### ISSUE TITLE
Loadbalancer : Add command fails with VM associated with a Vnet 

### ISSUE THREAD

**Issue by vikasmathod** [MSOpenTech/azure-xplat-cli#105]
Step 1: Create a Vnet with "affinity group" associated with it and not the location.
Step 2: Create a VM with the --virtual-network-name option.
Step 3: Add a load balancer for the deployment using the "internal-load-balancer add" command . The command fails. Please refer the screenshot below:

![vmvnet](https://cloud.githubusercontent.com/assets/6801546/4975630/0a623770-6901-11e4-9100-4e10a326fa5b.PNG)

**Comment by babumuralidharan** [comment]
@anuchandy do you have an update for this issue ?

**Comment by romangromov** [comment]
Please re-open if we still need this
