### ISSUE TITLE
Internal load balancer : Validations not handled

### ISSUE THREAD

**Issue by vikasmathod** [MSOpenTech/azure-xplat-cli#115]
Step 1: Add a loadbalancer to the created vm , here I am using the loadbalancername as '%'.

![l11](https://cloud.githubusercontent.com/assets/6801546/5216385/68431116-7658-11e4-8e11-0f81955dfecf.PNG)

Step 2: Try deleting the loadbalancer , the exception occurs.
![l21](https://cloud.githubusercontent.com/assets/6801546/5216388/6d56b784-7658-11e4-88b1-482d87c090c7.PNG)

Expected behaviour : Either a validation message has to be added preventing the user from entering special characters or delete functionality should be added for all characters.

**Comment by babumuralidharan** [comment]
@anuchandy can you open in bug in SDK please ?

**Comment by romangromov** [comment]
Please re-open if we still need this
