### ISSUE TITLE
disk command "update-by-name" for size is not working

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#138]
Please find the attached screenshot

![diskupdate_size](https://cloud.githubusercontent.com/assets/10084788/6966176/981daa0c-d974-11e4-9bcd-57c3861c343b.png)

**Comment by ruslangabitov** [comment]
@HimanshuBri can you please point me to a repo with this command?
I was not able to find 'vm disk update-by-name' in MSOpenTech/dev https://github.com/MSOpenTech/azure-xplat-cli/blob/dev/lib/commands/asm/vm._js#L527

**Comment by sreekanthbs** [comment]
@ruslangabitov yes I am also not able to find 'vm disk update-by-name' in MSOpenTech/dev.
I guess the command has been removed.
![image](https://cloud.githubusercontent.com/assets/11171941/9133996/d3ffdbfa-3d1d-11e5-83aa-8e76287aaca0.png).
