### ISSUE TITLE
Avoid 'Looking up the network security group' during nsg create,delete

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#189]
@romangromov 
We can implement this here also in asm as we have implemented in arm.
Have attached the screenshots for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/7703112/fc8bfd10-fe52-11e4-9edd-a3a7502b232b.png)
![image](https://cloud.githubusercontent.com/assets/10084788/7703146/72ce8218-fe53-11e4-97b1-cc65740d95b5.png)

**Comment by romangromov** [comment]
@HimanshuBri thank you, fixed it now, please make sure all is ok

**Comment by HimanshuBri** [comment]
@romangromov  LGTM.Hence closing the issue
<pre>
<code>
C:\May\22May\azure-xplat-cli-dev-asm-network>node bin/azure network nsg create TestNsg22M "East US"
info:    Executing command network nsg create
+ Creating a network security group "TestNsg22M"
+ Looking up the network security group "TestNsg22M"
data:    Name                            : TestNsg22M
data:    Location                        : East US
data:    Security group rules:
data:    Name                               Source IP           Source Port  Destination IP   Destination Port  Protocol  Type      Action  Priority  Default
data:    ---------------------------------  ------------------  -----------  ---------------  ----------------  --------  --------  ------  --------  -------
data:    ALLOW VNET OUTBOUND                VIRTUAL_NETWORK     *            VIRTUAL_NETWORK  *                 *         Outbound  Allow   65000     true
data:    ALLOW VNET INBOUND                 VIRTUAL_NETWORK     *            VIRTUAL_NETWORK  *                 *         Inbound   Allow   65000     true
data:    ALLOW AZURE LOAD BALANCER INBOUND  AZURE_LOADBALANCER  *            *                *                 *         Inbound   Allow   65001     true
data:    ALLOW INTERNET OUTBOUND            *                   *            INTERNET         *                 *         Outbound  Allow   65001     true
data:    DENY ALL OUTBOUND                  *                   *            *                *                 *         Outbound  Deny    65500     true
data:    DENY ALL INBOUND                   *                   *            *                *                 *         Inbound   Deny    65500     true
info:    network nsg create command OK

C:\May\22May\azure-xplat-cli-dev-asm-network>node bin/azure network nsg delete TestNsg22M -q
info:    Executing command network nsg delete
+ Deleting network security group "TestNsg22M"
info:    network nsg delete command OK
</code>
</pre>
