### ISSUE TITLE
ASM: 'network nsg rule create' not woking when specifying symbol along with name

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#191]
@romangromov. Please have a look at the same. Have attached the screenshot.
![image](https://cloud.githubusercontent.com/assets/10084788/7722851/86fc3d58-ff01-11e4-9c19-a881fa62f989.png)

**Comment by HimanshuBri** [comment]
Same issue happening with 'network nsg rule set' as well

**Comment by HimanshuBri** [comment]
@roman-boltunov. same issue for list, show, delete commands as well.

**Comment by roman-boltunov** [comment]
Hi @HimanshuBri. It's fixed now. Could you please check that everything works fine?

**Comment by HimanshuBri** [comment]
@roman-boltunov. Working fine. Thanks. Closing the issue.
