### ISSUE TITLE
ASM: network vnet subnet show json not returning anything

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#193]
@romangromov. @roman-boltunov. network vnet subnet show --json not returning anything
<pre>
<code>
C:\May\19May\azure-xplat-cli-dev-asm-network>node bin/azure network vnet subnet show XplatTestVnet Subnet-2 --json
{}
{}

Although this subnet is there in the given vnet

C:\May\19May\azure-xplat-cli-dev-asm-network>node bin/azure network vnet subnet list XplatTestVnet
info:    Executing command network vnet subnet list
+ Getting network configuration
data:    Name      Address prefix
data:    --------  --------------
data:    Subnet-1  10.0.0.0/23
data:    Subnet-2  10.0.2.0/23
info:    network vnet subnet list command OK
</code>
</pre>

**Comment by MikhailTryakhov** [comment]
Hi @HimanshuBri 
Could you please review it again

**Comment by HimanshuBri** [comment]
@MikhailTryakhov. Can you please tell me the branch for taking the latest code for this fix.

**Comment by anuchandy** [comment]
@HimanshuBri please use dev branch

**Comment by HimanshuBri** [comment]
@anuchandy in dev branch there is no commands to manage subnet for ASM mode

**Comment by MikhailTryakhov** [comment]
Hi @HimanshuBri, sorry - we were confused a bit cause of this error was reproduces in arm.
Thank you for clarification!
Now I've tested it in 'dev-asm-network' branch - it's fixed.
Could you please test it?

**Comment by HimanshuBri** [comment]
@MikhailTryakhov. still not working. Can you just confirm because there is no new code check-in.

**Comment by MikhailTryakhov** [comment]
@HimanshuBri  thank you! Please review it again

**Comment by HimanshuBri** [comment]
@MikhailTryakhov. Working fine. Thanks . Closing the issue.
![image](https://cloud.githubusercontent.com/assets/10084788/7797099/480d788e-0305-11e5-9e5b-b2f1a8c5f06a.png)
