### ISSUE TITLE
ASM: 'network application-gateway create' with same name giving wrong error

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#236]
Have attached screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/7933691/796673a6-093e-11e5-8417-6260f528fd2c.png)

**Comment by roman-boltunov** [comment]
@HimanshuBri it's fixed now. Could you please test it once again?

**Comment by HimanshuBri** [comment]
@roman-boltunov. Thanks. Fixed now. Closing the issue.
