### ISSUE TITLE
ASM: 'network application-gateway create' asking for vnet-subnet although it's not a mandatory parameter

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#237]
Have attached screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/7933823/9e8a4d82-093f-11e5-9f7d-c6361aa92da1.png)

**Comment by roman-boltunov** [comment]
Hi @HimanshuBri. According to the application gateway doc:
```
-subnet-names are required, CLI implementation will prompt for it if not provided.
```

**Comment by HimanshuBri** [comment]
@roman-boltunov. Can you share the doc please.

**Comment by roman-boltunov** [comment]
@HimanshuBri yes, please check you Microsoft email.

**Comment by HimanshuBri** [comment]
@roman-boltunov. Thanks. I got the same.

**Comment by HimanshuBri** [comment]
@roman-boltunov. You are true as per document CLI will prompt for subnet-name if not provided. But if you look at the below mentioned command, i think he also wanted subnet-name as a mandatory parameter but by mistake he might have wrote vnet name instead of subnet-name.
@anuchandy. Can you please confirm this as subnet-name is a mandatory parameter here and is required in all the cases. So it will be good if we include it in mandatory parameters list as well.
![image](https://cloud.githubusercontent.com/assets/10084788/7958428/eda74280-0a0c-11e5-8e9c-b1b73be4087c.png)

**Comment by anuchandy** [comment]
@roman-boltunov , @HimanshuBri - KG7 wrote this comment "Also add VNet as mandatory parameter" because he was not aware of nature of the positional parameter in CLI. We have a positional parameter for vnet which is enforced by CLI anyway. Now having only vnet is not sufficient, application gateway needs to be associated with a subnet under vnet, that's why we prompt for subnet.

**Comment by HimanshuBri** [comment]
@anuchandy. That is what i thought, since subnet-name is compulsory parameter and is required whenever we do 'network application-gateway create', why don't we make it mandatory instead of prompting it every time.

**Comment by roman-boltunov** [comment]
@anuchandy should we make this parameter mandatory?

**Comment by anuchandy** [comment]
@roman-boltunov  please make it as optional positional argument, if not provided then prompt for it.

**Comment by HimanshuBri** [comment]
Thanks @anuchandy for the confirmation.
@roman-boltunov. It is already implemented the way @anuchandy has asked. so we can close this. Thanks.

**Comment by roman-boltunov** [comment]
@HimanshuBri by the 'optional + positional' he means that we need to add it as positional, but we can also specify it as optional with --subnet-names. I will make it as positional asap.

**Comment by HimanshuBri** [comment]
@roman-boltunov. Thanks. Reopening the issue. will close it once it's fixed for optional parameter as well.

**Comment by roman-boltunov** [comment]
@HimanshuBri it's fixed now. Could you please check it?

**Comment by HimanshuBri** [comment]
@roman-boltunov. Thanks. Working fine now. Closing the issue.
