### ISSUE TITLE
ASM: 'network application-gateway show' not showing description parameter

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#240]
Have attached screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/7934455/3dcb2b64-0945-11e5-9fbd-4827debdf2fa.png)

**Comment by HimanshuBri** [comment]
@roman-boltunov. Similarly verbose output also not displaying description.
![image](https://cloud.githubusercontent.com/assets/10084788/7934485/9034278e-0945-11e5-88fa-9da921b3534d.png)

**Comment by roman-boltunov** [comment]
@HimanshuBri thank you. Will fix this asap.

**Comment by roman-boltunov** [comment]
@HimanshuBri it's fixed now. Could you please test it once again?

**Comment by HimanshuBri** [comment]
@roman-boltunov. Thanks. Fixed now. Closing the issue.
