### ISSUE TITLE
Asm: network gateway vnet connection list not working

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#245]
network gateway vnet connection list not working

<pre>
<code>

C:\June\2june\azure-xplat-cli-dev-asm-network>node bin/azure network gateway vnet connection list vnet1
info:    Executing command network gateway vnet connection list
+ Getting the network connections
error:   undefined is not a function
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network gateway vnet connection list command failed

</code>
</pre>

**Comment by MikhailTryakhov** [comment]
@HumanshiBri thank you , it's fixed now, could you please make sure that all is fine now?

**Comment by HimanshuBri** [comment]
@MikhailTryakhov. Not getting the list. Its showing No VPN gateway connections found. have attached the screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/7982468/f171f5fe-0ad4-11e5-870b-644ef6d346ec.png)

**Comment by MikhailTryakhov** [comment]
@HimanshuBri  it doesn't show any connections because List is empty. First, we need to add a connection to the collection. Currently, commands to manage connections are Blocked.

**Comment by HimanshuBri** [comment]
@MikhailTryakhov. Ok. Thanks. In that case will keep the issue open and will close when we have ther connection commands.

**Comment by HimanshuBri** [comment]
@MikhailTryakhov. Closing this issue. Thanks
