### ISSUE TITLE
ASM: 'network application-gateway create' error with multiple subnets

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#247]
Giving error when specifying more than one subnet. Have attached screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/7936669/82e8bfbe-0958-11e5-8259-6263790dc342.png)

**Comment by HimanshuBri** [comment]
Same error with set option as well

**Comment by roman-boltunov** [comment]
Adding @anuchandy. This is an external issue as the error comes from the server. In our application gateway doc we have a parameter for these commands called --subnet-names. But it looks like that server disallows us to specify multiple subnets.
Anu, could you please ask team responsible for application gateways if this behavior is expected.

**Comment by anuchandy** [comment]
In the command we accept multiple subnets as per API documentation. This should be a  server limitation for now, server error explain it. We might want to mark it as external.

**Comment by MikhailTryakhov** [comment]
Fixed
