### ISSUE TITLE
ASM: 'network application-gateway set' not working if not specifying '--gateway-size' or '-z' parameter

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#252]
Have attached screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/7959359/1242144a-0a16-11e5-84d4-090ba84f65fa.png)

**Comment by roman-boltunov** [comment]
@HimanshuBri it's fixed now. Could you test it once again?

**Comment by HimanshuBri** [comment]
@roman-boltunov. This error is fixed. 
But i am getting below mentioned error for non-existing application-gateway. I feel we need to change error message. Attached the screenshot.
![image](https://cloud.githubusercontent.com/assets/10084788/7960728/5712f13e-0a20-11e5-96a3-ff9d1445dbdb.png)

**Comment by roman-boltunov** [comment]
@HimanshuBri thank you! Fixed it.

**Comment by HimanshuBri** [comment]
@roman-boltunov. Working fine. Thanks. Closing the issue.
