### ISSUE TITLE
ASM: 'network application-gateway stop' showing unnecessary parameters.

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#253]
We don't need '-q or --quiet' here as this is a stop command not a delete command.
Have attached the screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/7959500/464f35b4-0a17-11e5-9fe2-8530a5d8f391.png)

**Comment by HimanshuBri** [comment]
@roman-boltunov. Although we can change the functionality of '-q or --quiet' by using this to ask as a confirmation as if user wants to stop an application-gateway or not.

**Comment by roman-boltunov** [comment]
@HimanshuBri there is no '-q' parameter in the doc. Will remove it asap.

**Comment by HimanshuBri** [comment]
@roman-boltunov. yes it's not there in the document. Remove it then. Thanks.

**Comment by roman-boltunov** [comment]
@HimanshuBri removed this parameter. Could you check that everything works as expected?

**Comment by HimanshuBri** [comment]
@roman-boltunov. Removed .Thanks. Closing the issue.
