### ISSUE TITLE
ASM: 'network route-table show' not displaying all parameters

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#259]
Can we have "label" in normal show and --verbose output as well, as we have in --json output.
Have attached screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/7980479/7b751cc8-0ac5-11e5-9dbd-9f70a889a29f.png)

**Comment by roman-boltunov** [comment]
@HimanshuBri Yep, will fix this asap.

**Comment by roman-boltunov** [comment]
@HimanshuBri fixed. Please make sure it works as expected.

**Comment by HimanshuBri** [comment]
@roman-boltunov. Working fine. Thanks. Closing the issue.
