### ISSUE TITLE
ASM: 'network route-table route set' not working for address-prefixes other than 0.0.0.0/0

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#261]
Have attached screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/7981209/fddd0612-0aca-11e5-9128-40b8c6247937.png)

**Comment by romangromov** [comment]
@HimanshuBri known issue, external, reported to @anuchandy, stay tuned, thank you

**Comment by romangromov** [comment]
Attaching  full http request/response here https://gist.github.com/romangromov/5a058e7e44cb6344c945#file-asm-route-table-set

**Comment by romangromov** [comment]
@sreekanthbs should be fixed now, please checkout `asm-network-fixes` branch

**Comment by sreekanthbs** [comment]
@romangromov It is working fine address-prefixes other than 0.0.0.0/0
![image](https://cloud.githubusercontent.com/assets/11171941/9355747/68ab6510-4699-11e5-9f17-221cbe90437c.png)

**Comment by romangromov** [comment]
@sreekanthbs yes, thanks, can we close this issue?

**Comment by sreekanthbs** [comment]
Yes @romangromov , @babumuralidharan please close this is issue
