### ISSUE TITLE
ASM: 'network route-table delete' and 'network route-table route delete' difference in implementation

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#262]
When i am trying to delete a non-existing 'route-table' it asks for a confirmation first [y/n] then tells the user that a particular 'route-table' doesn't exist whereas in 'route-table route' it directly tells us and throws error for non-existing 'route-table route'. I feel second second one is a better practice and we should follow same at both the places.
Have attached screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/7981850/67919a24-0acf-11e5-96fc-2294960c7272.png)

**Comment by roman-boltunov** [comment]
@HimanshuBri ok, will fix this.

**Comment by roman-boltunov** [comment]
@HimanshuBri fixed. Please make sure it works as expected.

**Comment by HimanshuBri** [comment]
@roman-boltunov  yes its working fine now
<pre>
<code>
C:\June\4june\azure-xplat-cli-dev-asm-network>node bin/azure network route-table delete --name Sample
info:    Executing command network route-table delete
+ Getting route table "Sample"
error:   Route table "Sample" not found
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network route-table delete command failed
</code>
</pre>
