### ISSUE TITLE
ASM: 'network gateway vnet diagnostics start' prompts for all other available options

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#266]
Since 'network gateway vnet diagnostics start' is prompting for all other options available it will be better if we can make them mandatory.
Have attached screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/7983255/ffded998-0adb-11e5-88ca-7efe7b766efd.png)

**Comment by roman-boltunov** [comment]
Adding @anuchandy. Is that suitable approach?

**Comment by anuchandy** [comment]
Please see the comment for https://github.com/MSOpenTech/azure-xplat-cli/issues/284 regarding the CLI command pattern. 

We used to accept all required argument as positional argument, but as we have more and more  parameters, declaring all of them as positional make makes command usage difficult as user need to specify arguments in specific order. This is why we accept some required params via optional arguments.

**Comment by HimanshuBri** [comment]
@anuchandy. Thanks. Closing the issue
