### ISSUE TITLE
ASM: 'network gateway vnet diagnostics get' not giving output with --json

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#267]
Have attached the screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/7983585/9592327a-0adf-11e5-8ff0-d9d3cedbe0a8.png)

**Comment by HimanshuBri** [comment]
@roman-boltunov. Also can you please tell us the use of -o,-p,-f parameters in below mentioned command.<code><pre>
E:\4486\4-June-2015\azure-xplat-cli-dev-asm-network>node bin/azure network gateway vnet diagnostics get vnet2 -h
help:    Get current diagnostics session in a virtual network gateway
help:
help:    Usage: network gateway vnet diagnostics get [options] <vnet-name>
help:
help:    Options:
help:      -h, --help                   output usage information
help:      -v, --verbose                use verbose output
help:      --json                       use json output
help:      -n, --vnet-name <vnet-name>  the name of the virtual network
help:      -o, --vendor <vendor>        the vendor of the VPN device
help:      -p, --platform <platform>    the platform of the VPN device
help:      -f, --os-family <os-family>  the OS family of the VPN device
help:      -s, --subscription <id>      the subscription id
</pre></code>

**Comment by roman-boltunov** [comment]
@HimanshuBri you can find them using 'network gateway vnet vpn-device list' command.

**Comment by roman-boltunov** [comment]
@HimanshuBri fixed. Please make sure it works as expected.

**Comment by HimanshuBri** [comment]
@roman-boltunov  yes working fine.Hence closing the issue
<pre>
<code>
C:\June\4june\azure-xplat-cli-dev-asm-network>node bin/azure network gateway vnet diagnostics get vnet2 --json
{
  "state": "Ready",
  "diagnosticsUrl": "https://gruntstg.blob.core.windows.net/disks/VNetGatewayDiagCapture_UTC_6_4_2015_11_46_05_AM_2.txt?sv=2014-02-14&sr=c&si=GatewayReadOnly&sig=3VMx
S5ZiBYyAF8vZLaRsX4SePGBOCc9CIddnRgQGK4A%3D",
  "statusCode": 200,
  "requestId": "e108d9d757a9aa9a95f1fe25c1adb9e0"
}
</code>
</pre>
