### ISSUE TITLE
ASM: 'network gateway vnet diagnostics get' giving same output even with -o, -p, -f options

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#270]
Have attached the screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/8000926/26fc1318-0b7e-11e5-9b9d-c4d3b7cefbdd.png)

**Comment by roman-boltunov** [comment]
@HimanshuBri my bad, these parameters are actually not for this command, these parameters used in 'vpn-device get-script' command, will remove them from 'diagnostics get'.

**Comment by HimanshuBri** [comment]
@roman-boltunov. Sure. thanks.

**Comment by roman-boltunov** [comment]
@HimanshuBri thanks, I fixed it. Please make sure it works as expected.

**Comment by HimanshuBri** [comment]
@roman-boltunov. Thanks it's fixed. Closing the issue.
