### ISSUE TITLE
ASM: 'network traffic-manager profile enable' showing unnecessary parameters

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#271]
-q not required. Please find the attached screenshot.
![image](https://cloud.githubusercontent.com/assets/10084788/8001765/7e11c136-0b86-11e5-9c6c-88f8f91ee6d6.png)

**Comment by HimanshuBri** [comment]
Same issue with disable as well. Please check the attached screenshot. 
![image](https://cloud.githubusercontent.com/assets/10084788/8002384/e7781bc0-0b8b-11e5-8c36-c5e78a78b128.png)

**Comment by romangromov** [comment]
@HimanshuBri thank you, will fix

**Comment by romangromov** [comment]
@HimanshuBri thank you, fixed now, please make sure all is fine

**Comment by HimanshuBri** [comment]
@romangromov. Working fine. Thanks. Closing the issue.
