### ISSUE TITLE
ASM: 'network traffic-manager profile enable' no output with --json 

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#272]
Have attached the screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/8001785/ac1fb3a8-0b86-11e5-86ef-c4598d489748.png)

**Comment by HimanshuBri** [comment]
Same issue with disable as well. Please check the screenshot. 
![image](https://cloud.githubusercontent.com/assets/10084788/8002356/a79f13aa-0b8b-11e5-85f5-e4e2d5661b93.png)

**Comment by romangromov** [comment]
@HimanshuBri thank you, will fix

**Comment by HimanshuBri** [comment]
@romangromov. Ok. Thanks.

**Comment by romangromov** [comment]
@HimanshuBri hello again, it's fixed for `enable` and `disable` commands as well. Please make sure it works fine now

**Comment by HimanshuBri** [comment]
@romangromov. Thanks. Working fine. Closing the issue.
