### ISSUE TITLE
ASM: 'network local-network create' giving error

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#273]
Have attached screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/8003015/44ae55fc-0b91-11e5-91c6-4477ad06878f.png)

**Comment by HimanshuBri** [comment]
Same issue with set command as well. Have attached the screenshot.
![image](https://cloud.githubusercontent.com/assets/10084788/8003265/9b0eecd4-0b93-11e5-8656-eeaea1cae603.png)

**Comment by HimanshuBri** [comment]
None of the commands related to 'network local-network' are working.

**Comment by HimanshuBri** [comment]
@MikhailTryakhov. 'network vnet local-network add' as well
![image](https://cloud.githubusercontent.com/assets/10084788/8004318/81f0557c-0b9c-11e5-9ccc-def84d95f068.png)

**Comment by romangromov** [comment]
@HimanshuBri thank you, this issue for all local-network commands should be fixed now

**Comment by HimanshuBri** [comment]
@romangromov. will check all the issues and let you know. Thanks.

**Comment by HimanshuBri** [comment]
@romangromov. Getting error when not specifying address-prefix and vpn-gateway-address
![image](https://cloud.githubusercontent.com/assets/10084788/8005186/b5065418-0ba4-11e5-916f-1d2002270c1f.png)

**Comment by romangromov** [comment]
Adding @MikhailTryakhov who owns this command

**Comment by HimanshuBri** [comment]
@romangromov, @MikhailTryakhov, @roman-boltunov. I feel we should change this error message as it is referring to some code.
![image](https://cloud.githubusercontent.com/assets/10084788/8005477/220738b8-0ba8-11e5-91d8-3ff587fe1f86.png)

**Comment by MikhailTryakhov** [comment]
@HimanshuBri thank you! This issue should be fixed for all local-network commands now.

**Comment by HimanshuBri** [comment]
@MikhailTryakhov. Thanks. Working fine. Closing the issue.
