### ISSUE TITLE
ASM: 'network local-network create' working with wrong vpn-gateway-address

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#278]
Have attached screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/8005833/c9bdb12e-0bab-11e5-9524-84b4275344df.png)

**Comment by HimanshuBri** [comment]
Same issue with set command as well. Please find the attached screenshot.
![image](https://cloud.githubusercontent.com/assets/10084788/8006299/1cb0d060-0bb0-11e5-831c-7d5b8313753a.png)

**Comment by MikhailTryakhov** [comment]
@HimanshuBri thanks! The issue should be fixed, now. Could you please confirm it?

**Comment by HimanshuBri** [comment]
@MikhailTryakhov. Thanks. Working fine. Closing the issue.

**Comment by HimanshuBri** [comment]
@MikhailTryakhov. Again working with wrong vpn-gateway-address. Please check the attached screenshot.
![image](https://cloud.githubusercontent.com/assets/10084788/8128050/4b2fa4f2-1119-11e5-950d-932e186b9409.png)

**Comment by MikhailTryakhov** [comment]
@HimanshuBri thank you! 
Seems it's external issue. '010' value becomes '8' because server uses Octal system when value starts from '0'. @anuchandy could you please confirm that it's external?

Attaching full request/response: https://gist.github.com/MikhailTryakhov/4bf9f2a019814e2b07ee

**Comment by anuchandy** [comment]
@HimanshuBri 

This is expected, as @MikhailTryakhov  mentioned IP address can be referred using octal representation as well.

$ ping 134.170.185.056

Pinging 134.170.185.46 with 32 bytes of data:

**Comment by HimanshuBri** [comment]
@anuchandy. Thanks. Its ok if it is converting the number using octal representation.

**Comment by MikhailTryakhov** [comment]
@HimanshuBri hi, if everything is OK now, could you please close the issue?

**Comment by HimanshuBri** [comment]
@MikhailTryakhov. Everything looks good. Closing the issue
