### ISSUE TITLE
ASM: 'network local-network set' showing wrong error message with wrong address-prefix

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#279]
Have attached screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/8006189/1848ccc2-0baf-11e5-8245-40d486ba6a29.png)

**Comment by MikhailTryakhov** [comment]
@HimanshuBri thank you! Currently, this issue should be fixed. Could you please confirm that it's working now?

**Comment by HimanshuBri** [comment]
@MikhailTryakhov. Thanks. Working fine. Closing the issue.
