### ISSUE TITLE
ASM: 'network local-network list' not displaying all the address-prefixes in case of multiple address-prefixes

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#280]
Have attached screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/8006456/bb672b04-0bb1-11e5-913c-5fbf81a55355.png)

**Comment by HimanshuBri** [comment]
Same issue in case of --verbose output as well. Although working fine for --json output. Please check the attached screenshot.
![image](https://cloud.githubusercontent.com/assets/10084788/8006478/f7b0118e-0bb1-11e5-900d-fca5e1a26c63.png)

**Comment by romangromov** [comment]
@HimanshuBri it's by design. When we have multiple address-prefixes then it will be truncated with 3 dots

**Comment by HimanshuBri** [comment]
@romangromov. Ok. thanks. Closing the issue.
