### ISSUE TITLE
ASM: 'network -h' giving error.

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#281]
Please check the code snippet. 2nd and 3rd last line
<code><pre>

E:\4486\5-June-2014\azure-xplat-cli-dev-asm-network (2)>node bin/azure network -h
help:    Commands to manage your Networks
help:
help:    Export the current Network configuration to a file
help:      network export [options] <file-path>
help:
help:    Set the Network configuration from a json file
help:      network import [options] <file-path>
help:
help:    Commands to manage your DNS Servers
help:      network dnsserver list [options]
help:      network dnsserver register [options] <dnsIp>
help:      network dnsserver unregister [options] <dnsIp>
help:
help:    Commands to manage your Virtual Networks
help:      network vnet list [options]
help:      network vnet show <vnet> [options]
help:      network vnet delete [options] <vnet>
help:      network vnet create [options] <vnet>
help:
help:    Commands to manage association between virtual network and local network
help:      network vnet local-network add [options] <name> <local-network-name>
help:      network vnet local-network remove [options] <name> <local-network-name>
help:
help:    Commands to manage your Virtual Network static IP addresses
help:      network vnet static-ip check [options] <vnet> <ip-address>
help:
help:    Commands to manage your Virtual Network Subnets
help:      network vnet subnet create [options] <vnet-name> <name>
help:      network vnet subnet set [options] <vnet-name> <name>
help:      network vnet subnet list [options] <vnet-name>
help:      network vnet subnet show [options] <vnet-name>
help:      network vnet subnet delete [options] <vnet-name> <name>
help:
help:    Commands to manage subnet route tables
help:      network vnet subnet route-table add [options] <vnet-name> <subnet-name> <route-table-name>
help:      network vnet subnet route-table delete [options] <vnet-name> <subnet-name> <route-table-name>
help:      network vnet subnet route-table show [options] <vnet-name> <subnet-name>
help:
help:    Commands to manage your reserved public Virtual IP addresses
help:      network reserved-ip list [options]
help:      network reserved-ip show [options] <name>
help:      network reserved-ip delete [options] <name>
help:      network reserved-ip create [options] <name> <location>
help:
help:    Commands to manage Network Security Groups
help:      network nsg create [options] <name> <location>
help:      network nsg list [options]
help:      network nsg show [options] <name>
help:      network nsg delete [options] <name>
help:
help:    Commands to manage Network Security Group Rules
help:      network nsg rule create [options] <nsg-name> <name>
help:      network nsg rule set [options] <nsg-name> <name>
help:      network nsg rule list [options] <nsg-name>
help:      network nsg rule show [options] <nsg-name> <name>
help:      network nsg rule delete [options] <nsg-name> <name>
help:
help:    Commands to manage Network Security Group of subnet
help:      network nsg subnet add [options] <nsg-name> <vnet-name> <subnet-name>
help:      network nsg subnet remove [options] <nsg-name> <vnet-name> <subnet-name>
help:
help:    Commands to manage local network
help:      network local-network create [options] <name>
help:      network local-network set [options] <name>
help:      network local-network list [options]
help:      network local-network show [options]
help:      network local-network delete [options] <name>
help:
help:    Commands to manage gateways
help:
help:    Commands to manage vpn gateways
help:      network gateway vnet create [options] <vnet-name>
help:      network gateway vnet show [options] <vnet-name>
help:      network gateway vnet delete [options] <vnet-name>
help:      network gateway vnet resize [options] <vnet-name> <sku>
help:      network gateway vnet reset [options] <vnet-name>
help:      network gateway vnet set-default-site [options] <vnet-name> <site-name>
help:      network gateway vnet remove-default-site [options] <vnet-name>
help:
help:    Commands to manage VPN gateway shared key
help:      network gateway vnet shared-key set [options] <vnet-name> <key-value>
help:      network gateway vnet shared-key reset [options] <vnet-name> <key-length>
help:
help:    Commands to manage vpn gateway connection
help:      network gateway vnet connection list [options] <vnet-name>
help:
help:    Commands to manage VPN gateway VPN devices
help:      network gateway vnet vpn-device list [options]
help:      network gateway vnet vpn-device get-script [options] <vnet-name>
help:
help:    Commands to manage VPN gateway diagnostics session
help:      network gateway vnet diagnostics start [options] <vnet-name>
help:      network gateway vnet diagnostics stop [options] <vnet-name>
help:      network gateway vnet diagnostics get [options] <vnet-name>
help:
help:    Commands to manage route table
help:      network route-table create [options] <name> <location>
help:      network route-table show [options] <name>
help:      network route-table list [options]
help:      network route-table delete [options] <name>
help:
help:    Commands to manage route table routes
help:      network route-table route set [options] <route-table-name> <name> <address-prefix> <next-hop-type>
help:      network route-table route delete [options] <route-table-name> <name>
help:
help:    Commands to manage application gateway
help:      network application-gateway create [options] <name> <vnet-name>
help:      network application-gateway set [options] <name> <vnet-name>
help:      network application-gateway list [options]
help:      network application-gateway show [options] <name>
help:      network application-gateway delete [options] <name>
help:      network application-gateway start [options] <name>
help:      network application-gateway stop [options] <name>
help:      network application-gateway export-config [options] <name> <file-path>
help:      network application-gateway import-config [options] <name> <import-from-file>
help:
error:   Cannot read property 'cyan' of undefined
info:    Error information has been recorded to C:\Users\himanshu.agarwal\.azure\azure.err

E:\4486\5-June-2014\azure-xplat-cli-dev-asm-network (2)>
</pre><?code>

**Comment by romangromov** [comment]
@HimanshuBri thank you, it's fixed now, please make sure all is fine

**Comment by HimanshuBri** [comment]
@romangromov. Thanks. Working fine. Closing the issue.
