### ISSUE TITLE
ASM : vm endpoint create not giving output in proper format 

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#289]
vm endpoint create , vm endpoint create --json , vm endpoint create -vv all giving output in same format .
<pre>
<code>
C:\June\9june\azure-xplat-cli-dev>node bin/azure vm endpoint create XplatTesttVm  8080 -n TestVmEndpt
info:    Executing command vm endpoint create
{ error: null,
  endPoint:
   { port: 8080,
     localPort: 8080,
     protocol: 'tcp',
     name: 'TestVmEndpt' } }

C:\June\9june\azure-xplat-cli-dev>node bin/azure vm endpoint create XplatTesttVm  8080 -n TestVmEndpt -vv
info:    Executing command vm endpoint create
{ error: null,
  endPoint:
   { port: 8080,
     localPort: 8080,
     protocol: 'tcp',
     name: 'TestVmEndpt' } }
{ error: null,
  endPoint:
   { port: 8080,
     localPort: 8080,
     protocol: 'tcp',
     name: 'tcp-8080-8080' } }
</code>
</pre>

**Comment by anuchandy** [comment]
@HimanshuBri I have updated the dev branch, could you please validate

**Comment by HimanshuBri** [comment]
@anuchandy Yes.Now working fine.Closing the issue
<pre>
<code>
C:\June\10june\azure-xplat-cli-dev>node bin/azure vm  endpoint create XplatestTVm 23 23 -n EndpT
info:    Executing command vm endpoint create
+ Getting virtual machines
+ Reading network configuration
+ Updating network configuration
info:    vm endpoint create command OK
</code>
</pre>
