### ISSUE TITLE
ASM: vm endpoint create not giving error for non-existing vm 

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#290]
Here sample is non existing vm .But no error message is coming in output.
<pre>
<code>
C:\June\9june\azure-xplat-cli-dev>node bin/azure vm endpoint create Sample 8080 80
info:    Executing command vm endpoint create
{ error: null,
  endPoint:
   { port: 8080,
     localPort: 80,
     protocol: 'tcp',
     name: 'tcp-8080-80' } }
</code>
</pre>

**Comment by anuchandy** [comment]
@HimanshuBri I have updated the dev branch, could you please validate

**Comment by HimanshuBri** [comment]
@anuchandy  yes working as expected.Closing the issue
<pre>
<code>
C:\June\10june\azure-xplat-cli-dev>node bin/azure vm endpoint create Sample 27 27
info:    Executing command vm endpoint create
+ Getting virtual machines
error:   No VM with name "Sample" found
error:   vm endpoint create command failed
</code>
</pre>
