### ISSUE TITLE
ASM:vm endpoint create should have optional parameter for local-port in the help 

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#292]
vm endpoint create should have optional parameter(like -k or something ) for local-port in the help 
<pre>
<code>
help:    Usage: vm endpoint create [options] <vm-name> <public-port> [local-port]
help:
help:    Options:
help:      -h, --help                                                     output usage information
help:      -v, --verbose                                                  use verbose output
help:      --json                                                         use json output
help:      -d, --dns-name <name>                                          filter VMs for the specified DNS name
help:      -n, --name <name>                                              the endpoint name
help:      -o, --protocol <protocol>                                      the transport layer protocol for the endpoint (tcp or udp)
help:      -m, --idle-timeout <idle-timeout>                              timeout for tcp idle connection specified in minutes
help:      -t, --probe-port <port>                                        the virtual machine port to use to inspect the availability status
help:      -r, --probe-protocol <protocol>                                the protocol to use to inspect the availability status
help:      -p, --probe-path <path>                                        the relative path to inspect the availability status
help:      -u, --direct-server-return <direct-server-return>              enable or disable direct server return on this endpoint, valid values are [Enabled, Disabled
] Disabled by default
help:      -b, --load-balanced-set-name <load-balanced-set-name>          the load-balancer set name
help:      -i, --internal-load-balancer-name <name>                       the internal load balancer name
help:      -a, --load-balancer-distribution <load-balancer-distribution>  the load balancer distribution, valid values are [sourceIP, sourceIPProtocol, None]
help:      -s, --subscription <id>                                        the subscription id
</code>
</pre>

**Comment by anuchandy** [comment]
@HimanshuBri I have updated the dev branch, could you please validate

**Comment by HimanshuBri** [comment]
@anuchandy yes now the optional parameter for local-port  is added in the help.Thanks.
Closing the issue
<pre>
<code>
C:\June\10june\azure-xplat-cli-dev>node bin/azure vm endpoint create -h
help:    Create a VM endpoint
help:
help:    Usage: vm endpoint create [options] <vm-name> <public-port> [local-port]
help:
help:    Options:
help:      -h, --help                                                     output usage information
help:      -v, --verbose                                                  use verbose output
help:      --json                                                         use json output
help:      -d, --dns-name <name>                                          filter VMs for the specified DNS name
help:      -n, --name <name>                                              the endpoint name
<b>help:      -k, --local-port <local-port>                                  the local port</b>
help:      -o, --protocol <protocol>                                      the transport layer protocol for the endpoint (tcp or udp)
help:      -m, --idle-timeout <idle-timeout>                              timeout for tcp idle connection specified in minutes
help:      -t, --probe-port <port>                                        the virtual machine port to use to inspect the availability status
help:      -r, --probe-protocol <protocol>                                the protocol to use to inspect the availability status
help:      -p, --probe-path <path>                                        the relative path to inspect the availability status
help:      -u, --direct-server-return <direct-server-return>              enable or disable direct server return on this endpoint, valid values are [Enabled, Disabled
] Disabled by default
help:      -b, --load-balanced-set-name <load-balanced-set-name>          the load-balancer set name
help:      -i, --internal-load-balancer-name <name>                       the internal load balancer name
help:      -a, --load-balancer-distribution <load-balancer-distribution>  the load balancer distribution, valid values are [sourceIP, sourceIPProtocol, None]
help:      -s, --subscription <id>                                        the subscription id
</code>
</pre>
