### ISSUE TITLE
ASM:vm endpoint set not working 

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#296]
<pre>
<code>

C:\June\9june\azure-xplat-cli-dev>node bin/azure vm endpoint list DnDIntelliJ
info:    Executing command vm endpoint list
+ Getting virtual machines
data:    Name            Protocol  Public Port  Private Port  Virtual IP       EnableDirectServerReturn  Load Balanced
data:    --------------  --------  -----------  ------------  ---------------  ------------------------  -------------
data:    Remote Desktop  tcp       3389         3389          191.236.114.223  false                     No
data:    SSH             tcp       22           22            191.236.114.223  false                     No
<b>data:    tcp-23-23       tcp       23           23            191.236.114.223  false                     No</b>
info:    vm endpoint list command OK

C:\June\9june\azure-xplat-cli-dev>node bin/azure vm endpoint set DnDIntelliJ  tcp-23-23 -n DndEndPt -b 81 -c 82 -o tcp -t 4444 -r tcp
info:    Executing command vm endpoint set
+ Getting virtual machines
+ Reading network configuration
error:   epToUpdate is not defined
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err

C:\June\9june\azure-xplat-cli-dev>node bin/azure vm endpoint set DnDIntelliJ  tcp-23-23 -n DndEndPt
info:    Executing command vm endpoint set
+ Getting virtual machines
+ Reading network configuration
error:   epToUpdate is not defined
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
</code>
</pre>

**Comment by anuchandy** [comment]
@HimanshuBri I have updated the dev branch, could you please validate

**Comment by HimanshuBri** [comment]
@anuchandy  yes now working fine.Hence closing the issue
<pre>
<code>
C:\June\10june\azure-xplat-cli-dev>node bin/azure vm  endpoint set XplatestTVm EndpT -n EndPt -l LbSet -b 24 -c 24 -o tcp -m 15 -t 4444 -r tcp  -a sourceIP
info:    Executing command vm endpoint set
+ Getting virtual machines
+ Reading network configuration
+ Updating network configuration
info:    vm endpoint set command OK
</code>
</pre>
