### ISSUE TITLE
ASM: vm endpoint create & set command must  be consistent for optional parameters

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#305]
load-balanced-set-name has -b option in create command & -l twice in set command
Can we use same option for both create & set command?

<pre>
<code>
C:\June\10june\azure-xplat-cli-dev>node bin/azure vm endpoint create -h
help:    Create a VM endpoint
help:
help:    Usage: vm endpoint create [options] <vm-name> <public-port> [local-port]
help:
help:    Options:
help:      -h, --help                                                     output usage information
help:      -v, --verbose                                                  use verbose output
help:      --json                                                         use json output
help:      -d, --dns-name <name>                                          filter VMs for the specified DNS name
help:      -n, --name <name>                                              the endpoint name
help:      -k, --local-port <local-port>                                  the local port
help:      -o, --protocol <protocol>                                      the transport layer protocol for the endpoint (tcp or udp)
help:      -m, --idle-timeout <idle-timeout>                              timeout for tcp idle connection specified in minutes
help:      -t, --probe-port <port>                                        the virtual machine port to use to inspect the availability status
help:      -r, --probe-protocol <protocol>                                the protocol to use to inspect the availability status
help:      -p, --probe-path <path>                                        the relative path to inspect the availability status
help:      -u, --direct-server-return <direct-server-return>              enable or disable direct server return on this endpoint, valid values are [Enabled, Disabled
] Disabled by default
<b>help:      -b, --load-balanced-set-name <load-balanced-set-name>          the load-balancer set name</b>
help:      -i, --internal-load-balancer-name <name>                       the internal load balancer name
help:      -a, --load-balancer-distribution <load-balancer-distribution>  the load balancer distribution, valid values are [sourceIP, sourceIPProtocol, None]
help:      -s, --subscription <id>                                        the subscription id

C:\June\10june\azure-xplat-cli-dev>node bin/azure vm endpoint set -h
help:    Update a VM endpoint
help:
help:    Usage: vm endpoint set [options] <vm-name> <endpoint-name>
help:
help:    Options:
help:      -h, --help                                                       output usage information
help:      -v, --verbose                                                    use verbose output
help:      --json                                                           use json output
help:      -d, --dns-name <name>                                            filter VMs for the specified DNS name
help:      -n, --new-endpoint-name <new-endpoint-name>                      the new name for the endpoint
<b>help:      -l, --load-balanced-set-name <load-balanced-set-name>            the load balanced set name</b>
help:      -b, --public-port <public-port>                                  the public port
help:      -c, --local-port <local-port>                                    the local port
<b>help:      -l, --load-balancer-set-name <load-balancer-set-name>            the load balancer set name</b>
help:      -o, --protocol <protocol>                                        the transport layer protocol for the endpoint (tcp or udp)
help:      -m, --idle-timeout <idle-timeout>                                connection timeout for tcp idle connection, specified in minutes
help:      -t, --probe-port <probe-port>                                    the virtual machine port to use to inspect the availability status
help:      -r, --probe-protocol <probe-protocol>                            the protocol to use to inspect the availability status
help:      -p, --probe-path <probe-path>                                    the relative path to inspect the availability status
help:      -u, --direct-server-return <direct-server-return>                enable or disable direct server return on endpoint, valid values are [Enabled, Disabled] D
isabled by default
help:      -i, --internal-load-balancer-name <internal-load-balancer-name>  the internal load balancer name
help:      -a, --load-balancer-distribution <load-balancer-distribution>    the load balancer distribution, valid values are [sourceIP, sourceIPProtocol, None]
help:      -s, --subscription <id>                                          the subscription id
</code>
</pre>

**Comment by anuchandy** [comment]
@HimanshuBri thanks, fixed, please validate

**Comment by HimanshuBri** [comment]
@anuchandy  yes its fixed.thanks
