### ISSUE TITLE
ASM: vm endpoint create giving error with direct-server-return option

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#306]
<pre>
<code>
C:\June\10june\azure-xplat-cli-dev>node bin/azure vm endpoint create XplatestTVm 29 29 -n EndPt2 -o tcp -m 20 -t 4222 -r http -p /prob/listnerr -u Enabled
info:    Executing command vm endpoint create
+ Getting virtual machines
+ Reading network configuration
+ Updating network configuration
error:   A parameter was incorrect
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   vm endpoint create command failed
</code>
</pre>

**Comment by anuchandy** [comment]
@HimanshuBri can you please check again?

**Comment by HimanshuBri** [comment]
@anuchandy yes its working fine now.Thanks
<pre>
<code>
C:\June\11june\azure-xplat-cli-dev>node bin/azure vm endpoint create XplatestTVm 29 29 -n EndPt -o tcp -m 20 -t 4222 -r http -p /prob/listnerr -u Enabled
info:    Executing command vm endpoint create
+ Getting virtual machines
+ Reading network configuration
+ Updating network configuration
info:    vm endpoint create command OK
</code>
</pre>
