### ISSUE TITLE
ASM: vm endpoint set not working for direct-server-return option

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#310]
<pre>
<code>
C:\June\11june\azure-xplat-cli-dev>node bin/azure vm endpoint set XplatestTVm EndPt -u Disabled
info:    Executing command vm endpoint set
+ Getting virtual machines
+ Reading network configuration
+ Updating network configuration
error:   Windows Azure does not support modifying Direct Server Return settings on an existing endpoint. Please delete and recreate the endpoint with Direct Server Re
turn set to True.
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   vm endpoint set command failed

<b>This is the create command is used</b>
C:\June\11june\azure-xplat-cli-dev>node bin/azure vm endpoint create XplatestTVm 29 29 -n EndPt -o tcp -m 20 -t 4222 -r http -p /prob/listnerr -u Enabled
info:    Executing command vm endpoint create
+ Getting virtual machines
+ Reading network configuration
+ Updating network configuration
info:    vm endpoint create command OK
</code>
</pre>

**Comment by anuchandy** [comment]
@HimanshuBri as of now server won't support updating this property, server is returning meaningful error in this case, this is external.

**Comment by romangromov** [comment]
Please re-open if we need this
