### ISSUE TITLE
ASM: 'network vnet local-network remove' giving error

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#313]
Please find the attached screenshot.
![image](https://cloud.githubusercontent.com/assets/10084788/8104548/35de4fb0-104f-11e5-9476-85b8c7bb1a8d.png)

**Comment by roman-boltunov** [comment]
@HimanshuBri it is fixed now. Please make sure it works fine now.

**Comment by HimanshuBri** [comment]
@roman-boltunov. I feel in the error message in below screenshot instead of gateway we should write local-network.
![image](https://cloud.githubusercontent.com/assets/10084788/8105470/1b1f6aee-1057-11e5-81ad-428cf330cb95.png)

**Comment by roman-boltunov** [comment]
@HimanshuBri thanks. Changed it.

**Comment by HimanshuBri** [comment]
@roman-boltunov. thanks. Everything looks good. Closing the issue.
