### ISSUE TITLE
ASM: 'network application-gateway address-pool add' cannot see added address-pool

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#316]
Please check the attached screenshot.
![image](https://cloud.githubusercontent.com/assets/10084788/8105983/543dd0fa-105b-11e5-9292-a539419c2eeb.png)

**Comment by romangromov** [comment]
@HimanshuBri please use `azure network application-gateway config show` command to get details about app gateway config

**Comment by HimanshuBri** [comment]
@romangromov. Thanks. Working fine. Closing the issue.
