### ISSUE TITLE
ASM: 'network application-gateway http-listener add' wrong error message for non-existing frontend-port

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#327]
Please find the attached screenshot.
![image](https://cloud.githubusercontent.com/assets/10084788/8157380/fe33798e-1371-11e5-9773-d379f598cfad.png)

**Comment by MikhailTryakhov** [comment]
@HimanshuBri thank you! Currently, it should be fixed.

**Comment by HimanshuBri** [comment]
@MikhailTryakhov. Workng fine. Thanks. closing the issue.
