### ISSUE TITLE
ASM: 'network dnsserver list' giving error.

### ISSUE THREAD

**Issue by MikhailTryakhov** [MSOpenTech/azure-xplat-cli#330]
Please see screenshot below:

![untitled](https://cloud.githubusercontent.com/assets/3079588/8158309/b4621cc8-1364-11e5-96d4-ef75eb685fad.png)

**Comment by MikhailTryakhov** [comment]
@HimanshuBri we accidentally found this issue. We are not owns `dnsserver` commands set, however fix was pretty straightforward, so we made it. Could you please confirm it's working fine now?

**Comment by MikhailTryakhov** [comment]
@anuchandy could you please confirm that it's external?

**Comment by HimanshuBri** [comment]
@MikhailTryakhov. Sure. Will check it and let you know.

**Comment by HimanshuBri** [comment]
@MikhailTryakhov. I am not getting this issue even in the old code.

**Comment by HimanshuBri** [comment]
@MikhailTryakhov. Getting this error whenever list is empty.

**Comment by HimanshuBri** [comment]
@MikhailTryakhov. Working fine now. Thanks.

**Comment by MikhailTryakhov** [comment]
@HimanshuBri thanks!
