### ISSUE TITLE
ASM: vm create with --ssh, --ssh-cert is not working

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#342]
VM create with --ssh and --ssh-cert is failing to create VM
<pre>
<code>
C:\Jun2015\17-Jun\azure-xplat-cli-dev>node bin/azure vm create TestVMDelete VMImage -g azureuser -p Brillio@2015 -t C:\Users\sreekanth.bandaru\.ssh\github_rsa.p
ub -e 22 -l "West US"
info:    Executing command vm create
warn:    --vm-size has not been specified. Defaulting to "Small".
error:   --ssh (SSH port, default to 22) is required when --ssh-cert or --ssh-password is specified
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
error:   vm create command failed
</code>
</pre>
<pre>
<code>
C:\Jun2015\17-Jun\azure-xplat-cli-dev>node bin/azure vm create TestVMDelete VMImage -g azureuser -p Brillio@2015 -t C:\Users\sreekanth.bandaru\.ssh\github_rsa.p
ub -e 22 -l "West US" -vv
info:    Executing command vm create
warn:    --vm-size has not been specified. Defaulting to "Small".
error:   --ssh (SSH port, default to 22) is required when --ssh-cert or --ssh-password is specified
silly:   { stack: 'Error: --ssh (SSH port, default to 22) is required when --ssh-cert or --ssh-password is specified\n    at VMClient._.extend.createVM (C:\\Jun
2015\\17-Jun\\azure-xplat-cli-dev\\lib\\commands\\asm\\vm\\vmclient.js:78:25)\n    at AzureCli.<anonymous> (C:\\Jun2015\\17-Jun\\azure-xplat-cli-dev\\lib\\comma
nds\\asm\\vm._js:59:16)\n    at AzureCli.<anonymous> (C:\\Jun2015\\17-Jun\\azure-xplat-cli-dev\\lib\\cli.js:216:12)\n    at AzureCli.<anonymous> (C:\\Jun2015\\1
7-Jun\\azure-xplat-cli-dev\\node_modules\\commander\\lib\\commander.js:235:8)\n    at AzureCli.emit (events.js:110:17)\n    at AzureCli.Command.parseArgs (C:\\J
un2015\\17-Jun\\azure-xplat-cli-dev\\node_modules\\commander\\lib\\commander.js:405:12)\n    at AzureCli.Command.parse (C:\\Jun2015\\17-Jun\\azure-xplat-cli-dev
\\node_modules\\commander\\lib\\commander.js:351:15)\n    at AzureCli.<anonymous> (C:\\Jun2015\\17-Jun\\azure-xplat-cli-dev\\lib\\cli.js:510:20)\n    at AzureCl
i.emit (events.js:107:17)\n    at AzureCli.Command.parseArgs (C:\\Jun2015\\17-Jun\\azure-xplat-cli-dev\\node_modules\\commander\\lib\\commander.js:407:12)\n', m
essage: '--ssh (SSH port, default to 22) is required when --ssh-cert or --ssh-password is specified' }
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
verbose: Error: --ssh (SSH port, default to 22) is required when --ssh-cert or --ssh-password is specified
    at VMClient._.extend.createVM (C:\Jun2015\17-Jun\azure-xplat-cli-dev\lib\commands\asm\vm\vmclient.js:78:25)
    at AzureCli.<anonymous> (C:\Jun2015\17-Jun\azure-xplat-cli-dev\lib\commands\asm\vm._js:59:16)
    at AzureCli.<anonymous> (C:\Jun2015\17-Jun\azure-xplat-cli-dev\lib\cli.js:216:12)
    at AzureCli.<anonymous> (C:\Jun2015\17-Jun\azure-xplat-cli-dev\node_modules\commander\lib\commander.js:235:8)
    at AzureCli.emit (events.js:110:17)
    at AzureCli.Command.parseArgs (C:\Jun2015\17-Jun\azure-xplat-cli-dev\node_modules\commander\lib\commander.js:405:12)
    at AzureCli.Command.parse (C:\Jun2015\17-Jun\azure-xplat-cli-dev\node_modules\commander\lib\commander.js:351:15)
    at AzureCli.<anonymous> (C:\Jun2015\17-Jun\azure-xplat-cli-dev\lib\cli.js:510:20)
    at AzureCli.emit (events.js:107:17)
    at AzureCli.Command.parseArgs (C:\Jun2015\17-Jun\azure-xplat-cli-dev\node_modules\commander\lib\commander.js:407:12)

error:   vm create command failed
</code>
</pre>

**Comment by ruslangabitov** [comment]
@sreekanthbs I was not able to reproduce this bug on the latest build, there were some changes to the   vmclient recently. Can you please verify it using latest code from dev branch?

**Comment by sreekanthbs** [comment]
@ruslangabitov With the latest build the error is not coming. It is working fine, so closing the issue.
<pre>
<code>
C:\Jul2015\Jul-29\azure-xplat-cli-dev>node bin/azure vm create TestVMDelete VMImage -g azureuser -p Brillio@2015 -t C:\Users\sreekanth.bandaru\.ssh\github_rsa.p
ub -e 22 -l "West US"
info:    Executing command vm create
warn:    --vm-size has not been specified. Defaulting to "Small".
+ Looking up image VMImage
+ Looking up cloud service
info:    cloud service TestVMDelete not found.
+ Creating cloud service
+ Configuring certificate
+ Creating VM
info:    vm create command OK
</code>
</pre>
