### ISSUE TITLE
ARM: 'vm image list' giving different OS for same offer and sku

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#354]
Please find the attached screenshot. 
![image](https://cloud.githubusercontent.com/assets/10084788/8280428/cde2a3fc-18fa-11e5-9111-ab4625125703.png)

**Comment by ruslangabitov** [comment]
Fixed here: https://github.com/MSOpenTech/azure-xplat-cli/pull/469, please verify.

**Comment by sreekanthbs** [comment]
@ruslangabitov yes its working fine now 
![image](https://cloud.githubusercontent.com/assets/11171941/9221480/45411016-4108-11e5-89ed-b68ae4a9cb21.png)

**Comment by babumuralidharan** [comment]
LGTM...
