### ISSUE TITLE
Asm:network vnet local-network remove not working 

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#355]
<pre>
<code>
C:\June\17june\azure-xplat-cli-dev-asm-network>node bin/azure network vnet local-network remove clitestlocvnet7922 clitestlocnet3134
info:    Executing command network vnet local-network remove
+ Getting network configuration
error:   Local network "clitestlocnet3134" does not exist
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network vnet local-network remove command failed

C:\June\17june\azure-xplat-cli-dev-asm-network>node bin/azure network local-network list
info:    Executing command network local-network list
+ Getting network configuration
data:    Name               Gateway address  Address space
data:    -----------------  ---------------  -------------
data:    CliTestlocNet3134  20.20.20.20      10.0.0.0/19
data:    CliTestlocNet5354  20.20.20.20      10.0.0.0/19
data:    LocalNetwork       191.236.86.5     10.16.0.45/29
data:    vnet1lnet          100.100.100.100  10.1.0.0/16
data:    vnet2lnet          200.200.200.200  10.2.0.0/16
data:    Vpn                10.32.0.0        10.16.0.0/27
info:    network local-network list command OK
</pre>

**Comment by roman-boltunov** [comment]
@HimanshuBri it is fixed now. Could you please test it once more?

**Comment by HimanshuBri** [comment]
@roman-boltunov  yes its working fine now.Thanks
