### ISSUE TITLE
ARM: VM create with image urn MicrosoftWindowsServer:WindowsServer:2008-R2-SP1:2.0.201502 is failing

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#368]
ARM VM create with image URN MicrosoftWindowsServer:WindowsServer:2008-R2-SP1:2.0.201502 is giving error <b>The subscription is not authorized.</b>

<pre>
<code>
C:\Jun2015\22-Jun\azure-xplat-cli-sprint-50>node bin/azure vm create xplatTestGExtension xplatvmExt eastus Windows -f xplatnicExt -Q MicrosoftWindowsServer:Wind
owsServer:2008-R2-SP1:2.0.201502 -u azureuser -p Brillio@2015 -o xplatstoragext3726 -R xplatstoragecntext7927 -F xplatvnetExt -P 10.0.0.0/16 -j xplatsubnetExt -
k 10.0.0.0/24 -i xplatipExt -w xplatdnsext
info:    Executing command vm create
+ Looking up the VM "xplatvmExt"
info:    Using the VM Size "Standard_A1"
info:    The [OS, Data] Disk or image configuration requires storage account
+ Looking up the storage account xplatstoragext3726
info:    Could not find the storage account "xplatstoragext3726", trying to create new one
+ Creating storage account "xplatstoragext3726" in "eastus"
+ Looking up the storage account xplatstoragext3726
+ Looking up the NIC "xplatnicExt"
info:    An nic with given name "xplatnicExt" not found, creating a new one
+ Looking up the virtual network "xplatvnetExt"
info:    Preparing to create new virtual network and subnet
+ Creating a new virtual network "xplatvnetExt" [address prefix: "10.0.0.0/16"] with subnet "xplatsubnetExt" [address prefix: "10.0.0.0/24"]
+ Looking up the virtual network "xplatvnetExt"
+ Looking up the subnet "xplatsubnetExt" under the virtual network "xplatvnetExt"
info:    Found public ip parameters, trying to setup PublicIP profile
+ Looking up the public ip "xplatipExt"
info:    PublicIP with given name "xplatipExt" not found, creating a new one
+ Creating public ip "xplatipExt"
+ Looking up the public ip "xplatipExt"
+ Creating NIC "xplatnicExt"
+ Looking up the NIC "xplatnicExt"
+ Creating VM "xplatvmExt"
error:   The subscription is not authorized.
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
error:   vm create command failed
</code>
</pre>

**Comment by anuchandy** [comment]
@sreekanthbs could you share the subscription details over email?

**Comment by babumuralidharan** [comment]
@anuchandy this is the test subscription that we use

**Comment by sreekanthbs** [comment]
ARM VM create with imageUrn MicrosoftWindowsServer:WindowsServer:
2012-Datacenter:3.0.201503 is also failing
<pre>
<code>
C:\Jul2015\Jul-14\azure-xplat-cli-dev>node bin/azure vm create xplatgroup xplatvmExt6 eastus Windows -f xplatnicExt8758 -Q MicrosoftWindowsServer:WindowsServer:
2012-Datacenter:3.0.201503 -u azureuser -p Brillio@2015 -o xplatstoragext9259 -R xplatstoragecntext8332 -F xplatvnetExt1991 -P 10.0.0.0/16 -j xplatsubnetExt9655
 -k 10.0.0.0/24 -i xplatipExt6348 -w xplatdnsext8991
info:    Executing command vm create
+ Looking up the VM "xplatvmExt6"
info:    Using the VM Size "Standard_A1"
info:    The [OS, Data] Disk or image configuration requires storage account
+ Looking up the storage account xplatstoragext9259
info:    Could not find the storage account "xplatstoragext9259", trying to create new one
+ Creating storage account "xplatstoragext9259" in "eastus"
+ Looking up the storage account xplatstoragext9259
+ Looking up the NIC "xplatnicExt8758"
info:    An nic with given name "xplatnicExt8758" not found, creating a new one
+ Looking up the virtual network "xplatvnetExt1991"
info:    Preparing to create new virtual network and subnet
+ Creating a new virtual network "xplatvnetExt1991" [address prefix: "10.0.0.0/16"] with subnet "xplatsubnetExt9655" [address prefix: "10.0.0.0/24"]
+ Looking up the virtual network "xplatvnetExt1991"
+ Looking up the subnet "xplatsubnetExt9655" under the virtual network "xplatvnetExt1991"
info:    Found public ip parameters, trying to setup PublicIP profile
+ Looking up the public ip "xplatipExt6348"
info:    PublicIP with given name "xplatipExt6348" not found, creating a new one
+ Creating public ip "xplatipExt6348"
+ Looking up the public ip "xplatipExt6348"
+ Creating NIC "xplatnicExt8758"
+ Looking up the NIC "xplatnicExt8758"
+ Creating VM "xplatvmExt6"
error:   The subscription is not authorized.
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
error:   vm create command failed
</code>
</pre>

**Comment by ruslangabitov** [comment]
@sreekanthbs looks like these images are not available in your subscription. I had the same error with specified images, but then I ran 'vm image list' commands for both of them:
<code>MicrosoftWindowsServer:WindowsServer:2012-Datacenter:3.0.201503</code>
![image](https://cloud.githubusercontent.com/assets/6327511/9237871/babf5cea-4102-11e5-8759-733bb4167ff0.png)
<code>MicrosoftWindowsServer:WindowsServer:2008-R2-SP1:2.0.201502</code>
![image](https://cloud.githubusercontent.com/assets/6327511/9237876/c1ffd64c-4102-11e5-929d-cdc2cd6a4c8c.png)

As you can see both of them are not in a list of available images.

**Comment by sreekanthbs** [comment]
@ruslangabitov yes those images are no longer available.I tried with the latest available urn & its working fine now.Closing the issues.Thanks
<pre>
<code>
C:\Aug\14Aug\azure-xplat-cli-dev>node bin/azure vm create xplatgroup xplatvmExt6 eastus Windows -f xplatnicExt8758 -Q MicrosoftWindowsServer:WindowsServer:2012-Datace
nter:3.0.201505 -u azureuser -p Brillio@2015 -o xplatstoragext9259 -R xplatstoragecntext8332 -F xplatvnetExt1991 -P 10.0.0.0/16 -j xplatsubnetExt9655 -k 10.0.0.0/24 -
i xplatipExt6348 -w xplatdnsext8991
info:    Executing command vm create
+ Looking up the VM "xplatvmExt6"
info:    Using the VM Size "Standard_A1"
info:    The [OS, Data] Disk or image configuration requires storage account
+ Looking up the storage account xplatstoragext9259
info:    Could not find the storage account "xplatstoragext9259", trying to create new one
+ Creating storage account "xplatstoragext9259" in "eastus"
+ Looking up the storage account xplatstoragext9259
+ Looking up the NIC "xplatnicExt8758"
info:    An nic with given name "xplatnicExt8758" not found, creating a new one
+ Looking up the virtual network "xplatvnetExt1991"
info:    Preparing to create new virtual network and subnet
+ Creating a new virtual network "xplatvnetExt1991" [address prefix: "10.0.0.0/16"] with subnet "xplatsubnetExt9655" [address prefix: "10.0.0.0/24"]
+ Looking up the virtual network "xplatvnetExt1991"
+ Looking up the subnet "xplatsubnetExt9655" under the virtual network "xplatvnetExt1991"
info:    Found public ip parameters, trying to setup PublicIP profile
+ Looking up the public ip "xplatipExt6348"
info:    PublicIP with given name "xplatipExt6348" not found, creating a new one
+ Creating public ip "xplatipExt6348"
+ Looking up the public ip "xplatipExt6348"
+ Creating NIC "xplatnicExt8758"
+ Looking up the NIC "xplatnicExt8758"
+ Creating VM "xplatvmExt6"
info:    vm create command OK
</code>
</pre?
