### ISSUE TITLE
ASM :vm create giving error --ssh required when --ssh-cert or --ssh-password is specified 

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#372]
Asm vm create giving error --ssh required when --ssh-cert or --ssh-password is specified although nothing is specified  related to ssh.
<pre>
<code><b>With Windows Image</b>
C:\June\24june\azure-xplat-cli-dev>node bin/azure vm create DummyVm fb83b3509582419d99629ce476bcb5c8__SQL-Server-2014-RTM-12.0.2361.0-OLTP-ENU-Win2012R2-cy14su08 azur
euser Super@123
info:    Executing command vm create
warn:    --vm-size has not been specified. Defaulting to "Small".
error:   --ssh (SSH port, default to 22) is required when --ssh-cert or --ssh-password is specified
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   vm create command failed

<b>With Linux Image</b>
C:\June\24june\azure-xplat-cli-dev>node bin/azure vm create DummyVm b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_1-LTS-amd64-server-20140909-en-us-30GB azureuser Su
per@123
info:    Executing command vm create
warn:    --vm-size has not been specified. Defaulting to "Small".
error:   --ssh (SSH port, default to 22) is required when --ssh-cert or --ssh-password is specified
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   vm create command failed

</code>
</pre>

**Comment by sreekanthbs** [comment]
The issue is in https://github.com/MSOpenTech/azure-xplat-cli/tree/dev branch

**Comment by roman-boltunov** [comment]
@sreekanthbs we are not working in dev branch for now, all changes comes to dev-asm-network, please test this issue under this branch.

**Comment by HimanshuBri** [comment]
Its working fine now.Hence closing the issue.
