### ISSUE TITLE
ARM: move promptRecordParameters function to DnsRecordSet

### ISSUE THREAD

**Issue by romangromov** [MSOpenTech/azure-xplat-cli#377]
Please place`promptRecordParameters` function from `network._js (line 1739)` inside `DnsRecordSet._js`
Also, there are JSHint issues inside `promptRecordParameters` - please fix as well.
Do not forget to run `ARM-relates` unit tests to make sure all is fine.

**Comment by roman-boltunov** [comment]
@romangromov fixed, could you please confirm that everything works good?

**Comment by romangromov** [comment]
@roman-boltunov everything seems nice, thank you
