### ISSUE TITLE
ASM: 'network vnet subnet create' showing error even after creating the subnet

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#380]
Please find the attached screenshots.
![image](https://cloud.githubusercontent.com/assets/10084788/8376889/b4a81872-1c29-11e5-9552-8984a8828cfe.png)
![image](https://cloud.githubusercontent.com/assets/10084788/8376908/d22e7b8e-1c29-11e5-96eb-9b2f386456f2.png)

**Comment by romangromov** [comment]
@HimanshuBri thank you, please try again - should be fixed from my side

**Comment by HimanshuBri** [comment]
@romangromov. Even when Nsg is not found it is creating the subnet although it is giving error.
Please check the attached screenshot.
![image](https://cloud.githubusercontent.com/assets/10084788/8403205/f1bd14b4-1e5f-11e5-926e-5e8609ea8689.png)

**Comment by MikhailTryakhov** [comment]
Hi @HimanshuBri  thank you for you comments!
Please review code changes - this issue should be fixed now

**Comment by HimanshuBri** [comment]
@MikhailTryakhov. I guess you have not merged the changes in dev-asm-network branch. Could you please confirm.

**Comment by MikhailTryakhov** [comment]
@HimanshuBri I'm terribly sorry, the updates were not merged magically.
Please review updates now

**Comment by HimanshuBri** [comment]
Thanks @MikhailTryakhov. Working as expected now. Closing the issue.
