### ISSUE TITLE
Refactoring:  Reuse `getImageInfo` from `show`

### ISSUE THREAD

**Issue by avranju** [MSOpenTech/azure-xplat-cli#39]
The `show` function implementation in `lib/commands/asm/iaas/image.js` has almost identical code for the case when `what` is not equal to `DISK` when compared with the implementation of `getImageInfo` in `lib/commands/asm/vm/vmUtils.js`. Consider reusing `getImageInfo` from `show` to avoid code duplication.

The two pieces of code are not *exactly* identical because `show` tries to save a copy of the `Error` object as returned by `computeManagementClient.virtualMachineOSImages.get` when the error code is equal to `ResourceNotFound`. When reusing `getImageInfo` we'll need to figure out how to raise the same error from `show`.

**Comment by romangromov** [comment]
Please re-open if we still need this
