### ISSUE TITLE
ASM : vm endpoint acl-rule create not working

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#429]
<pre>
<code>
C:\July\14july\azure-xplat-cli-dev>node bin/azure vm endpoint acl-rule create dndlinuxxlat EndPt1 3 permit 23.99.18.228/31
info:    Executing command vm endpoint acl-rule create
+ Getting virtual machines
+ Reading network configuration
+ Updating network configuration
error:   Existing endpoints in LB set 'lbSet14' do not contain ACL.
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   vm endpoint acl-rule create command failed

C:\July\14july\azure-xplat-cli-dev>node bin/azure vm endpoint list dndlinuxxlat
info:    Executing command vm endpoint list
+ Getting virtual machines
data:    Name            Protocol  Public Port  Private Port  Virtual IP      EnableDirectServerReturn  Load Balanced
data:    --------------  --------  -----------  ------------  --------------  ------------------------  -------------
data:    EndPt1          tcp       23           23            104.209.37.187  false                     Yes
data:    Remote Desktop  tcp       3389         3389          104.209.37.187  false                     No
data:    SSH             tcp       22           22            104.209.37.187  false                     No
info:    vm endpoint list command OK
</code>
</pre>

**Comment by babumuralidharan** [comment]
@sreekanthbs were you able to repro this after trying out azure --gen ? I feel this is a cache issue but good to check though

**Comment by sreekanthbs** [comment]
@babumuralidharan yes its looks like a cache issue only.
Its working fine after running azure --gen. Hence closing the issue.Thanks

**Comment by 8bitbrad** [comment]
I am seeing this same error in the version of the cli:

brad-dev:azure-experiments bradleywhite$ azure config list
info:    Getting config settings
data:    Setting  Value
data:    -------  -----
data:    mode     asm
brad-dev:azure-experiments bradleywhite$ azure --version
0.9.7 (node: 0.10.23)
brad-dev:azure-experiments bradleywhite$ azure vm endpoint acl-rule create lss-hmf01-jump01 ssh --action permit --order 10 --remote-subnet "69.84.207.62/32" --description "BKFD"
info:    Executing command vm endpoint acl-rule create
+ Getting virtual machines
+ Reading network configuration
+ Updating network configuration
error:   Existing endpoints in LB set 'lss-hmf01-ssh' do not contain ACL.
info:    Error information has been recorded to /Users/bradleywhite/.azure/azure.err
error:   vm endpoint acl-rule create command failed

**Comment by sreekanthbs** [comment]
@8bitbrad hi i am not able to repro this issue now.

<pre>
<code>
C:\Aug\14Aug\azure-xplat-cli-dev>node bin/azure vm endpoint acl-rule create cliVM14a endpt1 3 permit 23.99.18.228/31
info:    Executing command vm endpoint acl-rule create
+ Getting virtual machines
+ Reading network configuration
+ Updating network configuration
info:    vm endpoint acl-rule create command OK

C:\>azure vm endpoint acl-rule create cliVM14a endpt1 3 permit 23.99.18.228/31
info:    Executing command vm endpoint acl-rule create
+ Getting virtual machines
+ Reading network configuration
+ Updating network configuration
info:    vm endpoint acl-rule create command OK
</code>
</pre>
