### ISSUE TITLE
ARM: Dogfood 'environment add' issue

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#432]
ARM Dogfood 'environment add' for arm-arm-routes and dev-arm-idns repos has an issue while doing recordings for the ARM test cases.
Please refer below error screen shots, when we run mock recordings for the commands. 
![recordings_error](https://cloud.githubusercontent.com/assets/11171941/8725535/58db013e-2bf2-11e5-956a-7a0d269b911d.png)

Though the commands working fine but for the recording files missed some of the params
Below screen shot for the test case recordings
![recordings_without_activedirectory](https://cloud.githubusercontent.com/assets/11171941/8725581/91a0deda-2bf2-11e5-82c3-5424cbbe9261.PNG)

The error which showing first screen shot <b></i>The endpoint field activeDirectoryResourceId is not defined in this environment</i></b>
is missed in the test case addEnvironment value pair.
As this code is autogenerated, is there any command/ way to get that <b>activeDirectoryResourceId</b> and value to be properly added.

**Comment by DeepakRajendranMsft** [comment]
for endpoint issues, please contact Anu or the xplat SDK team.

RouteTable is now in production. Please send us your production subsciption id and we can enable it.

**Comment by babumuralidharan** [comment]
@sreekanthbs lets check this in production and update the comment here..

**Comment by babumuralidharan** [comment]
@sreekanthbs any update on this ??

**Comment by sreekanthbs** [comment]
@babumuralidharan  It is working in production, so closing the issue.
