### ISSUE TITLE
ARM: network route-table route create not working for next-hop-type - VirtualNetworkGateway & Null

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#433]
<pre>
<code>
C:\July\16july\azure-xplat-cli-dev-arm-routes>node bin/azure network route-table route create armresgrp24j route24j route11 10.0.0.0/23 VirtualNetworkGateway
info:    Executing command network route-table route create
+ Looking up route "route11" in route table "route24j"
+ Creating route "route11" in a route table "route24j"
error:   VirtualNetworkGateway as NextHoptype is currently not supported on a Route (/subscriptions/6dfcf2d3-8682-4606-943d-29b694b4c8c4/resourceGroups/armresgrp24j/p
roviders/Microsoft.Network/routeTables/route24j/routes/route11)
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network route-table route create command failed

C:\July\16july\azure-xplat-cli-dev-arm-routes>node bin/azure network route-table route create armresgrp24j route24j route11 10.0.0.0/23 Null
info:    Executing command network route-table route create
+ Looking up route "route11" in route table "route24j"
+ Creating route "route11" in a route table "route24j"
error:   Cannot parse the request.
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network route-table route create command failed

C:\July\16july\azure-xplat-cli-dev-arm-routes>node bin/azure network route-table route create armresgrp24j route24j route11 10.0.0.0/23 VNETLocal
info:    Executing command network route-table route create
+ Looking up route "route11" in route table "route24j"
+ Creating route "route11" in a route table "route24j"
+ Looking up route "route11" in route table "route24j"
data:    Id                              : /subscriptions/6dfcf2d3-8682-4606-943d-29b694b4c8c4/resourceGroups/armresgrp24j/providers/Microsoft.Network/routeTables/rou
te24j/routes/route11
data:    Name                            : route11
data:    Provisioning state              : Succeeded
data:    Next hop type                   : VnetLocal
data:    Address prefix                  : 10.0.0.0/23
info:    network route-table route create command OK

</code>
</pre>

**Comment by DeepakRajendranMsft** [comment]
VirtualNetworkGateway as NextHoptype is currently not supported on a Route 
 is an expected error. We do not support this presently

node bin/azure network route-table route create armresgrp24j route24j route11 10.0.0.0/23 Null
 Instead of "Null", please try "None"

**Comment by sreekanthbs** [comment]
@DeepakRajendranMsft tried with "None".But still getting the error.
Please have a look at the error
<pre>
<code>
C:\July\21july\azure-xplat-cli-dev-arm-routes>node bin/azure network route-table route create armresgrp24j route24j route11 10.0.0.0/23 "None"
info:    Executing command network route-table route create
error:   Given next hop type is invalid, supported values are VirtualAppliance, VirtualNetworkGateway, VNETLocal, Internet, Null
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network route-table route create command failed


C:\July\21july\azure-xplat-cli-dev-arm-routes>node bin/azure network route-table route create armresgrp24j route24j route11 10.0.0.0/23 None
info:    Executing command network route-table route create
error:   Given next hop type is invalid, supported values are VirtualAppliance, VirtualNetworkGateway, VNETLocal, Internet, Null
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network route-table route create command failed
</code>
</pre>

**Comment by babumuralidharan** [comment]
@DeepakRajendranMsft could you please comment on this ? 

@sreekanthbs  can you try this in production and let me know the behavior ?

**Comment by sreekanthbs** [comment]
@babumuralidharan issue is still there in production

![image](https://cloud.githubusercontent.com/assets/11171941/8845092/49df0760-3139-11e5-8966-47fb1625ced7.png)

**Comment by romangromov** [comment]
@sreekanthbs could you please confirm its `external` and no action required from our side?

**Comment by babumuralidharan** [comment]
@DeepakRajendranMsft does server side support this hoptype ? Do we need to handle anything in the client side for this issue ??

**Comment by romangromov** [comment]
Hi @DeepakRajendranMsft, can you please take a look this thread over? Thank you in advance

**Comment by DeepakRajendranMsft** [comment]
Sorry for my late reply. we just update Prod, None should be working now. Could you please give it a quick try again?

**Comment by sreekanthbs** [comment]
@DeepakRajendranMsft yes VirtualNetworkGateway is working fine now.
But None is still giving error.

![image](https://cloud.githubusercontent.com/assets/11171941/9243850/0998b77a-41b3-11e5-8124-35fca3ec9cf2.png)

**Comment by romangromov** [comment]
Thank you @DeepakRajendranMsft.
Hi @sreekanthbs, this should be fixed on our side, please verify fix in `arm-route-table-fixes` branch.
Also please make a smoke testing for `route-table route create` command for all of `nextHop` types - I'm going to send PR to upstream with fix, thank you in advance

**Comment by sreekanthbs** [comment]
@romangromov @DeepakRajendranMsft  yes its working fine in the specified branch.
I verified with all the nextHop type working fine now.
Closing the issue.Thanks

<pre>
<code>
C:\Aug\13Aug\azure-xplat-cli-arm-route-table-fixes>node bin/azure network route-table route create armresgrp13a routeTbl1 route1 10.0.0.0/23 VirtualNetworkGateway
info:    Executing command network route-table route create
+ Looking up route "route1" in route table "routeTbl1"
+ Creating route "route1" in a route table "routeTbl1"
+ Looking up route "route1" in route table "routeTbl1"
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp13a/providers/Microsoft.Network/routeTables/rou
teTbl1/routes/route1
data:    Name                            : route1
data:    Provisioning state              : Succeeded
data:    Next hop type                   : VirtualNetworkGateway
data:    Address prefix                  : 10.0.0.0/23
info:    network route-table route create command OK
:\Aug\13Aug\azure-xplat-cli-arm-route-table-fixes>node bin/azure network route-table route create armresgrp13a routeTbl1 route1 10.0.0.0/23 VirtualAppliance
nfo:    Executing command network route-table route create
ext hop ip address: 10.0.0.0
 Looking up route "route1" in route table "routeTbl1"
 Creating route "route1" in a route table "routeTbl1"
 Looking up route "route1" in route table "routeTbl1"
ata:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp13a/providers/Microsoft.Network/routeTables/rou
eTbl1/routes/route1
ata:    Name                            : route1
ata:    Provisioning state              : Succeeded
ata:    Next hop type                   : VirtualAppliance
ata:    Next hop IP address             : 10.0.0.0
ata:    Address prefix                  : 10.0.0.0/23
nfo:    network route-table route create command OK
:\Aug\13Aug\azure-xplat-cli-arm-route-table-fixes>node bin/azure network route-table route create armresgrp13a routeTbl1 route1 10.0.0.0/23 VNETLocal
nfo:    Executing command network route-table route create
 Looking up route "route1" in route table "routeTbl1"
 Creating route "route1" in a route table "routeTbl1"
 Looking up route "route1" in route table "routeTbl1"
ata:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp13a/providers/Microsoft.Network/routeTables/rou
eTbl1/routes/route1
ata:    Name                            : route1
ata:    Provisioning state              : Succeeded
ata:    Next hop type                   : VnetLocal
ata:    Address prefix                  : 10.0.0.0/23
nfo:    network route-table route create command OK
:\Aug\13Aug\azure-xplat-cli-arm-route-table-fixes>node bin/azure network route-table route create armresgrp13a routeTbl1 route1 0.0.0.0/0 Internet
nfo:    Executing command network route-table route create
 Looking up route "route1" in route table "routeTbl1"
 Creating route "route1" in a route table "routeTbl1"
 Looking up route "route1" in route table "routeTbl1"
ata:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp13a/providers/Microsoft.Network/routeTables/rou
eTbl1/routes/route1
ata:    Name                            : route1
ata:    Provisioning state              : Succeeded
ata:    Next hop type                   : Internet
ata:    Address prefix                  : 0.0.0.0/0
nfo:    network route-table route create command OK
</code>
</pre>
