### ISSUE TITLE
ARM: network route-table create command fails to create Route table other than Dogfood environment

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#435]
Giving below error 
![route-table-issue](https://cloud.githubusercontent.com/assets/11171941/8748683/da8376fe-2cb9-11e5-9f3a-1562971073dd.PNG)

**Comment by DeepakRajendranMsft** [comment]
Please send me your subscriptionId, we need to enable the routetable feature for your subscription. also, what location are you hitting?

**Comment by babumuralidharan** [comment]
@sreekanthbs hope this is working fine in production now.. Can you comment on this ?

**Comment by sreekanthbs** [comment]
@babumuralidharan yes its working fine in production now.Hence closing the issue
