### ISSUE TITLE
ASM: network vnet subnet create command shows incorrect message creating association with NSG

### ISSUE THREAD

**Issue by MikhailTryakhov** [MSOpenTech/azure-xplat-cli#439]
It contains message 'Creating a network security groups with name "%s" (no creation actually occurred). Please review details below:
![subnet nsg messages](https://cloud.githubusercontent.com/assets/3079588/8794663/421db15e-2f8e-11e5-8d2f-32dc68d87de3.png)

@anuchandy  could you please approve me to assign this issue (let know guys on the other side and mark it as external)

**Comment by babumuralidharan** [comment]
@anuchandy @MikhailTryakhov  I don't think this issue is external. Guess this is something that needs to be fixed in client right ? Could you please tell me why this issue is external?

**Comment by MikhailTryakhov** [comment]
@babumuralidharan you're right! It's internal - I've fixed it
