### ISSUE TITLE
ARM: 'network vnet subnet create ' not working with -r option

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#447]
<b>network vnet subnet create</b> command not working in branch https://github.com/MSOpenTech/azure-xplat-cli/tree/dev-arm-routes2 
Same command is working fine in https://github.com/MSOpenTech/azure-xplat-cli/tree/dev-arm-routes
branch, can you explain the difference between these two branches

<pre>
<code>
C:\July\npm\azure-xplat-cli-dev-arm-routes2>node bin/azure network vnet subnet create armgro22j vnet29 subnet29 -a 10.0.0.0/28 -w /subscriptions/bfb5e0bf-124b-4d0c-93
52-7c0a9f4d9948/resourceGroups/armgro22j/providers/Microsoft.Network/networkSecurityGroups/nsg29 -r routbl
info:    Executing command network vnet subnet create
+ Looking up the subnet "subnet29"
error:   resourceGroup is not defined
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network vnet subnet create command failed

</code>
</pre>

**Comment by sreekanthbs** [comment]
Here is the verbose output
<pre>
<code>
C:\July\npm\azure-xplat-cli-dev-arm-routes2>node bin/azure network vnet subnet create armgro22j vnet29 subnet29 -a 10.0.0.0/28 -w /subscriptions/bfb5e0bf-124b-4d0c-93
52-7c0a9f4d9948/resourceGroups/armgro22j/providers/Microsoft.Network/networkSecurityGroups/nsg29 -r routbl -vv
info:    Executing command network vnet subnet create
verbose: Looking up the subnet "subnet29"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { Content-Type: 'application/json', user-agent: 'WindowsAzureXplatCLI/0.9.6' },
silly:       url: 'https://management.azure.com/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armgro22j/providers/Microsoft.Network/virtualnetwork
s/vnet29/subnets/subnet29?api-version=2015-05-01-preview'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 404,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-length: '231',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           x-ms-request-id: 'e43965ed-ec9b-4b21-943c-8c3b6643901e',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
silly:           x-ms-ratelimit-remaining-subscription-reads: '14978',
silly:           x-ms-correlation-request-id: '569fba75-d797-411d-8193-5d258625facd',
silly:           x-ms-routing-request-id: 'SOUTHEASTASIA:20150722T145525Z:569fba75-d797-411d-8193-5d258625facd',
silly:           date: 'Wed, 22 Jul 2015 14:55:25 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '{\015\n  "error": {\015\n    "code": "NotFound",\015\n    "message": "Resource /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/
armgro22j/providers/Microsoft.Network/virtualNetworks/vnet29/subnets/subnet29 not found."\015\n  }\015\n}'
silly:   }
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { Content-Type: 'application/json', user-agent: 'WindowsAzureXplatCLI/0.9.6' },
silly:       url: 'https://management.azure.com/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armgro22j/providers/Microsoft.Network/virtualnetwork
s/vnet29?api-version=2015-05-01-preview'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-length: '1382',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           etag: 'W/"f5abec2a-da5d-4845-895b-4f277a11a56f"',
silly:           x-ms-request-id: '5421d965-1a6a-4491-aee7-41bee0b4229f',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
silly:           x-ms-ratelimit-remaining-subscription-reads: '14977',
silly:           x-ms-correlation-request-id: '14d9738c-bb12-4d15-89fb-d322e50242a4',
silly:           x-ms-routing-request-id: 'SOUTHEASTASIA:20150722T145526Z:14d9738c-bb12-4d15-89fb-d322e50242a4',
silly:           date: 'Wed, 22 Jul 2015 14:55:26 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '{\015\n  "name": "vnet29",\015\n  "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armgro22j/providers/Microsoft.Network/
virtualNetworks/vnet29",\015\n  "etag": "W/\\"f5abec2a-da5d-4845-895b-4f277a11a56f\\"",\015\n  "properties": {\015\n    "provisioningState": "Succeeded",\015\n    "re
sourceGuid": "820231f9-8cef-4933-a4ce-e332519559cb",\015\n    "addressSpace": {\015\n      "addressPrefixes": [\015\n        "10.0.0.0/24",\015\n        "10.0.1.0/24"
\015\n      ]\015\n    },\015\n    "dhcpOptions": {\015\n      "dnsServers": [\015\n        "10.0.0.0"\015\n      ]\015\n    },\015\n    "subnets": [\015\n      {\015
\n        "name": "subnet291",\015\n        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armgro22j/providers/Microsoft.Network/virtualNet
works/vnet29/subnets/subnet291",\015\n        "etag": "W/\\"f5abec2a-da5d-4845-895b-4f277a11a56f\\"",\015\n        "properties": {\015\n          "provisioningState":
 "Succeeded",\015\n          "addressPrefix": "10.0.0.0/28",\015\n          "networkSecurityGroup": {\015\n            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7
c0a9f4d9948/resourceGroups/armgro22j/providers/Microsoft.Network/networkSecurityGroups/nsg29"\015\n          },\015\n          "routeTable": {\015\n            "id":
"/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armgro22j/providers/Microsoft.Network/routeTables/routbl"\015\n          }\015\n        }\015\n
   }\015\n    ]\015\n  },\015\n  "location": "eastus"\015\n}'
silly:   }
error:   resourceGroup is not defined
silly:   {
silly:       stack: 'ReferenceError: resourceGroup is not defined\n    at __$_parseSubnet__7 (C:\\July\\npm\\azure-xplat-cli-dev-arm-routes2\\lib\\commands\\arm\\netw
ork\\subnet._js:444:50)\n    at __$_parseSubnet__7 (C:\\July\\npm\\azure-xplat-cli-dev-arm-routes2\\lib\\commands\\arm\\network\\subnet._js:460:17)\n    at __$_parseS
ubnet__7 (C:\\July\\npm\\azure-xplat-cli-dev-arm-routes2\\lib\\commands\\arm\\network\\subnet._js:463:13)\n    at __$_parseSubnet__7 (C:\\July\\npm\\azure-xplat-cli-d
ev-arm-routes2\\lib\\commands\\arm\\network\\subnet._js:394:13)\n    at ___ (C:\\July\\npm\\azure-xplat-cli-dev-arm-routes2\\lib\\commands\\arm\\network\\subnet._js:4
22:11)\n    at ___ (C:\\July\\npm\\azure-xplat-cli-dev-arm-routes2\\node_modules\\streamline\\lib\\callbacks\\runtime.js:111:13)\n    at C:\\July\\npm\\azure-xplat-cl
i-dev-arm-routes2\\node_modules\\azure-arm-network\\lib\\networkResourceProviderClient.js:23698:14\n    at C:\\July\\npm\\azure-xplat-cli-dev-arm-routes2\\lib\\util\\
utils.js:343:7\n    at handleRedirect (C:\\July\\npm\\azure-xplat-cli-dev-arm-routes2\\lib\\util\\utils.js:320:9)\n    at C:\\July\\npm\\azure-xplat-cli-dev-arm-route
s2\\lib\\util\\logging.js:281:7\n',
silly:       message: 'resourceGroup is not defined',
silly:       __frame: {
silly:           name: '_parseSubnet__7',
silly:           line: 162,
silly:           file: 'C:\\July\\npm\\azure-xplat-cli-dev-arm-routes2\\lib\\commands\\arm\\network\\subnet._js',
silly:           prev: {
silly:               name: 'create__1',
silly:               line: 36,
silly:               file: 'C:\\July\\npm\\azure-xplat-cli-dev-arm-routes2\\lib\\commands\\arm\\network\\subnet._js',
silly:               prev: {
silly:                   name: '__6',
silly:                   line: 155,
silly:                   file: 'C:\\July\\npm\\azure-xplat-cli-dev-arm-routes2\\lib\\commands\\arm\\network\\network._js',
silly:                   prev: undefined,
silly:                   calls: 4,
silly:                   active: false,
silly:                   offset: 7,
silly:                   col: 13
silly:               },
silly:               calls: 2,
silly:               active: false,
silly:               offset: 8,
silly:               col: 29
silly:           },
silly:           calls: 0,
silly:           active: true,
silly:           offset: 3,
silly:           col: 66
silly:       },
silly:       rawStack: 'ReferenceError: resourceGroup is not defined\n    at __$_parseSubnet__7 (C:\\July\\npm\\azure-xplat-cli-dev-arm-routes2\\lib\\commands\\arm\\n
etwork\\subnet._js:444:50)\n    at __$_parseSubnet__7 (C:\\July\\npm\\azure-xplat-cli-dev-arm-routes2\\lib\\commands\\arm\\network\\subnet._js:460:17)\n    at __$_par
seSubnet__7 (C:\\July\\npm\\azure-xplat-cli-dev-arm-routes2\\lib\\commands\\arm\\network\\subnet._js:463:13)\n    at __$_parseSubnet__7 (C:\\July\\npm\\azure-xplat-cl
i-dev-arm-routes2\\lib\\commands\\arm\\network\\subnet._js:394:13)\n    at ___ (C:\\July\\npm\\azure-xplat-cli-dev-arm-routes2\\lib\\commands\\arm\\network\\subnet._j
s:422:11)\n    at ___ (C:\\July\\npm\\azure-xplat-cli-dev-arm-routes2\\node_modules\\streamline\\lib\\callbacks\\runtime.js:111:13)\n    at C:\\July\\npm\\azure-xplat
-cli-dev-arm-routes2\\node_modules\\azure-arm-network\\lib\\networkResourceProviderClient.js:23698:14\n    at C:\\July\\npm\\azure-xplat-cli-dev-arm-routes2\\lib\\uti
l\\utils.js:343:7\n    at handleRedirect (C:\\July\\npm\\azure-xplat-cli-dev-arm-routes2\\lib\\util\\utils.js:320:9)\n    at C:\\July\\npm\\azure-xplat-cli-dev-arm-ro
utes2\\lib\\util\\logging.js:281:7\n'
silly:   }
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
verbose: ReferenceError: resourceGroup is not defined
    at __$_parseSubnet__7 (C:\July\npm\azure-xplat-cli-dev-arm-routes2\lib\commands\arm\network\subnet._js:444:50)
    at __$_parseSubnet__7 (C:\July\npm\azure-xplat-cli-dev-arm-routes2\lib\commands\arm\network\subnet._js:460:17)
    at __$_parseSubnet__7 (C:\July\npm\azure-xplat-cli-dev-arm-routes2\lib\commands\arm\network\subnet._js:463:13)
    at __$_parseSubnet__7 (C:\July\npm\azure-xplat-cli-dev-arm-routes2\lib\commands\arm\network\subnet._js:394:13)
    at ___ (C:\July\npm\azure-xplat-cli-dev-arm-routes2\lib\commands\arm\network\subnet._js:422:11)
    at ___ (C:\July\npm\azure-xplat-cli-dev-arm-routes2\node_modules\streamline\lib\callbacks\runtime.js:111:13)
    at C:\July\npm\azure-xplat-cli-dev-arm-routes2\node_modules\azure-arm-network\lib\networkResourceProviderClient.js:23698:14
    at C:\July\npm\azure-xplat-cli-dev-arm-routes2\lib\util\utils.js:343:7
    at handleRedirect (C:\July\npm\azure-xplat-cli-dev-arm-routes2\lib\util\utils.js:320:9)
    at C:\July\npm\azure-xplat-cli-dev-arm-routes2\lib\util\logging.js:281:7

error:   network vnet subnet create command failed

</code>
</pre>

**Comment by babumuralidharan** [comment]
@ruslangabitov can you please comment on this ??

**Comment by anuchandy** [comment]
https://github.com/MSOpenTech/azure-xplat-cli/tree/dev-arm-routes2  uses latest network SDK from npm repository

and  https://github.com/MSOpenTech/azure-xplat-cli/tree/dev-arm-routes uses older version of network SDK which is stored under armsdk folder.

**Comment by ruslangabitov** [comment]
@babumuralidharan @anuchandy I found the issue, its a merge conflict issue, I'll fix it tomorrow morning.

**Comment by ruslangabitov** [comment]
Fixed here: https://github.com/MSOpenTech/azure-xplat-cli/pull/453

**Comment by ruslangabitov** [comment]
@sreekanthbs Anu described one difference and another one is that <code>dev-arm-routes2</code> is synced with Azure dev branch.
Code in <code>dev-arm-routes</code> was pretty old and outdated, therefore it had a lot of merge conflicts. It is more stable in testing routes feature though.

**Comment by sreekanthbs** [comment]
@ruslangabitov  yes its working fine now.Hence closing the issue.
![image](https://cloud.githubusercontent.com/assets/11171941/8869455/7648e3fc-3201-11e5-81c1-576a0293d805.png)
