### ISSUE TITLE
ARM: network vnet subnet create not working with -o option for network-security-group-name

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#457]
![image](https://cloud.githubusercontent.com/assets/11171941/8871727/1b6ca4f0-3215-11e5-971a-74ba53c284ce.png)

**Comment by sreekanthbs** [comment]
network vnet subnet create is working with -w option i.e network-security-group-id
But giving error with -o option i.e network-security-group-name

![image](https://cloud.githubusercontent.com/assets/11171941/8871938/bdaf3d4e-3216-11e5-9467-db88767e4c78.png)

**Comment by sreekanthbs** [comment]
Same issue with network vnet subnet set 
![image](https://cloud.githubusercontent.com/assets/11171941/8871976/0328ec26-3217-11e5-9778-cb66c7aa7e9e.png)

**Comment by romangromov** [comment]
Hi @sreekanthbs, please make sure all is fine now

**Comment by sreekanthbs** [comment]
@romangromov  yes its working fine now.Thanks.Closing the issue

![image](https://cloud.githubusercontent.com/assets/11171941/8901217/b8ad793c-3464-11e5-97e5-e420ec7be290.png)
