### ISSUE TITLE
ARM: network vnet subnet set not working for -r option

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#458]
I created a subnet using -r routetbl1
![image](https://cloud.githubusercontent.com/assets/11171941/8872112/f5c2ceac-3217-11e5-97cd-b70f23f69b82.png)Trying to set using -r route-tabl2 -- Getting error
![image](https://cloud.githubusercontent.com/assets/11171941/8872087/cdf3167a-3217-11e5-86d5-43acc587ca96.png)

**Comment by romangromov** [comment]
Hi @sreekanthbs, please make sure all is fine now

**Comment by sreekanthbs** [comment]
@romangromov yes its working fine now.Thanks.Closing the issue
![image](https://cloud.githubusercontent.com/assets/11171941/8901227/df25cb00-3464-11e5-8b51-2bc5288f5487.png)
