### ISSUE TITLE
ARM:network nic address-pool add not working with -a option

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#464]
Its working with address-pool id but not with address-pool name param
![image](https://cloud.githubusercontent.com/assets/11171941/8957056/35ef44e2-3619-11e5-83d4-e9705b5d24a9.png)

**Comment by romangromov** [comment]
@sreekanthbs thanks, this shold be fixed now, please use `dev-arm-nic-fixes` branch

**Comment by sreekanthbs** [comment]
@romangromov  yes its working fine now.Thanks.Closing the issue
<pre>
<code>
C:\Aug\11Aug\azure-xplat-cli-dev-arm-nic-fixes>node bin/azure  network nic address-pool add armresgrp11a nic29 -l lb29 -a lbadd29
info:    Executing command network nic address-pool add
+ Looking up the network interface "nic29"
+ Looking up the load balancer "lb29"
+ Updating network interface "nic29"
info:    network nic address-pool add command OK
</code>
</pre>
