### ISSUE TITLE
ARM:network nic inbound-nat-rule add not working with -r option

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#465]
Its working with inbound-nat-rule id option but not with inbound-nat-rule name param
![image](https://cloud.githubusercontent.com/assets/11171941/8957100/9cf77df8-3619-11e5-87a9-2aadc25cd5f7.png)

**Comment by romangromov** [comment]
@sreekanthbs thanks, this shold be fixed now, please use `dev-arm-nic-fixes` branch

**Comment by sreekanthbs** [comment]
@romangromov yes its working fine now.Thanks.Closing the issue
<pre>
<code>
C:\Aug\11Aug\azure-xplat-cli-dev-arm-nic-fixes>node bin/azure  network nic inbound-nat-rule add armresgrp11a nic29 -l lb29 -r lbinbound29
info:    Executing command network nic inbound-nat-rule add
+ Looking up the network interface "nic29"
+ Looking up the load balancer "lb29"
+ Updating network interface "nic29"
info:    network nic inbound-nat-rule add command OK
</code>
</pre>
