### ISSUE TITLE
ARM:network vpn-gateway delete not working

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#473]
![armvpndelete1](https://cloud.githubusercontent.com/assets/11171941/9194898/43bf03e6-403c-11e5-80c1-64e6af535525.PNG)

**Comment by sreekanthbs** [comment]
Here is the verbose output 
C:\Aug\10Aug\azure-xplat-cli-dev-arm-vpn-gateways>node bin/azure network vpn-gateway delete armresgrpVPN vpn1 -q -vv
info:    Executing command network vpn-gateway delete
verbose: Looking up virtual network gateway "vpn1"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { Content-Type: 'application/json', user-agent: 'WindowsAzureXplatCLI/0.9.6' },
silly:       url: 'https://management.azure.com/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrpVPN/providers/Microsoft.Network/virtualNetw
orkGateways/vpn1?api-version=2015-05-01-preview'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-length: '1371',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           etag: 'W/"228a1fac-9e68-49f9-bb27-6f3d5eb9705d"',
silly:           x-ms-request-id: '701a1e87-50e4-4b8d-b8ee-f3e8fc29cb13',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
silly:           x-ms-ratelimit-remaining-subscription-reads: '14999',
silly:           x-ms-correlation-request-id: '27ff9de5-74aa-4875-ba16-0007eede6065',
silly:           x-ms-routing-request-id: 'EASTASIA:20150811T094029Z:27ff9de5-74aa-4875-ba16-0007eede6065',
silly:           date: 'Tue, 11 Aug 2015 09:40:29 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '{\015\n  "name": "vpn1",\015\n  "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrpVPN/providers/Microsoft.Network
/virtualNetworkGateways/vpn1",\015\n  "etag": "W/\\"228a1fac-9e68-49f9-bb27-6f3d5eb9705d\\"",\015\n  "properties": {\015\n    "provisioningState": "Succeeded",\015\n
   "resourceGuid": "61504949-ea3b-4d6a-a008-51c172934140",\015\n    "ipConfigurations": [\015\n      {\015\n        "name": "ip-config",\015\n        "id": "/subscrip
tions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrpVPN/providers/Microsoft.Network/virtualNetworkGateways/vpn1/ipConfigurations/ip-config",\015\n
   "etag": "W/\\"228a1fac-9e68-49f9-bb27-6f3d5eb9705d\\"",\015\n        "properties": {\015\n          "provisioningState": "Succeeded",\015\n          "privateIPAddr
ess": "10.0.0.11",\015\n          "privateIPAllocationMethod": "Static",\015\n          "publicIPAddress": {\015\n            "id": "/subscriptions/bfb5e0bf-124b-4d0c
-9352-7c0a9f4d9948/resourceGroups/armresgrpVPN/providers/Microsoft.Network/publicIPAddresses/publicip1"\015\n          },\015\n          "subnet": {\015\n
"id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrpVPN/providers/Microsoft.Network/virtualNetworks/vnet1/subnets/GatewaySubnet"\015\n
         }\015\n        }\015\n      }\015\n    ],\015\n    "gatewayType": "Vpn",\015\n    "vpnType": "RouteBased",\015\n    "enableBgp": true\015\n  },\015\n  "locat
ion": "eastus"\015\n}'
silly:   }
verbose: Deleting virtual network gateway "vpn1"
error:   undefined is not a function
silly:   {
silly:       stack: 'TypeError: undefined is not a function\n    at __$delete__4 (C:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-vpn-gateways\\lib\\commands\\arm\\network\\v
pnGateway._js:211:90)\n    at __tryCatch (C:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-vpn-gateways\\node_modules\\streamline\\lib\\callbacks\\runtime.js:150:4)\n    at __
_ (C:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-vpn-gateways\\lib\\commands\\arm\\network\\vpnGateway._js:210:17)\n    at ___ (C:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-vpn-
gateways\\lib\\commands\\arm\\network\\vpnGateway._js:215:17)\n    at __$delete__4 (C:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-vpn-gateways\\lib\\commands\\arm\\network\
\vpnGateway._js:231:15)\n    at __$delete__4 (C:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-vpn-gateways\\lib\\commands\\arm\\network\\vpnGateway._js:203:15)\n    at ___ (C
:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-vpn-gateways\\lib\\commands\\arm\\network\\vpnGateway._js:206:13)\n    at ___ (C:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-vpn-gate
ways\\node_modules\\streamline\\lib\\callbacks\\runtime.js:111:13)\n    at C:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-vpn-gateways\\node_modules\\streamline\\lib\\callba
cks\\runtime.js:99:14\n    at Object.__g.trampoline.flush (C:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-vpn-gateways\\node_modules\\streamline\\lib\\callbacks\\runtime.js:
24:29)\n',
silly:       message: 'undefined is not a function',
silly:       __frame: {
silly:           name: '__91',
silly:           line: 1961,
silly:           file: 'C:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-vpn-gateways\\lib\\commands\\arm\\network\\network._js',
silly:           prev: undefined,
silly:           calls: 3,
silly:           active: false,
silly:           offset: 6,
silly:           col: 17
silly:       },
silly:       rawStack: 'TypeError: undefined is not a function\n    at __$delete__4 (C:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-vpn-gateways\\lib\\commands\\arm\\network
\\vpnGateway._js:211:90)\n    at __tryCatch (C:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-vpn-gateways\\node_modules\\streamline\\lib\\callbacks\\runtime.js:150:4)\n    at
 ___ (C:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-vpn-gateways\\lib\\commands\\arm\\network\\vpnGateway._js:210:17)\n    at ___ (C:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-v
pn-gateways\\lib\\commands\\arm\\network\\vpnGateway._js:215:17)\n    at __$delete__4 (C:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-vpn-gateways\\lib\\commands\\arm\\netwo
rk\\vpnGateway._js:231:15)\n    at __$delete__4 (C:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-vpn-gateways\\lib\\commands\\arm\\network\\vpnGateway._js:203:15)\n    at ___
 (C:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-vpn-gateways\\lib\\commands\\arm\\network\\vpnGateway._js:206:13)\n    at ___ (C:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-vpn-g
ateways\\node_modules\\streamline\\lib\\callbacks\\runtime.js:111:13)\n    at C:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-vpn-gateways\\node_modules\\streamline\\lib\\cal
lbacks\\runtime.js:99:14\n    at Object.__g.trampoline.flush (C:\\Aug\\10Aug\\azure-xplat-cli-dev-arm-vpn-gateways\\node_modules\\streamline\\lib\\callbacks\\runtime.
js:24:29)\n'
silly:   }
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
verbose: TypeError: undefined is not a function
    at __$delete__4 (C:\Aug\10Aug\azure-xplat-cli-dev-arm-vpn-gateways\lib\commands\arm\network\vpnGateway._js:211:90)
    at __tryCatch (C:\Aug\10Aug\azure-xplat-cli-dev-arm-vpn-gateways\node_modules\streamline\lib\callbacks\runtime.js:150:4)
    at ___ (C:\Aug\10Aug\azure-xplat-cli-dev-arm-vpn-gateways\lib\commands\arm\network\vpnGateway._js:210:17)
    at ___ (C:\Aug\10Aug\azure-xplat-cli-dev-arm-vpn-gateways\lib\commands\arm\network\vpnGateway._js:215:17)
    at __$delete__4 (C:\Aug\10Aug\azure-xplat-cli-dev-arm-vpn-gateways\lib\commands\arm\network\vpnGateway._js:231:15)
    at __$delete__4 (C:\Aug\10Aug\azure-xplat-cli-dev-arm-vpn-gateways\lib\commands\arm\network\vpnGateway._js:203:15)
    at ___ (C:\Aug\10Aug\azure-xplat-cli-dev-arm-vpn-gateways\lib\commands\arm\network\vpnGateway._js:206:13)
    at ___ (C:\Aug\10Aug\azure-xplat-cli-dev-arm-vpn-gateways\node_modules\streamline\lib\callbacks\runtime.js:111:13)
    at C:\Aug\10Aug\azure-xplat-cli-dev-arm-vpn-gateways\node_modules\streamline\lib\callbacks\runtime.js:99:14
    at Object.__g.trampoline.flush (C:\Aug\10Aug\azure-xplat-cli-dev-arm-vpn-gateways\node_modules\streamline\lib\callbacks\runtime.js:24:29)

error:   network vpn-gateway delete command failed

**Comment by romangromov** [comment]
@sreekanthbs thanks, this should be fixed now, use `dev-arm-vpn-gateways` branch of cource

**Comment by sreekanthbs** [comment]
@romangromov  yes its working fine now.Thanks.
Hence closing the issue.
