### ISSUE TITLE
ARM: network vpn-gateway add ip-config is not yet supported

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#478]
![image](https://cloud.githubusercontent.com/assets/11171941/9222267/f5ed40d8-410d-11e5-8140-c521b676e0c5.png)

**Comment by romangromov** [comment]
@sreekanthbs I'm waiting feedback about multiple VIPs for vpn-gateway, but looks like it's not supported by server, will post update on this thread

**Comment by romangromov** [comment]
@sreekanthbs update from Networking team:

```3 [Roman].	Do you support multiple ipConfigurations for VirtualNetworkGateway right now? When I try to add another one VIP for existing gateway I’m receiving two king of server errors, please see full http logs here (PUT) and here (POST)

[Amit] No only one ipconfiguration is allowed.
```

hence it's external

**Comment by sreekanthbs** [comment]
@romangromov  thanks for the update
