### ISSUE TITLE
ASM: cannot able to run more than 1 network command at a time

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#480]
ASM network commands fails when we try to create more than one network commands at same time

![image](https://cloud.githubusercontent.com/assets/11171941/9243514/228f8758-41af-11e5-9017-652229d6d578.png)
At a time only one command will pass, other will fail with error <b> An update to your network configuration is currently underway. Please try this operation again later.</b>
![image](https://cloud.githubusercontent.com/assets/11171941/9243526/44d37b3a-41af-11e5-91c3-37d86ae97e09.png)

**Comment by romangromov** [comment]
Hi @anuchandy, looks like this is an expected behavior, could you please confirm?
