### ISSUE TITLE
ASM: network application-gateway create is timedout every time

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#482]
ASM network application-gateway create command is timedout everytime.

![image](https://cloud.githubusercontent.com/assets/11171941/9250922/0b735b78-41ee-11e5-8c1d-42c42812b6e1.png)

The app gateway is showing as 'creating' state in the list
![image](https://cloud.githubusercontent.com/assets/11171941/9250983/5c035642-41ee-11e5-9f0b-3c1eeceb0948.png)

**Comment by romangromov** [comment]
@sreekanthbs should be fixed now, please checkout `asm-network-fixes` branch

**Comment by sreekanthbs** [comment]
@romangromov  It is working fine now.
![image](https://cloud.githubusercontent.com/assets/11171941/9355798/d0fb2dc6-4699-11e5-99bf-b4e728f32b92.png)

**Comment by romangromov** [comment]
@sreekanthbs nice to hear, thank you, can we close this issue?

**Comment by sreekanthbs** [comment]
Closing the issue
