### ISSUE TITLE
ARM: `route-table show` not output required fields

### ISSUE THREAD

**Issue by romangromov** [MSOpenTech/azure-xplat-cli#484]
From Deepak Rajendran <derajen@exchange.microsoft.com>:

`I was trying out the route table cmdlets in xplat cli and saw some very issues.
The issues are mostly around show. We don’t seem to have updated the output for quite a while now. The new properties (rather the properties that were added after the first release) aren’t present. Could you please take a look at all resource properties and ensure that we show everything to the user?`

**1.**
C:\windows\system32>azure network route-table route create
info:    Executing command network route-table route create
Resource group name: testrbac1
Route Table name: rt1
Route name: route1
Address prefix: 10.0.0.0/8
Next hop type: VirtualAppliance
Next hop ip address:
+ Looking up route "route1" in route table "rt1"
+ Creating route "route1" in a route table "rt1"
error:   NextHopIpAddress cannot be Null or Empty in route route1 when NextHopTy
pe is .
info:    Error information has been recorded to C:\Users\derajen\.azure\azure.er
r
error:   network route-table route create command failed

The error is missing the next hoptype value

**2.** 
I don’t get prompted when for next hop IPaddress when then next hop type is virualAppliance (“v” is in small case). We should be case – insensitive here

C:\windows\system32>azure network route-table route create
info:    Executing command network route-table route create
Resource group name: testrbac1
Route Table name: rt1
Route name: route1
Address prefix: 10.0.0.0/8
Next hop type: virtualAppliance
+ Looking up route "route1" in route table "rt1"
+ Creating route "route1" in a route table "rt1"
error:   NextHopIpAddress cannot be Null or Empty in route route1 when NextHopTy
pe is .
info:    Error information has been recorded to C:\Users\derajen\.azure\azure.er
r
error:   network route-table route create command failed

**3.** 

After setting the route table to the subnet, the get methods don’t show all the details. In the example below, I am not able to see the route table that was set to the subnet.

C:\windows\system32>azure network vnet subnet set -g testrbac1 -e multivip -n su
bnet -r rt1
info:    Executing command network vnet subnet set
+ Looking up the subnet "subnet"
+ Looking up route table "rt1"
+ Setting subnet "subnet"
+ Looking up the subnet "subnet"
data:    Id                              : /subscriptions/9532a63e-f2eb-4649-bb2
3-5ed01077ce80/resourceGroups/testrbac1/providers/Microsoft.Network/virtualNetwo
rks/multivip/subnets/subnet
data:    Type                            : Microsoft.Network/virtualNetworks/sub
nets
data:    ProvisioningState               : Succeeded
data:    Name                            : subnet
data:    Address prefix                  : 10.0.0.0/11
data:
info:    network vnet subnet set command OK

C:\windows\system32>azure network vnet subnet show -g testrbac1 -e multivip -n s
ubnet
info:    Executing command network vnet subnet show
+ Looking up the subnet "subnet"
data:    Id                              : /subscriptions/9532a63e-f2eb-4649-bb2
3-5ed01077ce80/resourceGroups/testrbac1/providers/Microsoft.Network/virtualNetwo
rks/multivip/subnets/subnet
data:    Type                            : Microsoft.Network/virtualNetworks/sub
nets
data:    ProvisioningState               : Succeeded
data:    Name                            : subnet
data:    Address prefix                  : 10.0.0.0/11
data:
info:    network vnet subnet show command OK

C:\windows\system32>azure network vnet show -g testrbac1 -n multivip
info:    Executing command network vnet show
+ Looking up virtual network "multivip"
data:    Id                              : /subscriptions/9532a63e-f2eb-4649-bb2
3-5ed01077ce80/resourceGroups/testrbac1/providers/Microsoft.Network/virtualNetwo
rks/multivip
data:    Name                            : multivip
data:    Type                            : Microsoft.Network/virtualNetworks
data:    Location                        : westeurope
data:    ProvisioningState               : Succeeded
data:    Address prefixes:
data:      10.0.0.0/8
data:    Subnets:
data:      Name                          : subnet
data:      Address prefix                : 10.0.0.0/11
data:
info:    network vnet show command OK

I see the data only when I get json value (not even under verbose option.)

I understand a lot of new properties have been added. Could we please check that all the properties are displayed under “show” and “list” command for other network resources?

**4.**
Similar to #3, I don’t see the subnet reference in route table after the route table was added to the subnet

C:\windows\system32>azure network route-table show -g testrbac1 -n rt1
info:    Executing command network route-table show
+ Looking up route table "rt1"
data:    Id                              : /subscriptions/9532a63e-f2eb-4649-bb2
3-5ed01077ce80/resourceGroups/testrbac1/providers/Microsoft.Network/routeTables/
rt1
data:    Name                            : rt1
data:    Type                            : Microsoft.Network/routeTables
data:    Location                        : westeurope
data:    Provisioning state              : Succeeded
data:    Routes:
data:      Name                          : route1
data:      Address prefix                : 11.0.0.0/8
data:      Next hop type                 : VnetLocal
data:
info:    network route-table show command OK

In general, all resources should display everything that is transmitted over the write. I have attached the latest network spec. please make sure that you can display all properties for all resources

**5.**
Similar to #3 and #4 in nic , I don find the “enableipforwarding” property that is send over the wire.

C:\windows\system32>azure network nic show -g testrbac1 -n nic1
info:    Executing command network nic show
+ Looking up the network interface "nic1"
data:    Id                              : /subscriptions/9532a63e-f2eb-4649-bb2
3-5ed01077ce80/resourceGroups/testrbac1/providers/Microsoft.Network/networkInter
faces/nic1
data:    Name                            : nic1
data:    Type                            : Microsoft.Network/networkInterfaces
data:    Location                        : westeurope
data:    Provisioning state              : Succeeded
data:    Enable IP forwarding            : true
data:    IP configurations:
data:      Name                          : NIC-config
data:      Provisioning state            : Succeeded
data:      Private IP address            : 10.0.0.4
data:      Private IP Allocation Method  : Dynamic
data:      Subnet                        : /subscriptions/9532a63e-f2eb-4649-bb2
3-5ed01077ce80/resourceGroups/testrbac1/providers/Microsoft.Network/virtualNetwo
rks/multivip/subnets/subnet
data:
info:    network nic show command OK

C:\windows\system32>azure network nic show -g testrbac1 -n nic1 --json
{
  "ipConfigurations": [
    {
      "loadBalancerBackendAddressPools": [],
      "loadBalancerInboundNatRules": [],
      "privateIpAddress": "10.0.0.4",
      "privateIpAllocationMethod": "Dynamic",
      "subnet": {
        "id": "/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroup
s/testrbac1/providers/Microsoft.Network/virtualNetworks/multivip/subnets/subnet"

      },
      "provisioningState": "Succeeded",
      "name": "NIC-config",
      "etag": "W/\"a6bd093d-23e2-474a-923f-da9d7d54143c\"",
      "id": "/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/
testrbac1/providers/Microsoft.Network/networkInterfaces/nic1/ipConfigurations/NI
C-config"
    }
  ],
  "tags": {},
  "dnsSettings": {
    "appliedDnsServers": [],
    "dnsServers": []
  },
  "enableIPForwarding": true,
  "provisioningState": "Succeeded",
  "etag": "W/\"a6bd093d-23e2-474a-923f-da9d7d54143c\"",
  "id": "/subscriptions/9532a63e-f2eb-4649-bb23-5ed01077ce80/resourceGroups/test
rbac1/providers/Microsoft.Network/networkInterfaces/nic1",
  "name": "nic1",
  "location": "westeurope"
}

Thanks,
Deepak.

**Comment by romangromov** [comment]
Hi @sreekanthbs, please make sure we are good with all changes requested by @DeepakRajendranMsft, use `arm-route-table-fixes` branch.

Since we are good I will send PR to upstream, thanks

**Comment by sreekanthbs** [comment]
@romangromov  
1.The error is missing the next hoptype value 
I am still getting this error
![image](https://cloud.githubusercontent.com/assets/11171941/9330332/4ec9021a-45d6-11e5-9bf0-548a6d35f7fc.png)
2.I don’t get prompted when for next hop IPaddress when then next hop type is virualAppliance (“v” is in small case). We should be case – insensitive here
Yes its fixed & working fine
![image](https://cloud.githubusercontent.com/assets/11171941/9330351/6b91d2be-45d6-11e5-8297-2fd0138d3db5.png)
3. not able to see the route table that was set to the subnet.
Yes its working fine now.
![image](https://cloud.githubusercontent.com/assets/11171941/9330393/bf30df28-45d6-11e5-8632-5bd99256fcfe.png)
4.don’t see the subnet reference in route table after the route table was added to the subnet
Yes its working fine now now
![image](https://cloud.githubusercontent.com/assets/11171941/9330417/df36fe38-45d6-11e5-9239-160dd16a9460.png)

5.don find the “enableipforwarding” property that is send over the wire
Yes its working fine now
![image](https://cloud.githubusercontent.com/assets/11171941/9330426/f1fe5cdc-45d6-11e5-8202-b248e1be92c3.png)

**Comment by romangromov** [comment]
@sreekanthbs as for **1**: this is because you are provided an empty string for `Next hop ip address`. We do not validate and empty string case everywhere, so this is by design.

If we need to throw some error for an empty case here please let me know - will add such a validation for `ip address`

**Comment by babumuralidharan** [comment]
@sreekanthbs I guess the current way of showing the error and eventually failing the command makes sense confining with the current design. 
@romangromov, we should be good here. But we need to show the nexthoptype value that user typed in here..

For e.g:  In the error message we miss to print the value of NextHopType given in the command by the user 
NextHopIpAddress cannot be Null or Empty in route route 2 when NextHopType is ___virtualAppliance___. Here virtualAppliance value is missing. Could you please correct this and we should be good here.

**Comment by romangromov** [comment]
@babumuralidharan ok, will fix

**Comment by romangromov** [comment]
@sreekanthbs now fixed error message, please verify and let me know, thank you

**Comment by romangromov** [comment]
@sreekanthbs

now fixed error message, please verify and let me know, thank you

**Comment by sreekanthbs** [comment]
@romangromov yes the error message is showing the nexthoptype value
![image](https://cloud.githubusercontent.com/assets/11171941/9357946/3e57df88-46a7-11e5-9439-841d4199d7ec.png)

**Comment by romangromov** [comment]
@sreekanthbs thank you, will send PR to upstream.

@babumuralidharan let's keep it open until merged to upstream, will share update

**Comment by romangromov** [comment]
@babumuralidharan merged, hence closing the issue
