### ISSUE TITLE
ARM:network gateway vnet delete not working 

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#486]
![image](https://cloud.githubusercontent.com/assets/11171941/9355137/d60921ca-4693-11e5-8137-9f7796ec83f9.png)

**Comment by romangromov** [comment]
@sreekanthbs well, this issue happens from time to time. Try to remove gateway again, and it will be removed a few minutes later. Anyway, will report this issue to Gateway Team.

**Comment by romangromov** [comment]
@sreekanthbs update from Network team:

```
[Roman]: The Delete method do not deletes VirtualNetworkGateway immediately. After call delete method the VirtualNetworkGateway still exists with provisioning state “Deleting” and it will be deleted automatically by server after a few minutes later. Is this expected behavior for delete method?
[Amit]: Yes the delete is asynchronous operation.
```

**Comment by romangromov** [comment]
@sreekanthbs suggestion from my side: try to use something like `setTimeout` function, this should do the trick here

**Comment by sreekanthbs** [comment]
@romangromov thanks for the update

**Comment by romangromov** [comment]
Hi @sreekanthbs, now `network gateway vnet delete` works in sync way, please make sure it works fine now, thanks

**Comment by sreekanthbs** [comment]
@romangromov issue still exist
![image](https://cloud.githubusercontent.com/assets/11171941/9683394/7330f8ec-532d-11e5-8b3e-17251338db45.png)

**Comment by romangromov** [comment]
@sreekanthbs not sure why you are getting this behavior, delete works fine for me. Please try to logout and then login
![screenshot_9](https://cloud.githubusercontent.com/assets/1655573/9683715/406cb516-531b-11e5-8ed6-d0d243237dac.png)

**Comment by sreekanthbs** [comment]
@romangromov The issue is in the provisioning state of the gateway.
If the state is -- Succeeded 
Then the delete is working fine.
Please look at the screenshot
![image](https://cloud.githubusercontent.com/assets/11171941/9712768/9956f7b2-556a-11e5-83dd-37da403e33f5.png)

But sometimes the gateway is gets created in failed state.
If  Provisioning state = Failed
Then the gateway delete is not working as expected.
I just run the same command which i run for above the above screenshot but this time the gateway gets created in failed state.
Please have a look at the below screenshot for the detail
![image](https://cloud.githubusercontent.com/assets/11171941/9712901/8b8f5204-556b-11e5-9946-21a558390e7c.png)

**Comment by romangromov** [comment]
@sreekanthbs got it, thank you for verifying, will ping Gateway team about `prov. state=failed` issue

**Comment by romangromov** [comment]
UPD: can't repro this with Autorest SDK, close issue after migration to autorest
