### ISSUE TITLE
ARM:network application-gateway create not working for -t  && --subnet-name  option

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#487]
![image](https://cloud.githubusercontent.com/assets/11171941/9377578/ff5fb814-4737-11e5-983f-05cd0a5dcdee.png)
![image](https://cloud.githubusercontent.com/assets/11171941/9377615/61957262-4738-11e5-8d34-78b851a3c03a.png)

**Comment by MikhailTryakhov** [comment]
Hi @sreekanthbs, this branch is a test branch,
app gateways commands are blocked now. I'll revert test changes in this branch

**Comment by MikhailTryakhov** [comment]
Sorry @sreekanthbs it was a test commit - it's reverted now.
Could you please close this bug

**Comment by sreekanthbs** [comment]
Yes sure.Closing the issue
