### ISSUE TITLE
ARM:network application-gateway create not working

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#488]
![image](https://cloud.githubusercontent.com/assets/11171941/9377672/e668c4e4-4738-11e5-9d8d-2bda51383d04.png)

**Comment by MikhailTryakhov** [comment]
Sorry @sreekanthbs it was a test commit - it's reverted now.
Could you please close this bug

**Comment by sreekanthbs** [comment]
Yes sure.Closing the issue
