### ISSUE TITLE
ARM:network gateway vnet create some times fail

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#489]
Sometime 'network gateway vnet create' fails giving error connect ETIMEDOUT

![image](https://cloud.githubusercontent.com/assets/11171941/9436158/eaea1cf4-4a6a-11e5-9b95-76cdace934b5.png)

**Comment by romangromov** [comment]
@sreekanthbs can't repro this, it's working fine for me...
FYI: I've a separate thread with Networking team about issues in VPN gateways. There are several well known issues on their side, that's why API may not be stable. Will keep you posted about news from their side

**Comment by sreekanthbs** [comment]
@romangromov  even for me it is working fine.but sometime i am getting this error.

**Comment by romangromov** [comment]
Hi @sreekanthbs, looks like it was fixed, please make sure you are able to create Vnet Gateway stably, thanks

**Comment by sreekanthbs** [comment]
@romangromov still this issue exist
![image](https://cloud.githubusercontent.com/assets/11171941/9683118/aa583630-532a-11e5-977d-6d6e06fd998d.png)

**Comment by sreekanthbs** [comment]
@romangromov  now gateway is getting created without any error.But sometime the gateway is created with provisioning state as failed.

**Comment by romangromov** [comment]
@sreekanthbs the same here for me, thanks

**Comment by sreekanthbs** [comment]
@romangromov still Sometime 'network gateway vnet create' fails giving error  -- CONNECT ETIMEDOUT.
Any update on this?

**Comment by romangromov** [comment]
@sreekanthbs no updated on this, will ping again

**Comment by romangromov** [comment]
UPD: can't repro this with Autorest SDK, close issue after migration to autorest
