### ISSUE TITLE
ARM:network vnet subnet delete giving error which is used for gateway 

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#492]
Hi @romangromov network vnet subnet delete giving error which is used for gateway from branch dev-arm-vpn-gateways

![vnet subnet error](https://cloud.githubusercontent.com/assets/11171941/9498217/3b29b90a-4c36-11e5-9f1d-592269fbd148.png)

**Comment by sreekanthbs** [comment]
The gateway is getting created in failed state.
![gateway_create_state_failed](https://cloud.githubusercontent.com/assets/11171941/9498719/cb703ab4-4c38-11e5-9c6d-e6e38247787b.png)

**Comment by romangromov** [comment]
@sreekanthbs can you please describe step-by-step how I can repro this issue?
Thanks in advance!

**Comment by sreekanthbs** [comment]
@romangromov  this error is coming sometime because the gateway which we created using GatewaySubnet is getting created in failed state sometime.
Please have a look at the steps  we following.
<Pre>
<code>1.azure network vnet create grpname vnet1 eastus -a 10.0.0.0/24
2.azure network vnet subnet create grpname vnet1 GatewaySubnet -a 10.0.0.0/28
3.azure network public-ip create grpname publicip1 eastus
4.azure network gateway vnet create -g grpname -n gateway1 -l eastus -y RouteBased -p publicip1 -m vnet1 -e GatewaySubnet -a 10.0.0.11 -b true -t tag1=val1
5.azure network gateway vnet delete grpname gateway1 -q
Till here everything is working fine for me
6. azure network vnet subnet delete vnet1 GatewaySubnet -q</code></pre>
Step 6 is sometime failing giving error because sometime the gateway that is created is in failed state.
![image](https://cloud.githubusercontent.com/assets/11171941/9518297/6f35a1d0-4cd3-11e5-9a9a-f935ebbcbda3.png)

Please have a look at the error we are getting when trying to delete the the subnet
![vnet subnet error](https://cloud.githubusercontent.com/assets/11171941/9518321/9140908c-4cd3-11e5-9112-a5b853f8756f.png)

**Comment by sreekanthbs** [comment]
Hi @romangromov  any update on the issue?

**Comment by romangromov** [comment]
@sreekanthbs this should be reported to networking team

**Comment by romangromov** [comment]
Hi @sreekanthbs, looks like it was fixed as well, please try to repro and let me know

**Comment by sreekanthbs** [comment]
@romangromov issue still exist

**Comment by sreekanthbs** [comment]
@romangromov this issue is because sometimes the gateway is getting created with provisioning state as failed.
![image](https://cloud.githubusercontent.com/assets/11171941/9713053/99bd858e-556c-11e5-9f0b-08007ba23ca0.png)

**Comment by romangromov** [comment]
@sreekanthbs thanks, I've ping Gateway team about this

**Comment by romangromov** [comment]
UPD:  can't repro this with Autorest SDK
