### ISSUE TITLE
ARM:network gateway create not working, giving wrong error message

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#497]
![image](https://cloud.githubusercontent.com/assets/11171941/9682002/25501106-5320-11e5-89bb-04507a62e406.png)

**Comment by sreekanthbs** [comment]
please find below the verbose output for the error
<pre>
</code>
C:\Sept\4sept\azure-xplat-cli-dev-arm-vpn-gateways>node bin/azure network gateway vnet create armresgrp4a gatewayvnet4a "West US" -y RouteBased -u publicip4a  -m vnet
4a -e GatewaySubnet -a 10.0.0.11 -b true -t tag1=val1 -vv
info:    Executing command network gateway vnet create
verbose: Looking up the subnet "GatewaySubnet"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { Content-Type: 'application/json', user-agent: 'WindowsAzureXplatCLI/0.9.8' },
silly:       url: 'https://management.azure.com/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp4a/providers/Microsoft.Network/virtualnetwo
rks/vnet4a/subnets/GatewaySubnet?api-version=2015-05-01-preview'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-length: '352',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           etag: 'W/"e2d579e3-8951-42f9-9105-2daa051e5a3e"',
silly:           x-ms-request-id: 'a87c5ea4-9eb7-491b-8222-bed8da8a4ec0',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
silly:           x-ms-ratelimit-remaining-subscription-reads: '14993',
silly:           x-ms-correlation-request-id: 'cf090957-0e74-4daf-a9ec-052b60f7f988',
silly:           x-ms-routing-request-id: 'SOUTHEASTASIA:20150904T105449Z:cf090957-0e74-4daf-a9ec-052b60f7f988',
silly:           date: 'Fri, 04 Sep 2015 10:54:49 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '{\015\n  "name": "GatewaySubnet",\015\n  "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp4a/providers/Microsoft
.Network/virtualNetworks/vnet4a/subnets/GatewaySubnet",\015\n  "etag": "W/\\"e2d579e3-8951-42f9-9105-2daa051e5a3e\\"",\015\n  "properties": {\015\n    "provisioningSt
ate": "Succeeded",\015\n    "addressPrefix": "10.0.0.0/28"\015\n  }\015\n}'
silly:   }
verbose: Looking up virtual network gateway "gatewayvnet4a"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { Content-Type: 'application/json', user-agent: 'WindowsAzureXplatCLI/0.9.8' },
silly:       url: 'https://management.azure.com/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp4a/providers/Microsoft.Network/virtualNetwo
rkGateways/gatewayvnet4a?api-version=2015-05-01-preview'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 404,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           x-ms-failure-cause: 'gateway',
silly:           x-ms-request-id: 'd3f3aa04-b5cb-431b-9f1a-9aed6f9fe7e6',
silly:           x-ms-correlation-request-id: 'd3f3aa04-b5cb-431b-9f1a-9aed6f9fe7e6',
silly:           x-ms-routing-request-id: 'SOUTHEASTASIA:20150904T105450Z:d3f3aa04-b5cb-431b-9f1a-9aed6f9fe7e6',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           date: 'Fri, 04 Sep 2015 10:54:50 GMT',
silly:           connection: 'close',
silly:           content-length: '169'
silly:       },
silly:       body: "{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Network/virtualNetworkGateways/gatewayvnet4a' under resource group 'armresg
rp4a' was not found."}}"
silly:   }
verbose: Creating virtual network gateway "gatewayvnet4a"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'PUT',
silly:       headers: {
silly:           Content-Type: 'application/json',
silly:           Content-Length: 455,
silly:           user-agent: 'WindowsAzureXplatCLI/0.9.8'
silly:       },
silly:       url: 'https://management.azure.com/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp4a/providers/Microsoft.Network/virtualnetwo
rkgateways/gatewayvnet4a?api-version=2015-05-01-preview',
silly:       body: '{"properties":{"ipConfigurations":[{"properties":{"privateIPAddress":"10.0.0.11","privateIPAllocationMethod":"Static","subnet":{"id":"/subscriptio
ns/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp4a/providers/Microsoft.Network/virtualNetworks/vnet4a/subnets/GatewaySubnet"},"publicIPAddress":{"id":
"publicip4a"}},"name":"ip-config"}],"gatewayType":"Vpn","vpnType":"RouteBased","enableBgp":"true"},"location":"West US","tags":{"tag1":"val1"}}'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 400,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-length: '402',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           x-ms-request-id: 'c7599e98-0c52-4163-a2ca-496aa9542fc8',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
silly:           x-ms-ratelimit-remaining-subscription-writes: '1194',
silly:           x-ms-correlation-request-id: '081a20de-be24-4bed-8b6a-7e84b4564dd1',
silly:           x-ms-routing-request-id: 'SOUTHEASTASIA:20150904T105455Z:081a20de-be24-4bed-8b6a-7e84b4564dd1',
silly:           date: 'Fri, 04 Sep 2015 10:54:55 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '{\015\n  "error": {\015\n    "code": "InvalidRequestFormat",\015\n    "message": "Cannot parse the request.",\015\n    "details": [\015\n      {\0
15\n        "code": "InvalidJsonReferenceFormat",\015\n        "message": "Reference Id publicip4a is not formatted correctly. The Id is expected to reference resourc
es of type publicIPAddresses. Path properties.ipConfigurations[0].properties.publicIPAddress."\015\n      }\015\n    ]\015\n  }\015\n}'
silly:   }
error:   Cannot parse the request.
silly:   {
silly:       stack: 'Error: Cannot parse the request.\n    at Function.ServiceClient._normalizeError (C:\\Sept\\4sept\\azure-xplat-cli-dev-arm-vpn-gateways\\node_modu
les\\azure-common\\lib\\services\\serviceclient.js:815:23)\n    at C:\\Sept\\4sept\\azure-xplat-cli-dev-arm-vpn-gateways\\node_modules\\azure-common\\lib\\services\\f
ilters\\errorhandlingfilter.js:44:29\n    at Request._callback (C:\\Sept\\4sept\\azure-xplat-cli-dev-arm-vpn-gateways\\node_modules\\azure-common\\lib\\http\\request-
pipeline.js:109:14)\n    at Request.self.callback (C:\\Sept\\4sept\\azure-xplat-cli-dev-arm-vpn-gateways\\node_modules\\azure-common\\node_modules\\request\\request.j
s:199:22)\n    at Request.emit (events.js:110:17)\n    at Request.<anonymous> (C:\\Sept\\4sept\\azure-xplat-cli-dev-arm-vpn-gateways\\node_modules\\azure-common\\node
_modules\\request\\request.js:1160:14)\n    at Request.emit (events.js:129:20)\n    at IncomingMessage.<anonymous> (C:\\Sept\\4sept\\azure-xplat-cli-dev-arm-vpn-gatew
ays\\node_modules\\azure-common\\node_modules\\request\\request.js:1111:12)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n',
silly:       message: 'Cannot parse the request.',
silly:       code: 'InvalidRequestFormat',
silly:       details: [
silly:           { code: 'InvalidJsonReferenceFormat', message: 'Reference Id publicip4a is not formatted correctly. The Id is expected to reference resources of type
 publicIPAddresses. Path properties.ipConfigurations[0].properties.publicIPAddress.' }
silly:       ],
silly:       statusCode: 400,
silly:       requestId: 'c7599e98-0c52-4163-a2ca-496aa9542fc8',
silly:       __frame: {
silly:           name: '_createOrUpdate__9',
silly:           line: 202,
silly:           file: 'C:\\Sept\\4sept\\azure-xplat-cli-dev-arm-vpn-gateways\\lib\\commands\\arm\\network\\virtualNetworkGateway._js',
silly:           prev: {
silly:               name: 'create__1',
silly:               line: 39,
silly:               file: 'C:\\Sept\\4sept\\azure-xplat-cli-dev-arm-vpn-gateways\\lib\\commands\\arm\\network\\virtualNetworkGateway._js',
silly:               prev: {
silly:                   name: '__93',
silly:                   line: 2014,
silly:                   file: 'C:\\Sept\\4sept\\azure-xplat-cli-dev-arm-vpn-gateways\\lib\\commands\\arm\\network\\network._js',
silly:                   prev: undefined,
silly:                   calls: 5,
silly:                   active: false,
silly:                   offset: 17,
silly:                   col: 18
silly:               },
silly:               calls: 3,
silly:               active: false,
silly:               offset: 11,
silly:               col: 9
silly:           },
silly:           calls: 0,
silly:           active: false,
silly:           offset: 5,
silly:           col: 64
silly:       },
silly:       rawStack: 'Error: Cannot parse the request.\n    at Function.ServiceClient._normalizeError (C:\\Sept\\4sept\\azure-xplat-cli-dev-arm-vpn-gateways\\node_m
odules\\azure-common\\lib\\services\\serviceclient.js:815:23)\n    at C:\\Sept\\4sept\\azure-xplat-cli-dev-arm-vpn-gateways\\node_modules\\azure-common\\lib\\services
\\filters\\errorhandlingfilter.js:44:29\n    at Request._callback (C:\\Sept\\4sept\\azure-xplat-cli-dev-arm-vpn-gateways\\node_modules\\azure-common\\lib\\http\\reque
st-pipeline.js:109:14)\n    at Request.self.callback (C:\\Sept\\4sept\\azure-xplat-cli-dev-arm-vpn-gateways\\node_modules\\azure-common\\node_modules\\request\\reques
t.js:199:22)\n    at Request.emit (events.js:110:17)\n    at Request.<anonymous> (C:\\Sept\\4sept\\azure-xplat-cli-dev-arm-vpn-gateways\\node_modules\\azure-common\\n
ode_modules\\request\\request.js:1160:14)\n    at Request.emit (events.js:129:20)\n    at IncomingMessage.<anonymous> (C:\\Sept\\4sept\\azure-xplat-cli-dev-arm-vpn-ga
teways\\node_modules\\azure-common\\node_modules\\request\\request.js:1111:12)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n'
silly:   }
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
verbose: Error: Cannot parse the request.
    at Function.ServiceClient._normalizeError (C:\Sept\4sept\azure-xplat-cli-dev-arm-vpn-gateways\node_modules\azure-common\lib\services\serviceclient.js:815:23)
    at C:\Sept\4sept\azure-xplat-cli-dev-arm-vpn-gateways\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:44:29
    at Request._callback (C:\Sept\4sept\azure-xplat-cli-dev-arm-vpn-gateways\node_modules\azure-common\lib\http\request-pipeline.js:109:14)
    at Request.self.callback (C:\Sept\4sept\azure-xplat-cli-dev-arm-vpn-gateways\node_modules\azure-common\node_modules\request\request.js:199:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (C:\Sept\4sept\azure-xplat-cli-dev-arm-vpn-gateways\node_modules\azure-common\node_modules\request\request.js:1160:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (C:\Sept\4sept\azure-xplat-cli-dev-arm-vpn-gateways\node_modules\azure-common\node_modules\request\request.js:1111:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16

error:   network gateway vnet create command failed
</code>
</pre>

**Comment by romangromov** [comment]
@sreekanthbs figure it out: you are using `-u` to provide publicIP name, but shortcut for publicIP name is `-p`, please run `azure network gateway vnet create -h` for details

**Comment by sreekanthbs** [comment]
@romangromov yes .Got it.Closing the issue.
Thanks for the info.
