### ISSUE TITLE
ARM : network application-gateway start not working 

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#499]
Sometime the 'network application-gateway start' is giving error.Please have a look at screenshot for the error
![image](https://cloud.githubusercontent.com/assets/11171941/9875666/9605306a-5bcd-11e5-91b9-3482aafdc1fb.png)

**Comment by sreekanthbs** [comment]
![image](https://cloud.githubusercontent.com/assets/11171941/9875659/84505408-5bcd-11e5-8d5d-3b40b7c119d2.png)

**Comment by MikhailTryakhov** [comment]
Hi @sreekanthbs could you please review again, is it still reproduced?

**Comment by sreekanthbs** [comment]
@MikhailTryakhov yes its working fine now.Hence Closing the issue
