### ISSUE TITLE
ARM: network application-gateway frontend-port add not working

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#502]
<pre>
<code>
C:\Sep2015\21Sep\azure-xplat-cli-dev-arm-app-gateways>node bin/azure network application-gateway frontend-port add test-trya-group appgw01 tryaPort -o 1234
info:    Executing command network application-gateway frontend-port add
error:   callback missing (argument #5). See https://github.com/Sage/streamlinejs/blob/master/FAQ.md#no-callback-given-error
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
error:   network application-gateway frontend-port add command failed
</code>
</pre>

**Comment by MikhailTryakhov** [comment]
Hi @sreekanthbs thank you for such test. It's fixed now, please review it again
