### ISSUE TITLE
ARM : network application-gateway start not working

### ISSUE THREAD

**Issue by MikhailTryakhov** [MSOpenTech/azure-xplat-cli#507]
Server throws error after command start for already started app gateway
Screenshot is [here](https://gyazo.com/f8b62e94ea1584b2622c5b9f937ef71e)

**Comment by sreekanthbs** [comment]
@MikhailTryakhov issue is still there in the latest commmit.

**Comment by MikhailTryakhov** [comment]
Hi @sreekanthbs 
please review it again and close if it's fixed

**Comment by sreekanthbs** [comment]
@MikhailTryakhov yes its working fine now.Thanks.Can you please close this issue.
![image](https://cloud.githubusercontent.com/assets/11171941/10729286/4d9b7936-7c0e-11e5-90db-0b68b0249b26.png)
