### ISSUE TITLE
ARM: network lb inbound-nat-pool create is not working

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#510]
network lb inbound-nat-pool create is not working from the branch <b>arm-lb-inbound-nat-pool</b>
<pre>
<code>
C:\Sep2015\24Sep\azure-xplat-cli-arm-lb-inbound-nat-pool>node bin/azure network lb inbound-nat-pool create armresgrp16s lb29 lbnatpool1
info:    Executing command network lb inbound-nat-pool create
+ Looking up the load balancer "lb29"
warn:    Using default protocol: tcp
warn:    Using default frontend port range start: 0
warn:    Using default frontend port range end: 65535
warn:    Using default backend port: 80
warn:    Setting default inbound NAT pool frontend IP configuration
+ Updating load balancer "lb29"
+ Looking up the load balancer "lb29"
error:   Cannot read property 'name' of undefined
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
error:   network lb inbound-nat-pool create command failed

C:\Sep2015\24Sep\azure-xplat-cli-arm-lb-inbound-nat-pool>node bin/azure network lb inbound-nat-pool create armresgrp16s lb29 lbnatpool1 -p tcp -f 4 -b 80 -i vip
29
info:    Executing command network lb inbound-nat-pool create
+ Looking up the load balancer "lb29"
warn:    Using default frontend port range end: 65535
+ Updating load balancer "lb29"
+ Looking up the load balancer "lb29"
error:   Cannot read property 'name' of undefined
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
error:   network lb inbound-nat-pool create command failed

C:\Sep2015\24Sep\azure-xplat-cli-arm-lb-inbound-nat-pool>node bin/azure network lb inbound-nat-pool create armresgrp16s lb29 lbnatpool1 -p tcp -f 4 -e 4 -b 80 -
i vip29
info:    Executing command network lb inbound-nat-pool create
+ Looking up the load balancer "lb29"
+ Updating load balancer "lb29"
+ Looking up the load balancer "lb29"
error:   Cannot read property 'name' of undefined
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
error:   network lb inbound-nat-pool create command failed
</code>
</pre>

Verbose output
<pre>
<code>
C:\Sep2015\24Sep\azure-xplat-cli-arm-lb-inbound-nat-pool>node bin/azure network lb inbound-nat-pool create armresgrp16s lb29 lbnatpool1 -vv
info:    Executing command network lb inbound-nat-pool create
verbose: Looking up the load balancer "lb29"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { Content-Type: 'application/json', user-agent: 'WindowsAzureXplatCLI/0.9.9' },
silly:       url: 'https://management.azure.com/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp16s/providers/Microsoft.Network/loadB
alancers/lb29?api-version=2015-05-01-preview'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-length: '1183',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           etag: 'W/"0c4b4d09-4324-4874-b5e2-fa09c8ed8de8"',
silly:           x-ms-request-id: '0e0d340f-b776-41c8-8e1b-740072cbb55a',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
silly:           x-ms-ratelimit-remaining-subscription-reads: '14977',
silly:           x-ms-correlation-request-id: '21146b4d-f594-4a1a-a956-5a64204b7468',
silly:           x-ms-routing-request-id: 'WESTUS:20150924T112610Z:21146b4d-f594-4a1a-a956-5a64204b7468',
silly:           date: 'Thu, 24 Sep 2015 11:26:10 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '{\015\n  "name": "lb29",\015\n  "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp16s/providers/Microsoft.N
etwork/loadBalancers/lb29",\015\n  "etag": "W/\\"0c4b4d09-4324-4874-b5e2-fa09c8ed8de8\\"",\015\n  "properties": {\015\n    "provisioningState": "Succeeded",\015
\n    "resourceGuid": "e5947c87-0eb8-4eb1-8988-e5571fc70df1",\015\n    "frontendIPConfigurations": [\015\n      {\015\n        "name": "vip29",\015\n        "id
": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp16s/providers/Microsoft.Network/loadBalancers/lb29/frontendIPConfigurations/vip2
9",\015\n        "etag": "W/\\"0c4b4d09-4324-4874-b5e2-fa09c8ed8de8\\"",\015\n        "properties": {\015\n          "provisioningState": "Succeeded",\015\n
      "privateIPAllocationMethod": "Dynamic",\015\n          "publicIPAddress": {\015\n            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/re
sourceGroups/armresgrp16s/providers/Microsoft.Network/publicIPAddresses/publicip16s"\015\n          }\015\n        }\015\n      }\015\n    ],\015\n    "backendA
ddressPools": [],\015\n    "loadBalancingRules": [],\015\n    "probes": [],\015\n    "inboundNatRules": [],\015\n    "outboundNatRules": []\015\n  },\015\n  "lo
cation": "eastus",\015\n  "tags": {}\015\n}'
silly:   }
warn:    Using default protocol: tcp
warn:    Using default frontend port range start: 0
warn:    Using default frontend port range end: 65535
warn:    Using default backend port: 80
warn:    Setting default inbound NAT pool frontend IP configuration
verbose: Updating load balancer "lb29"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'PUT',
silly:       headers: {
silly:           Content-Type: 'application/json',
silly:           Content-Length: 1377,
silly:           user-agent: 'WindowsAzureXplatCLI/0.9.9'
silly:       },
silly:       url: 'https://management.azure.com/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp16s/providers/Microsoft.Network/loadB
alancers/lb29?api-version=2015-05-01-preview',
silly:       body: '{"properties":{"frontendIPConfigurations":[{"properties":{"privateIPAllocationMethod":"Dynamic","publicIPAddress":{"id":"/subscriptions/bfb5
e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp16s/providers/Microsoft.Network/publicIPAddresses/publicip16s"},"inboundNatRules":[],"inboundNatPools":
[],"outboundNatRules":[],"loadBalancingRules":[],"provisioningState":"Succeeded"},"name":"vip29","etag":"W/\\"0c4b4d09-4324-4874-b5e2-fa09c8ed8de8\\"","id":"/su
bscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp16s/providers/Microsoft.Network/loadBalancers/lb29/frontendIPConfigurations/vip29"}],"b
ackendAddressPools":[],"loadBalancingRules":[],"probes":[],"inboundNatRules":[],"inboundNatPools":[{"properties":{"frontendIPConfiguration":{"id":"/subscription
s/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp16s/providers/Microsoft.Network/loadBalancers/lb29/frontendIPConfigurations/vip29"},"protocol":"t
cp","frontendPortRangeStart":0,"frontendPortRangeEnd":65535,"backendPort":80},"name":"lbnatpool1"}],"outboundNatRules":[],"resourceGuid":"e5947c87-0eb8-4eb1-898
8-e5571fc70df1","provisioningState":"Succeeded"},"etag":"W/\\"0c4b4d09-4324-4874-b5e2-fa09c8ed8de8\\"","id":"/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948
/resourceGroups/armresgrp16s/providers/Microsoft.Network/loadBalancers/lb29","name":"lb29","location":"eastus","tags":{}}'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-length: '1183',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           x-ms-request-id: '543796cd-d8fd-4787-9a25-3a583411f141',
silly:           azure-asyncoperation: 'https://management.azure.com/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/providers/Microsoft.Network/locations/ea
stus/operations/543796cd-d8fd-4787-9a25-3a583411f141?api-version=2015-05-01-preview',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
silly:           x-ms-ratelimit-remaining-subscription-writes: '1197',
silly:           x-ms-correlation-request-id: '6aabbb9a-6757-4878-9eef-15a655afb9ac',
silly:           x-ms-routing-request-id: 'WESTUS:20150924T112612Z:6aabbb9a-6757-4878-9eef-15a655afb9ac',
silly:           date: 'Thu, 24 Sep 2015 11:26:11 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '{\015\n  "name": "lb29",\015\n  "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp16s/providers/Microsoft.N
etwork/loadBalancers/lb29",\015\n  "etag": "W/\\"784d2b65-75ae-4ce0-b57b-cb75085f6e5e\\"",\015\n  "properties": {\015\n    "provisioningState": "Succeeded",\015
\n    "resourceGuid": "e5947c87-0eb8-4eb1-8988-e5571fc70df1",\015\n    "frontendIPConfigurations": [\015\n      {\015\n        "name": "vip29",\015\n        "id
": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp16s/providers/Microsoft.Network/loadBalancers/lb29/frontendIPConfigurations/vip2
9",\015\n        "etag": "W/\\"784d2b65-75ae-4ce0-b57b-cb75085f6e5e\\"",\015\n        "properties": {\015\n          "provisioningState": "Succeeded",\015\n
      "privateIPAllocationMethod": "Dynamic",\015\n          "publicIPAddress": {\015\n            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/re
sourceGroups/armresgrp16s/providers/Microsoft.Network/publicIPAddresses/publicip16s"\015\n          }\015\n        }\015\n      }\015\n    ],\015\n    "backendA
ddressPools": [],\015\n    "loadBalancingRules": [],\015\n    "probes": [],\015\n    "inboundNatRules": [],\015\n    "outboundNatRules": []\015\n  },\015\n  "lo
cation": "eastus",\015\n  "tags": {}\015\n}'
silly:   }
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { x-ms-version: '2015-05-01-preview', user-agent: 'WindowsAzureXplatCLI/0.9.9' },
silly:       url: 'https://management.azure.com/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/providers/Microsoft.Network/locations/eastus/operations/54379
6cd-d8fd-4787-9a25-3a583411f141?api-version=2015-05-01-preview'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-length: '29',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           x-ms-request-id: '44fecefd-f29b-4b2d-9d5f-e565ea5ca834',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
silly:           x-ms-ratelimit-remaining-subscription-reads: '14991',
silly:           x-ms-correlation-request-id: '703e0cb3-659b-44b6-a6c9-a6ad274cd7e4',
silly:           x-ms-routing-request-id: 'WESTUS:20150924T112613Z:703e0cb3-659b-44b6-a6c9-a6ad274cd7e4',
silly:           date: 'Thu, 24 Sep 2015 11:26:13 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '{\015\n  "status": "Succeeded"\015\n}'
silly:   }
verbose: Looking up the load balancer "lb29"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { Content-Type: 'application/json', user-agent: 'WindowsAzureXplatCLI/0.9.9' },
silly:       url: 'https://management.azure.com/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp16s/providers/Microsoft.Network/loadB
alancers/lb29?api-version=2015-05-01-preview'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-length: '1183',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           etag: 'W/"784d2b65-75ae-4ce0-b57b-cb75085f6e5e"',
silly:           x-ms-request-id: '32aee0e1-1927-4f3d-9fbf-fd37545b57ab',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
silly:           x-ms-ratelimit-remaining-subscription-reads: '14990',
silly:           x-ms-correlation-request-id: '992c0b89-1c98-4e3d-9c32-542f1148ef00',
silly:           x-ms-routing-request-id: 'WESTUS:20150924T112615Z:992c0b89-1c98-4e3d-9c32-542f1148ef00',
silly:           date: 'Thu, 24 Sep 2015 11:26:14 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '{\015\n  "name": "lb29",\015\n  "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp16s/providers/Microsoft.N
etwork/loadBalancers/lb29",\015\n  "etag": "W/\\"784d2b65-75ae-4ce0-b57b-cb75085f6e5e\\"",\015\n  "properties": {\015\n    "provisioningState": "Succeeded",\015
\n    "resourceGuid": "e5947c87-0eb8-4eb1-8988-e5571fc70df1",\015\n    "frontendIPConfigurations": [\015\n      {\015\n        "name": "vip29",\015\n        "id
": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp16s/providers/Microsoft.Network/loadBalancers/lb29/frontendIPConfigurations/vip2
9",\015\n        "etag": "W/\\"784d2b65-75ae-4ce0-b57b-cb75085f6e5e\\"",\015\n        "properties": {\015\n          "provisioningState": "Succeeded",\015\n
      "privateIPAllocationMethod": "Dynamic",\015\n          "publicIPAddress": {\015\n            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/re
sourceGroups/armresgrp16s/providers/Microsoft.Network/publicIPAddresses/publicip16s"\015\n          }\015\n        }\015\n      }\015\n    ],\015\n    "backendA
ddressPools": [],\015\n    "loadBalancingRules": [],\015\n    "probes": [],\015\n    "inboundNatRules": [],\015\n    "outboundNatRules": []\015\n  },\015\n  "lo
cation": "eastus",\015\n  "tags": {}\015\n}'
silly:   }
silly:   undefined
error:   Cannot read property 'name' of undefined
silly:   {
silly:       stack: "TypeError: Cannot read property 'name' of undefined\n    at C:\\Sep2015\\24Sep\\azure-xplat-cli-arm-lb-inbound-nat-pool\\lib\\commands\\arm
\\network\\loadBalancer._js:1234:44\n    at Interactor.__.extend.formatOutput (C:\\Sep2015\\24Sep\\azure-xplat-cli-arm-lb-inbound-nat-pool\\lib\\util\\interacti
on._js:268:7)\n    at LoadBalancer.__.extend.showInboundNatPool (C:\\Sep2015\\24Sep\\azure-xplat-cli-arm-lb-inbound-nat-pool\\lib\\commands\\arm\\network\\loadB
alancer._js:1233:22)\n    at ___ (C:\\Sep2015\\24Sep\\azure-xplat-cli-arm-lb-inbound-nat-pool\\lib\\commands\\arm\\network\\loadBalancer._js:1153:18)\n    at __
_ (C:\\Sep2015\\24Sep\\azure-xplat-cli-arm-lb-inbound-nat-pool\\node_modules\\streamline\\lib\\callbacks\\runtime.js:111:13)\n    at ___ (C:\\Sep2015\\24Sep\\az
ure-xplat-cli-arm-lb-inbound-nat-pool\\lib\\commands\\arm\\network\\loadBalancer._js:213:17)\n    at __tryCatch (C:\\Sep2015\\24Sep\\azure-xplat-cli-arm-lb-inbo
und-nat-pool\\node_modules\\streamline\\lib\\callbacks\\runtime.js:150:4)\n    at ___ (C:\\Sep2015\\24Sep\\azure-xplat-cli-arm-lb-inbound-nat-pool\\lib\\command
s\\arm\\network\\loadBalancer._js:209:13)\n    at __$get__4 (C:\\Sep2015\\24Sep\\azure-xplat-cli-arm-lb-inbound-nat-pool\\lib\\commands\\arm\\network\\loadBalan
cer._js:206:15)\n    at __tryCatch (C:\\Sep2015\\24Sep\\azure-xplat-cli-arm-lb-inbound-nat-pool\\node_modules\\streamline\\lib\\callbacks\\runtime.js:150:4)\n",

silly:       message: "Cannot read property 'name' of undefined",
silly:       __frame: {
silly:           name: 'createInboundNatPool__26',
silly:           line: 632,
silly:           file: 'C:\\Sep2015\\24Sep\\azure-xplat-cli-arm-lb-inbound-nat-pool\\lib\\commands\\arm\\network\\loadBalancer._js',
silly:           prev: {
silly:               name: '__34',
silly:               line: 718,
silly:               file: 'C:\\Sep2015\\24Sep\\azure-xplat-cli-arm-lb-inbound-nat-pool\\lib\\commands\\arm\\network\\network._js',
silly:               prev: undefined,
silly:               calls: 4,
silly:               active: false,
silly:               offset: 7,
silly:               col: 19
silly:           },
silly:           calls: 3,
silly:           active: true,
silly:           offset: 19,
silly:           col: 25
silly:       },
silly:       rawStack: "TypeError: Cannot read property 'name' of undefined\n    at C:\\Sep2015\\24Sep\\azure-xplat-cli-arm-lb-inbound-nat-pool\\lib\\commands\\
arm\\network\\loadBalancer._js:1234:44\n    at Interactor.__.extend.formatOutput (C:\\Sep2015\\24Sep\\azure-xplat-cli-arm-lb-inbound-nat-pool\\lib\\util\\intera
ction._js:268:7)\n    at LoadBalancer.__.extend.showInboundNatPool (C:\\Sep2015\\24Sep\\azure-xplat-cli-arm-lb-inbound-nat-pool\\lib\\commands\\arm\\network\\lo
adBalancer._js:1233:22)\n    at ___ (C:\\Sep2015\\24Sep\\azure-xplat-cli-arm-lb-inbound-nat-pool\\lib\\commands\\arm\\network\\loadBalancer._js:1153:18)\n    at
 ___ (C:\\Sep2015\\24Sep\\azure-xplat-cli-arm-lb-inbound-nat-pool\\node_modules\\streamline\\lib\\callbacks\\runtime.js:111:13)\n    at ___ (C:\\Sep2015\\24Sep\
\azure-xplat-cli-arm-lb-inbound-nat-pool\\lib\\commands\\arm\\network\\loadBalancer._js:213:17)\n    at __tryCatch (C:\\Sep2015\\24Sep\\azure-xplat-cli-arm-lb-i
nbound-nat-pool\\node_modules\\streamline\\lib\\callbacks\\runtime.js:150:4)\n    at ___ (C:\\Sep2015\\24Sep\\azure-xplat-cli-arm-lb-inbound-nat-pool\\lib\\comm
ands\\arm\\network\\loadBalancer._js:209:13)\n    at __$get__4 (C:\\Sep2015\\24Sep\\azure-xplat-cli-arm-lb-inbound-nat-pool\\lib\\commands\\arm\\network\\loadBa
lancer._js:206:15)\n    at __tryCatch (C:\\Sep2015\\24Sep\\azure-xplat-cli-arm-lb-inbound-nat-pool\\node_modules\\streamline\\lib\\callbacks\\runtime.js:150:4)\
n"
silly:   }
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
verbose: TypeError: Cannot read property 'name' of undefined
    at C:\Sep2015\24Sep\azure-xplat-cli-arm-lb-inbound-nat-pool\lib\commands\arm\network\loadBalancer._js:1234:44
    at Interactor.__.extend.formatOutput (C:\Sep2015\24Sep\azure-xplat-cli-arm-lb-inbound-nat-pool\lib\util\interaction._js:268:7)
    at LoadBalancer.__.extend.showInboundNatPool (C:\Sep2015\24Sep\azure-xplat-cli-arm-lb-inbound-nat-pool\lib\commands\arm\network\loadBalancer._js:1233:22)
    at ___ (C:\Sep2015\24Sep\azure-xplat-cli-arm-lb-inbound-nat-pool\lib\commands\arm\network\loadBalancer._js:1153:18)
    at ___ (C:\Sep2015\24Sep\azure-xplat-cli-arm-lb-inbound-nat-pool\node_modules\streamline\lib\callbacks\runtime.js:111:13)
    at ___ (C:\Sep2015\24Sep\azure-xplat-cli-arm-lb-inbound-nat-pool\lib\commands\arm\network\loadBalancer._js:213:17)
    at __tryCatch (C:\Sep2015\24Sep\azure-xplat-cli-arm-lb-inbound-nat-pool\node_modules\streamline\lib\callbacks\runtime.js:150:4)
    at ___ (C:\Sep2015\24Sep\azure-xplat-cli-arm-lb-inbound-nat-pool\lib\commands\arm\network\loadBalancer._js:209:13)
    at __$get__4 (C:\Sep2015\24Sep\azure-xplat-cli-arm-lb-inbound-nat-pool\lib\commands\arm\network\loadBalancer._js:206:15)
    at __tryCatch (C:\Sep2015\24Sep\azure-xplat-cli-arm-lb-inbound-nat-pool\node_modules\streamline\lib\callbacks\runtime.js:150:4)

error:   network lb inbound-nat-pool create command failed
</code>
</pre>

**Comment by romangromov** [comment]
I have fix error, but you will be NOT able to create inbound NAT pool until having an access.

**Comment by sreekanthbs** [comment]
@romangromov  now i am able to create inbound NAT pool.Hence closing the issue
