### ISSUE TITLE
ARM:network application-gateway rule remove not working

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#512]
![image](https://cloud.githubusercontent.com/assets/11171941/10161859/913036aa-66c4-11e5-8845-9131694cd803.png)

**Comment by MikhailTryakhov** [comment]
Hi @sreekanthbs 
thank you for a great job!
I've mad such commands block blindly - it's fixed now
Could you please test it again

**Comment by MikhailTryakhov** [comment]
Add/remove tasks are blocked because of no way to add http listener available now.
![error message adding rule](https://gyazo.com/c7d39bf20d4c147e060a6edd43dc6769)
