### ISSUE TITLE
Arm: network application-gateway ip-config add not working

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#514]
1. Both --subnet-name & -name (ip-config) are using same option i.e -n 
2. After specifying all the required param , it prompt for subnet name twice 
3. In the error message it is displaying subnet  "testSubnet3"  as virtual network   --"'Microsoft.Network/virtualNetworks/testSubnet3'" under resource group 'test-trya-group3' was not found.

![image](https://cloud.githubusercontent.com/assets/11171941/10162185/1e06757e-66c7-11e5-9b7f-08883e114f52.png)

**Comment by MikhailTryakhov** [comment]
Hi @sreekanthbs 
thank you, great job! It's fixed now

**Comment by sreekanthbs** [comment]
@MikhailTryakhov  network application-gateway ip-config add command prompting for ::
1.subnet-name even though i provided the same in the command only
2.virtual-network-name -- I guess there should be one option for virtual-network-name in help ,currently there is no option for it.
![image](https://cloud.githubusercontent.com/assets/11171941/10163458/a8822190-66d0-11e5-8569-2937aa6e1031.png)

**Comment by MikhailTryakhov** [comment]
@sreekanthbs  you're right!
It's fixed now

**Comment by sreekanthbs** [comment]
@MikhailTryakhov please give different short names for each of 
 --name <name>
 --vnet-name <vnet-name>
 --subnet-name <subnet-name>
![image](https://cloud.githubusercontent.com/assets/11171941/10165394/aa44dfa2-66dc-11e5-8e22-8903f3e44120.png)

**Comment by MikhailTryakhov** [comment]
@sreekanthbs done!
thank you for a great job!

**Comment by sreekanthbs** [comment]
@MikhailTryakhov tried again with all options but still it is prompting to enter Ip config name and Virtual network name and giving error
<pre>
<code>
C:\Sep2015\29Sep\azure-xplat-cli-dev-arm-app-gateways>node bin/azure network application-gateway ip-config add test-trya-group3 appgw03 ipconfig1 -v vnet32 -u s
ubnet32
info:    Executing command network application-gateway ip-config add
Ip config name: ipconfig1
Virtual network name: vnet32
verbose: Looking up an Application Gateway "appgw03"
verbose: Looking up the subnet "subnet32"
verbose: Setting configuration for an Application Gateway "appgw03"
error:   2 IP configuration specified for gateway /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Networ
k/applicationGateways/appgw03. Gateway must be created with one IP configuration.
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
verbose: Error: 2 IP configuration specified for gateway /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft
.Network/applicationGateways/appgw03. Gateway must be created with one IP configuration.
    at Function.ServiceClient._normalizeError (C:\Sep2015\29Sep\azure-xplat-cli-dev-arm-app-gateways\node_modules\azure-common\lib\services\serviceclient.js:815
:23)
    at C:\Sep2015\29Sep\azure-xplat-cli-dev-arm-app-gateways\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:44:29
    at Request._callback (C:\Sep2015\29Sep\azure-xplat-cli-dev-arm-app-gateways\node_modules\azure-common\lib\http\request-pipeline.js:109:14)
    at Request.self.callback (C:\Sep2015\29Sep\azure-xplat-cli-dev-arm-app-gateways\node_modules\azure-common\node_modules\request\request.js:199:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (C:\Sep2015\29Sep\azure-xplat-cli-dev-arm-app-gateways\node_modules\azure-common\node_modules\request\request.js:1160:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (C:\Sep2015\29Sep\azure-xplat-cli-dev-arm-app-gateways\node_modules\azure-common\node_modules\request\request.js:1111:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
</code>
</pre>
<pre>
<code>
C:\Sep2015\29Sep\azure-xplat-cli-dev-arm-app-gateways>node bin/azure network application-gateway ip-config add test-trya-group3 appgw03
info:    Executing command network application-gateway ip-config add
Ip config name: ipconfig1
Virtual network name: tryaVnet3
Subnet name: testSubnet3
+ Looking up an Application Gateway "appgw03"
+ Looking up the subnet "testSubnet3"
+ Setting configuration for an Application Gateway "appgw03"
error:   2 IP configuration specified for gateway /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Networ
k/applicationGateways/appgw03. Gateway must be created with one IP configuration.
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
error:   network application-gateway ip-config add command failed
</code>
</pre>

**Comment by MikhailTryakhov** [comment]
Marked as expected
