### ISSUE TITLE
ARM:network application-gateway set command have same option for location & sku-name

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#515]
![image](https://cloud.githubusercontent.com/assets/11171941/10162596/103e918a-66ca-11e5-8c3a-ddfbcf980848.png)

**Comment by MikhailTryakhov** [comment]
@sreekanthbs sorry 
I'm afraid you're using not the latest branch version - there is no location option in set command anymore

**Comment by sreekanthbs** [comment]
@MikhailTryakhov i verified in the latest branch version again and the issue is there.
I verified in this branch https://github.com/MSOpenTech/azure-xplat-cli/tree/dev-arm-app-gateways .

**Comment by MikhailTryakhov** [comment]
@sreekanthbs you're right - I forgot about ```azure --gen``` command.
Please review it again

**Comment by sreekanthbs** [comment]
@MikhailTryakhov yes after running azure --gen command , now --location option is not coming.
Hence closing the issue
