### ISSUE TITLE
ARM: network application-gateway frontend-ip throws the same error for all cases

### ISSUE THREAD

**Issue by MikhailTryakhov** [MSOpenTech/azure-xplat-cli#522]
There are 3 ways to create frontend-ip, but in all 3 current for app gw server throws error
![Image](https://i.gyazo.com/6b6e10e59a5ae94b08f32ef4d116da31.png) 
for static private IP as the front-end IP address

and

![img](https://i.gyazo.com/49bc83b7003a3ef0b6452853c21f85c4.png)
for dynamic private IP as the front-end IP address

**Comment by sreekanthbs** [comment]
@MikhailTryakhov issue still exist
![image](https://cloud.githubusercontent.com/assets/11171941/10728395/6c738e0e-7c07-11e5-821e-ead8e3e70ae9.png)

**Comment by MikhailTryakhov** [comment]
Resolved on the server side

**Comment by romangromov** [comment]
@sreekanthbs please confirm we are good on this
