### ISSUE TITLE
ARM : network application-gateway http-listener add not working as expected

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#523]
When i run the add command , It gives error in output but actually its getting added in application gateway
![image](https://cloud.githubusercontent.com/assets/11171941/10273720/4880b424-6b52-11e5-9e36-3d4af0850011.png)

**Comment by MikhailTryakhov** [comment]
Hi @sreekanthbs. can't reproduse such issue.
Is it regular on your side - can you reproduce the same again?

**Comment by sreekanthbs** [comment]
@MikhailTryakhov its not regular but i encountered this issue twice

**Comment by sreekanthbs** [comment]
@MikhailTryakhov i verified on the latest branch.
Again got the same issue
![image](https://cloud.githubusercontent.com/assets/11171941/10396013/b0457f18-6ebd-11e5-8293-125a95e16376.png)

**Comment by MikhailTryakhov** [comment]
Duplicates issue https://github.com/MSOpenTech/azure-xplat-cli/issues/534
