### ISSUE TITLE
ARM : network application-gateway rule remove displaying wrong message

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#524]
![image](https://cloud.githubusercontent.com/assets/11171941/10273943/82330426-6b55-11e5-826c-6cfa7a2d5f80.png)

**Comment by MikhailTryakhov** [comment]
Thank you @sreekanthbs! Great job!
It's fixed now

**Comment by sreekanthbs** [comment]
@MikhailTryakhov  yes now its display correct message for the above mentioned issue.
But in case if we don't specify rule name in the command ,then its prompt for wrong message for name.
![image](https://cloud.githubusercontent.com/assets/11171941/10306245/3a7085c0-6c43-11e5-9fea-cb0807b82e2c.png)

**Comment by MikhailTryakhov** [comment]
It duplicates issue https://github.com/MSOpenTech/azure-xplat-cli/issues/528
