### ISSUE TITLE
ARM : network application-gateway set sometime does not end

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#525]
Sometime 'network application-gateway set' command doest not end even after 30 minutes

**Comment by MikhailTryakhov** [comment]
Thank you @sreekanthbs I'll add info message for that and communicate about such issue on the metting

**Comment by sreekanthbs** [comment]
@MikhailTryakhov i verified in the latest branch.
I run the same set command twice
First time it gave error.But on second time it worked perfectly fine.
Please find below the error details.
<pre>
<code>
C:\Oct\9oct\azure-xplat-cli-dev-arm-app-gateways>node bin/azure network application-gateway set test-trya-group3 appgw03   -l Standard_Small -z 5
info:    Executing command network application-gateway set
+ Looking up an Application Gateway "appgw03"
info:    Application gateway set command is a long-running process. It may take up to 15-20 minutes to complete.
+ Setting configuration for an Application Gateway "appgw03"
error:   output is not defined
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network application-gateway set command failed


C:\Oct\9oct\azure-xplat-cli-dev-arm-app-gateways>node bin/azure network application-gateway set test-trya-group3 appgw03   -l Standard_Small -z 5
info:    Executing command network application-gateway set
+ Looking up an Application Gateway "appgw03"
info:    Application gateway set command is a long-running process. It may take up to 15-20 minutes to complete.
+ Setting configuration for an Application Gateway "appgw03"
+ Looking up an Application Gateway "appgw03"
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/application
Gateways/appgw03
data:    Name                            : appgw03
data:    Location                        : westus
data:    Provisioning state              : Succeeded
data:    Sku                             : Standard_Small
data:    Resource Group                  : test-trya-group3
data:    Gateway IP configations         : [gatewayip03]
data:    SSL cerificates                 : []
data:    Frontend ip configurations      : [frontendip03]
data:    Frontend ports                  : [frontendport03, frntport3]
data:    Backend address pools           : [pool03, backendpool3]
data:    Backend http settings           : [setting03, httpsetting3]
data:    Http listeners                  : [listener03, httplistener3]
data:    Request routing rules           : [rule03]
data:    GatewayIpConfigurationText      : [
    {
        "subnet": {
            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/virtualNetworks/tryaVnet3/subnets/t
estSubnet3"
        },
        "provisioningState": "Succeeded",
        "name": "gatewayip03",
        "etag": "W/\"4e2c63ab-41ee-49da-bb14-aec51bdc44e7\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/gatewayIPCo
nfigurations/gatewayip03"
    }
]
data:    SslCertificateText              : []
data:    FrontendIpConfigurationText     : [
    {
        "privateIPAllocationMethod": "Dynamic",
        "publicIPAddress": {
            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/publicIPAddresses/ipforappgateway3"

        },
        "provisioningState": "Succeeded",
        "name": "frontendip03",
        "etag": "W/\"4e2c63ab-41ee-49da-bb14-aec51bdc44e7\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/frontendIPC
onfigurations/frontendip03"
    }
]
data:    FrontendPortText                : [
    {
        "port": 80,
        "provisioningState": "Succeeded",
        "name": "frontendport03",
        "etag": "W/\"4e2c63ab-41ee-49da-bb14-aec51bdc44e7\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/frontendPor
ts/frontendport03"
    },
    {
        "port": 3380,
        "provisioningState": "Succeeded",
        "name": "frntport3",
        "etag": "W/\"4e2c63ab-41ee-49da-bb14-aec51bdc44e7\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/frontendPor
ts/frntport3"
    }
]
data:    BackendAddressPoolText          : [
    {
        "backendAddresses": [
            {
                "ipAddress": "1.1.1.1"
            },
            {
                "ipAddress": "2.2.2.2"
            },
            {
                "ipAddress": "3.3.3.3"
            }
        ],
        "backendIPConfigurations": [],
        "provisioningState": "Succeeded",
        "name": "pool03",
        "etag": "W/\"4e2c63ab-41ee-49da-bb14-aec51bdc44e7\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/backendAddr
essPools/pool03"
    },
    {
        "backendAddresses": [
            {
                "ipAddress": "4.4.4.4"
            },
            {
                "ipAddress": "5.5.5.5"
            }
        ],
        "backendIPConfigurations": [],
        "provisioningState": "Succeeded",
        "name": "backendpool3",
        "etag": "W/\"4e2c63ab-41ee-49da-bb14-aec51bdc44e7\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/backendAddr
essPools/backendpool3"
    }
]
data:    BackendHttpSettingsText         : [
    {
        "port": 80,
        "protocol": "Http",
        "cookieBasedAffinity": "Disabled",
        "provisioningState": "Succeeded",
        "name": "setting03",
        "etag": "W/\"4e2c63ab-41ee-49da-bb14-aec51bdc44e7\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/backendHttp
SettingsCollection/setting03"
    },
    {
        "port": 3380,
        "protocol": "Http",
        "cookieBasedAffinity": "Disabled",
        "provisioningState": "Succeeded",
        "name": "httpsetting3",
        "etag": "W/\"4e2c63ab-41ee-49da-bb14-aec51bdc44e7\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/backendHttp
SettingsCollection/httpsetting3"
    }
]
data:    HttpListenersText               : [
    {
        "frontendIPConfiguration": {
            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/fronten
dIPConfigurations/frontendip03"
        },
        "frontendPort": {
            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/fronten
dPorts/frontendport03"
        },
        "protocol": "Http",
        "provisioningState": "Succeeded",
        "name": "listener03",
        "etag": "W/\"4e2c63ab-41ee-49da-bb14-aec51bdc44e7\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/httpListene
rs/listener03"
    },
    {
        "frontendIPConfiguration": {
            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/fronten
dIPConfigurations/frontendip03"
        },
        "frontendPort": {
            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/fronten
dPorts/frntport3"
        },
        "protocol": "Http",
        "provisioningState": "Succeeded",
        "name": "httplistener3",
        "etag": "W/\"4e2c63ab-41ee-49da-bb14-aec51bdc44e7\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/httpListene
rs/httplistener3"
    }
]
data:    RequestRoutingRulesText         : [
    {
        "ruleType": "Basic",
        "backendAddressPool": {
            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/backend
AddressPools/pool03"
        },
        "backendHttpSettings": {
            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/backend
HttpSettingsCollection/setting03"
        },
        "httpListener": {
            "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/httpLis
teners/listener03"
        },
        "provisioningState": "Succeeded",
        "name": "rule03",
        "etag": "W/\"4e2c63ab-41ee-49da-bb14-aec51bdc44e7\"",
        "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers/Microsoft.Network/applicationGateways/appgw03/requestRout
ingRules/rule03"
    }
]
data:    Sku                             : {
    "name": "Standard_Small",
    "tier": "Standard",
    "capacity": 5
}
info:    network application-gateway set command OK

</code>
</pre>

**Comment by MikhailTryakhov** [comment]
Duplicates issue https://github.com/MSOpenTech/azure-xplat-cli/issues/534
