### ISSUE TITLE
ARM: network gateway connection create not working

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#527]
![image](https://cloud.githubusercontent.com/assets/11171941/10305032/5db438d6-6c3b-11e5-839c-469b1d7dca1c.png)

**Comment by romangromov** [comment]
@sreekanthbs thanks, should be fixed now

**Comment by sreekanthbs** [comment]
@romangromov yes its working fine now.Thanks
Closing the issue.
