### ISSUE TITLE
Arm: network application-gateway rule add displaying wrong message

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#528]
In network application rule add command i have not given the rule name so that it will prompt for rule name.
But instead it is prompting wrong message i.e Frontend port name
![image](https://cloud.githubusercontent.com/assets/11171941/10305973/5b224f08-6c41-11e5-9b4c-65ff6cb963ef.png)

**Comment by sreekanthbs** [comment]
Same issue with rule remove command

![image](https://cloud.githubusercontent.com/assets/11171941/10306175/d32a18b8-6c42-11e5-95ea-1e09eb463b45.png)

**Comment by MikhailTryakhov** [comment]
@sreekanthbs thank you! It's fixed now!

**Comment by sreekanthbs** [comment]
@MikhailTryakhov  its working fine.Thanks Closing the issue
