### ISSUE TITLE
ARM : network gateway connection list displaying wrong sharedkey

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#529]
I created a gateway connection with shared key -- (abc123)
In show command its displaying it correctly but in list command its displaying wrong shared key.
![image](https://cloud.githubusercontent.com/assets/11171941/10310324/066ee386-6c5f-11e5-9171-b13f694ce2af.png)

**Comment by romangromov** [comment]
@sreekanthbs got it, please attach -vv for list and show

**Comment by sreekanthbs** [comment]
@romangromov please find the verbose output for list and show
<pre>
<code>
<b>verbose output for list</b>
C:\Oct\6oct\azure-xplat-cli-dev-arm-vpn-connections>node bin/azure network gateway connection list armtestrg1 -vv
info:    Executing command network gateway connection list
verbose: Looking up gateway connections
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { user-agent: 'WindowsAzureXplatCLI/0.9.9' },
silly:       url: 'https://management.azure.com/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armtestrg1/providers/Microsoft.Network/connections?a
pi-version=2015-05-01-preview'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-length: '1946',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           x-ms-request-id: '10977730-72a7-4456-8e53-24048612a669',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
silly:           x-ms-ratelimit-remaining-subscription-reads: '14959',
silly:           x-ms-correlation-request-id: '0a84b39d-ee82-4992-b121-7316a1b42735',
silly:           x-ms-routing-request-id: 'SOUTHEASTASIA:20151006T141755Z:0a84b39d-ee82-4992-b121-7316a1b42735',
silly:           date: 'Tue, 06 Oct 2015 14:17:55 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '{\015\n  "value": [\015\n    {\015\n      "name": "connVnet1ToVnet2",\015\n      "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resour
ceGroups/armtestrg1/providers/Microsoft.Network/connections/connVnet1ToVnet2",\015\n      "etag": "W/\\"1f7aaf83-b14a-4627-bce0-b0520c412de3\\"",\015\n      "type": "
Microsoft.Network/connections",\015\n      "location": "eastus",\015\n      "properties": {\015\n        "provisioningState": "Succeeded",\015\n        "resourceGuid"
: "3ebfc5ae-1887-46e9-9fc2-dc7c6e004fbe",\015\n        "virtualNetworkGateway1": {\015\n          "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceG
roups/armtestrg1/providers/Microsoft.Network/virtualNetworkGateways/gateway1"\015\n        },\015\n        "localNetworkGateway2": {\015\n          "id": "/subscripti
ons/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armtestrg1/providers/Microsoft.Network/localNetworkGateways/localntwrk2"\015\n        },\015\n        "connect
ionType": "IPsec",\015\n        "routingWeight": 0,\015\n        "sharedKey": "3082019006092A864886F70D010703A08201813082017D0201003182014930820145020100302D301931173
0150603550403130E6E72702D656E6372797074696F6E021078A0163F01050D9647F47ED7EF267DBC300D06092A864886F70D010101050004820100972E20CEE9FDB8174D88004642C096872ED9E5BEFB92A49
774D5F4A16103BF6E62011811376D4BD5E5988AF7BDB938C0EF2A160E112761A5D02C54F309952ED48F62324AFCF075F4AEC42704F214AD5AAE915DBA05031D4E4CE64EA4BB62EB3B77D6963DDF77A6722F928
07708B48F2DFB005A11A4A3BAF65F030B45B2E3594940084FBDEAAAF64EF54873EB25E7EB02014C5378FCD4D2963B74366B1B17A622D1B9A3B33432044DED15D5BA9664BFBF74432E62A471287B6879C04CE1D
BE9ED6629BDB4456397F13116A2DD8456854BAA8FF94A156C5762DC75C8F78C052E7DE1BE48EE2E654DD6027FB3E927FF953B2CA47A2884086ECD87739E47A62709DC302B06092A864886F70D0107013014060
82A864886F70D030704081FE23EF170BADB2F80082A2E8D524FC14CDF",\015\n        "connectionStatus": "Unknown",\015\n        "ingressBytesTransferred": 0,\015\n        "egres
sBytesTransferred": 0\015\n      }\015\n    }\015\n  ],\015\n  "nextLink": ""\015\n}'
silly:   }
silly:   [
silly:       {
silly:           tags: {},
silly:           virtualNetworkGateway1: {
silly:               ipConfigurations: [],
silly:               tags: {},
silly:               id: '/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armtestrg1/providers/Microsoft.Network/virtualNetworkGateways/gateway1'
silly:           },
silly:           localNetworkGateway2: {
silly:               tags: {},
silly:               id: '/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armtestrg1/providers/Microsoft.Network/localNetworkGateways/localntwrk2'
silly:           },
silly:           connectionType: 'IPsec',
silly:           routingWeight: 0,
silly:           sharedKey: '3082019006092A864886F70D010703A08201813082017D0201003182014930820145020100302D3019311730150603550403130E6E72702D656E6372797074696F6E02107
8A0163F01050D9647F47ED7EF267DBC300D06092A864886F70D010101050004820100972E20CEE9FDB8174D88004642C096872ED9E5BEFB92A49774D5F4A16103BF6E62011811376D4BD5E5988AF7BDB938C0E
F2A160E112761A5D02C54F309952ED48F62324AFCF075F4AEC42704F214AD5AAE915DBA05031D4E4CE64EA4BB62EB3B77D6963DDF77A6722F92807708B48F2DFB005A11A4A3BAF65F030B45B2E3594940084FB
DEAAAF64EF54873EB25E7EB02014C5378FCD4D2963B74366B1B17A622D1B9A3B33432044DED15D5BA9664BFBF74432E62A471287B6879C04CE1DBE9ED6629BDB4456397F13116A2DD8456854BAA8FF94A156C5
762DC75C8F78C052E7DE1BE48EE2E654DD6027FB3E927FF953B2CA47A2884086ECD87739E47A62709DC302B06092A864886F70D010701301406082A864886F70D030704081FE23EF170BADB2F80082A2E8D524
FC14CDF',
silly:           resourceGuid: '3ebfc5ae-1887-46e9-9fc2-dc7c6e004fbe',
silly:           provisioningState: 'Succeeded',
silly:           etag: 'W/"1f7aaf83-b14a-4627-bce0-b0520c412de3"',
silly:           id: '/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armtestrg1/providers/Microsoft.Network/connections/connVnet1ToVnet2',
silly:           name: 'connVnet1ToVnet2',
silly:           type: 'Microsoft.Network/connections',
silly:           location: 'eastus'
silly:       }
silly:   ]
data:    Name              Location  Type   Routing weight  Virtual network gateway  Connected entity
data:    ----------------  --------  -----  --------------  -----------------------  ----------------
data:    connVnet1ToVnet2  eastus    IPsec  0               gateway1                 localntwrk2
info:    network gateway connection list command OK

<b>verbose output for show</b>

C:\Oct\6oct\azure-xplat-cli-dev-arm-vpn-connections>node bin/azure network gateway connection show armtestrg1 connVnet1ToVnet2 -vv
info:    Executing command network gateway connection show
verbose: Looking up gateway connection "connVnet1ToVnet2"
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { Content-Type: 'application/json', user-agent: 'WindowsAzureXplatCLI/0.9.9' },
silly:       url: 'https://management.azure.com/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armtestrg1/providers/Microsoft.Network/connections/c
onnVnet1ToVnet2?api-version=2015-05-01-preview'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 200,
silly:       header: {
silly:           cache-control: 'no-cache',
silly:           pragma: 'no-cache',
silly:           content-length: '931',
silly:           content-type: 'application/json; charset=utf-8',
silly:           expires: '-1',
silly:           x-ms-request-id: 'c9fd088b-1eaa-47c4-a5a2-a3fd8b774f65',
silly:           strict-transport-security: 'max-age=31536000; includeSubDomains',
silly:           server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
silly:           x-ms-ratelimit-remaining-subscription-reads: '14931',
silly:           x-ms-correlation-request-id: '313e963e-e6fa-495a-a7e0-3ea30bb5c315',
silly:           x-ms-routing-request-id: 'SOUTHEASTASIA:20151006T142018Z:313e963e-e6fa-495a-a7e0-3ea30bb5c315',
silly:           date: 'Tue, 06 Oct 2015 14:20:18 GMT',
silly:           connection: 'close'
silly:       },
silly:       body: '{\015\n  "name": "connVnet1ToVnet2",\015\n  "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armtestrg1/providers/Microso
ft.Network/connections/connVnet1ToVnet2",\015\n  "type": "Microsoft.Network/connections",\015\n  "properties": {\015\n    "provisioningState": "Succeeded",\015\n    "
resourceGuid": "5c11b198-5fd0-46a8-9f4b-3631755466cf",\015\n    "virtualNetworkGateway1": {\015\n      "id": "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/reso
urceGroups/armtestrg1/providers/Microsoft.Network/virtualNetworkGateways/gateway1"\015\n    },\015\n    "localNetworkGateway2": {\015\n      "id": "/subscriptions/bfb
5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armtestrg1/providers/Microsoft.Network/localNetworkGateways/localntwrk2"\015\n    },\015\n    "connectionType": "IPse
c",\015\n    "routingWeight": 0,\015\n    "sharedKey": "abc123",\015\n    "connectionStatus": "NotConnected",\015\n    "ingressBytesTransferred": 0,\015\n    "egressB
ytesTransferred": 0\015\n  }\015\n}'
silly:   }
silly:   {
silly:       tags: {},
silly:       virtualNetworkGateway1: {
silly:           ipConfigurations: [],
silly:           tags: {},
silly:           id: '/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armtestrg1/providers/Microsoft.Network/virtualNetworkGateways/gateway1'
silly:       },
silly:       localNetworkGateway2: {
silly:           tags: {},
silly:           id: '/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armtestrg1/providers/Microsoft.Network/localNetworkGateways/localntwrk2'
silly:       },
silly:       connectionType: 'IPsec',
silly:       routingWeight: 0,
silly:       sharedKey: 'abc123',
silly:       resourceGuid: '5c11b198-5fd0-46a8-9f4b-3631755466cf',
silly:       provisioningState: 'Succeeded',
silly:       id: '/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armtestrg1/providers/Microsoft.Network/connections/connVnet1ToVnet2',
silly:       name: 'connVnet1ToVnet2',
silly:       type: 'Microsoft.Network/connections'
silly:   }
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armtestrg1/providers/Microsoft.Network/connections/connV
net1ToVnet2
data:    Name                            : connVnet1ToVnet2
data:    Type                            : Microsoft.Network/connections
data:    Provisioning state              : Succeeded
data:    Connection type                 : IPsec
data:    Routing weight                  : 0
data:    Virtual network gateway 1       : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armtestrg1/providers/Microsoft.Network/virtualNetworkGat
eways/gateway1
data:    Local network gateway 2         : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armtestrg1/providers/Microsoft.Network/localNetworkGatew
ays/localntwrk2
info:    network gateway connection show command OK

</code>
</pre>

**Comment by romangromov** [comment]
@sreekanthbs this is by design:

`[Manjusha] Secret key is a secret and we want to show it in specific get. In List connections we don’t want to show the shared key, so we show the encrypted shared key. Only when you get specific connection you get to see its secret.`

Hence please close this issue

**Comment by sreekanthbs** [comment]
@romangromov Thanks for the info.Closing the issue.
