### ISSUE TITLE
ARM:network application-gateway ip-config set not working

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#530]
<pre>
<code>
C:\Oct\9oct\azure-xplat-cli-dev-arm-app-gateways>node bin/azure network application-gateway ip-config set  test-trya-group3 appgw03 -n ipconfig3 -e vnet32 -u subnet32

info:    Executing command network application-gateway ip-config set
+ Looking up an Application Gateway "appgw03"
error:   An application gateway ip config with name "ipconfig3" not found in Application Gateway "appgw03"
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network application-gateway ip-config set command failed

</code>
</pre>

**Comment by MikhailTryakhov** [comment]
Hi @sreekanthbs 
are you sure that ip-config with name 'ipconfig3' really exists in specified gateway?

**Comment by sreekanthbs** [comment]
@MikhailTryakhov  there is no command to add ip-config ,so yes this ip-config 'ipconfig3'does not exist in speciifed gateway.Is there a way to add this ip-config to gateway?

**Comment by MikhailTryakhov** [comment]
@sreekanthbs correct, there are no add/remove commands because of only one gateway ip config should exists (not 0, not 2, but 1) and it is created with application gateway. The only chance to work with app gateway is setting some parameters of configuration.

**Comment by sreekanthbs** [comment]
@MikhailTryakhov got it.Thanks for the clarification. I try to set some configuration on an existing ip-config still getting some error.
<pre>
<code>
C:\Oct\9oct\azure-xplat-cli-dev-arm-app-gateways>node bin/azure network application-gateway ip-config set  test-trya-group3 appgw03 -n gatewayip03 -e vnet32 -u subnet
32
info:    Executing command network application-gateway ip-config set
+ Looking up an Application Gateway "appgw03"
+ Looking up the subnet "subnet32"
+ Setting configuration for an Application Gateway "appgw03"
error:   output is not defined
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network application-gateway ip-config set command failed


C:\Oct\9oct\azure-xplat-cli-dev-arm-app-gateways>node bin/azure network application-gateway ip-config set  test-trya-group3 appgw03 -n gatewayip03 -e vnet32 -u subnet
32
info:    Executing command network application-gateway ip-config set
+ Looking up an Application Gateway "appgw03"
+ Looking up the subnet "subnet32"
error:   Current gateway ip config already has the same subnet with Id: "/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/test-trya-group3/providers
/Microsoft.Network/virtualNetworks/vnet32/subnets/subnet32"
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network application-gateway ip-config set command failed
</code>
</pre>

**Comment by MikhailTryakhov** [comment]
Duplicates issue https://github.com/MSOpenTech/azure-xplat-cli/issues/534
