### ISSUE TITLE
ARM : network express-route authorization set displaying different option 

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#531]
![image](https://cloud.githubusercontent.com/assets/11171941/10447354/66b86540-71a1-11e5-987e-3cf9a647df09.png)

**Comment by MikhailTryakhov** [comment]
@sreekanthbs thank you!
Please review latest updates - it's fixed now

**Comment by sreekanthbs** [comment]
@MikhailTryakhov  its working fine now.Thanks.
Closing the issue.
