### ISSUE TITLE
ARM : network express-route authorization create always creating authorization with use state as Available

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#532]
<pre>
<code>
C:\Oct\13oct\azure-xplat-cli-dev-arm-express-route-auth>node bin/azure network express-route authorization create armresgrp12o expressroute1 exproutauth5 -k ABC@123<b> -
u Used</b>
info:    Executing command network express-route authorization create
+ Looking up the express route circuit "expressroute1"
+ Looking up the express route circuit authorization "expressroute1"
+ Creating express route circuit authorization "expressroute1"
+ Looking up the express route circuit authorization "expressroute1"
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp12o/providers/Microsoft.Network/expressRouteCir
cuits/expressroute1/authorizations/exproutauth5
data:    Name                            : exproutauth5
data:    Type                            : Microsoft.Network/expressRouteCircuits/authorizations
data:    Use state                     <b>  : Available </b>
data:    Authorization Key               : e3b81fa4-48e2-44ed-b172-35beed302b6c
data:    Provisioning state              : Succeeded
info:    network express-route authorization create command OK

</code>
</pre>

**Comment by sreekanthbs** [comment]
Same issue in set 
<pre>
<code>
C:\Oct\13oct\azure-xplat-cli-dev-arm-express-route-auth>node bin/azure network express-route authorization set armresgrp12o expressroute1 exproutauth5 -k ABC@123 -u U
sed
info:    Executing command network express-route authorization set
+ Looking up the express route circuit "expressroute1"
+ Looking up the express route circuit authorization "expressroute1"
+ Setting express route circuit authorization "expressroute1"
+ Looking up the express route circuit authorization "expressroute1"
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp12o/providers/Microsoft.Network/expressRouteCir
cuits/expressroute1/authorizations/exproutauth5
data:    Name                            : exproutauth5
data:    Type                            : Microsoft.Network/expressRouteCircuits/authorizations
data:    Use state                       : Available
data:    Authorization Key               : e3b81fa4-48e2-44ed-b172-35beed302b6c
data:    Provisioning state              : Succeeded
info:    network express-route authorization set command OK
</code>
</pre>

**Comment by romangromov** [comment]
@sreekanthbs is this blocking issue for all of `authorization` commands stack?

**Comment by romangromov** [comment]
@MikhailTryakhov since it marked as `external`, do we have any updates from Amit?

**Comment by MikhailTryakhov** [comment]
@romangromov  he wrote that's external bug and they need 1-2 weeks to test environment

**Comment by sreekanthbs** [comment]
@romangromov  no its not a blocking issue.But the verification cannot be completed till we can verify the create & set command with both state - Used & Available.

**Comment by romangromov** [comment]
[Amit] `authorization will be available in next week’s deployment. It can be part of CLI’s next release cycle.`

please do not forget to ping him again

**Comment by MikhailTryakhov** [comment]
Amit told exlude it from create/set commands
