### ISSUE TITLE
ARM : network application-gateway set command non-regular error

### ISSUE THREAD

**Issue by MikhailTryakhov** [MSOpenTech/azure-xplat-cli#534]
There is non-regular error setting application gateway.
```
C:\Oct\9oct\azure-xplat-cli-dev-arm-app-gateways>node bin/azure network application-gateway set test-trya-group3 appgw03   -l Standard_Small -z 5
info:    Executing command network application-gateway set
+ Looking up an Application Gateway "appgw03"
info:    Application gateway set command is a long-running process. It may take up to 15-20 minutes to complete.
+ Setting configuration for an Application Gateway "appgw03"
error:   output is not defined
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network application-gateway set command failed
```

**Comment by romangromov** [comment]
@MikhailTryakhov `Application gateway set command is a long-running process` - this should be warn instead of info

**Comment by romangromov** [comment]
@MikhailTryakhov about error message: `output is not defined` - this is JS runtime error, not server response. Why this is marked as `external`?

**Comment by MikhailTryakhov** [comment]
@romangromov it throws after request sent during long-running operation...

**Comment by romangromov** [comment]
@MikhailTryakhov can you please attach server response and stack trace for more details?

**Comment by MikhailTryakhov** [comment]
@romangromov  unfortunately I can't reproduce it. I'll ask Sreekanth to test such tasks

**Comment by romangromov** [comment]
@sreekanthbs we need two things: 1) last response from server (-vv) 2) stack trace from azure.err

**Comment by MikhailTryakhov** [comment]
@romangromov you were right - I've fixed it. Thank you!

**Comment by romangromov** [comment]
@sreekanthbs please confirm we are good here, as well as https://github.com/MSOpenTech/azure-xplat-cli/issues/525 https://github.com/MSOpenTech/azure-xplat-cli/issues/523 https://github.com/MSOpenTech/azure-xplat-cli/issues/530 . Otherwise, re-open

**Comment by sreekanthbs** [comment]
@MikhailTryakhov  @romangromov  i verified all 3 issues mentioned above .All are working fine.Not able to repro these issues.
