### ISSUE TITLE
Arm: network application-gateway create giving error even though the app-gateway gets created

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#536]
This error is regular. I run the create application-gateway create command twice both time got same error.
![image](https://cloud.githubusercontent.com/assets/11171941/10724712/9646c734-7bec-11e5-9988-782c9d7b8e43.png)

**Comment by sreekanthbs** [comment]
@MikhailTryakhov this issue is in other commands as well.
![image](https://cloud.githubusercontent.com/assets/11171941/10731209/4ba4c28e-7c1a-11e5-8518-b23ec7fccf42.png)
![image](https://cloud.githubusercontent.com/assets/11171941/10731561/00d82276-7c1c-11e5-9699-65f8255d9fa1.png)
![image](https://cloud.githubusercontent.com/assets/11171941/10731571/110543cc-7c1c-11e5-915d-da31604d1b11.png)

**Comment by squillace** [comment]
@sreekanthbs @MikhailTryakhov @romangromov is ARM support for app gateway coming out publicly any time soon? What is the timeline for this feature in the cli?

**Comment by MikhailTryakhov** [comment]
@squillace we have two latest issues on SDK side and I hope that guys from their side would help us resolve it ASAP

**Comment by squillace** [comment]
Is any pushing needed on sdk side? Just let me know...
