### ISSUE TITLE
ARM: network dns zone record-set list --json  not displaying NS/SOA types properly

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#537]
network dns zone record-set list --json not displaying type of dnszones for NS type and SOA
![image](https://cloud.githubusercontent.com/assets/11171941/10727853/077e30d4-7c03-11e5-8600-72568b1b5cdb.png)

![image](https://cloud.githubusercontent.com/assets/11171941/10728119/4056642e-7c05-11e5-86b9-6879144b0811.png)

![image](https://cloud.githubusercontent.com/assets/11171941/10728082/e7986184-7c04-11e5-8ea0-344fcb2cad43.png)

**Comment by romangromov** [comment]
Attaching http req/res https://gist.github.com/romangromov/d39150d1e7dd42cd9c2a#file-zone-list-type-issue

**Comment by romangromov** [comment]
UPD: [Jonathan] `Re record set LIST giving the wrong type for NS/SOA records—yes, this is a known issue, we will fix this.  `

**Comment by romangromov** [comment]
UPD: still exist
