### ISSUE TITLE
ARM: network traffic-manager profile create with --json option with warn message error

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#542]
ARM network traffic-manager profile create with --json option giving a warn message as ''Using default location: global" and then json output is getting displayed. Because of this traffic-manager test cases are failing.
![image](https://cloud.githubusercontent.com/assets/11171941/11117086/edc17810-895c-11e5-9370-ad3c947da694.png)

Make sure json output should not display any warnings

**Comment by romangromov** [comment]
@sreekanthbs warning removed, should work fine now

**Comment by sreekanthbs** [comment]
@romangromov It is working fine now, hence closing the issue.
