### ISSUE TITLE
ARM: network express-route peering create, show not displaying Azure ASN property

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#550]
ARM network express-route peering create and show not displaying Azure ASN property while network express-route peering show --json output showing the property. Make consistency across --json output and normal output display. verified in the branch arm-express-route-peering
![image](https://cloud.githubusercontent.com/assets/11171941/11234507/9365dd70-8dee-11e5-9baf-a4fdcbeee932.png)

**Comment by MikhailTryakhov** [comment]
Thank you @sreekanthbs - it's fixed now

**Comment by sreekanthbs** [comment]
@MikhailTryakhov yes its working fine now.Thanks.Closing the issue

<pre>
<code>
C:\Nov\19Nov\azure-xplat-cli-dev-arm-express-route-peering>node bin/azure network express-route peering show armresgrp18n expressroute1 MicrosoftPeering
info:    Executing command network express-route peering show
+ Looking up the express route circuit "expressroute1" peering "MicrosoftPeering"
data:    Name                            : MicrosoftPeering
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp18n/providers/Microsoft.Network/expressRouteCir
cuits/expressroute1/peerings/MicrosoftPeering
data:    Type                            : Microsoft.Network/expressRouteCircuits/peerings
data:    etag                            : W/"8af6f317-051e-4782-ad3c-f16410a30031"
data:    Properties:
data:      Provisioning State            : Succeeded
data:      Peering Type                  : MicrosoftPeering
data:      Peer ASN                      : 100
data:      Primary Peer Address Prefix   : 192.168.1.0/30
data:      Secondary Peer Address Prefix : 192.168.2.0/30
data:      Primary Azure Port            : VZ-SYD-06GMR-CIS-1-PRI-A
data:      Secondary Azure Port          : VZ-SYD-06GMR-CIS-2-SEC-A
data:      State                         : Enabled
data:      Azure ASN                     : 12076
data:      Vlan Id                       : 200
data:      Microsoft Peering Config:
data:        Advertised Public Prefixes:
data:          11.2.3.4/30
data:          12.2.3.4/30
data:        Advertised Public Prefix State: ValidationNeeded
data:        Customer Asn                : 0
data:        Routing Registry Name       : ARIN
info:    network express-route peering show command OK



C:\Nov\19Nov\azure-xplat-cli-dev-arm-express-route-peering>node bin/azure network express-route peering create armresgrp18n expressroute1 AzurePublicPeering --vlan-id
 550 --peer-asn 65000  --primary-address-prefix 176.16.3.0/30 --secondary-address-prefix 176.16.4.0/30 -y AzurePublicPeering
info:    Executing command network express-route peering create
+ Looking up the express route circuit "expressroute1"
+ Looking up the express route circuit "expressroute1" peering "AzurePublicPeering"
+ Creating express route peering "AzurePublicPeering" in circuit "expressroute1"
+ Looking up the express route circuit "expressroute1" peering "AzurePublicPeering"
data:    Name                            : AzurePublicPeering
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp18n/providers/Microsoft.Network/expressRouteCir
cuits/expressroute1/peerings/AzurePublicPeering
data:    Type                            : Microsoft.Network/expressRouteCircuits/peerings
data:    etag                            : W/"93469d3a-566b-41de-9b3a-685839d21a96"
data:    Properties:
data:      Provisioning State            : Succeeded
data:      Peering Type                  : AzurePublicPeering
data:      Peer ASN                      : 65000
data:      Primary Peer Address Prefix   : 176.16.3.0/30
data:      Secondary Peer Address Prefix : 176.16.4.0/30
data:      Primary Azure Port            : VZ-SYD-06GMR-CIS-1-PRI-A
data:      Secondary Azure Port          : VZ-SYD-06GMR-CIS-2-SEC-A
data:      State                         : Enabled
data:      Azure ASN                     : 12076
data:      Vlan Id                       : 550
info:    network express-route peering create command OK
C:\Nov\19Nov\azure-xplat-cli-dev-arm-express-route-peering>node bin/azure network express-route peering show armresgrp18n expressroute1 AzurePublicPeering
info:    Executing command network express-route peering show
+ Looking up the express route circuit "expressroute1" peering "AzurePublicPeering"
data:    Name                            : AzurePublicPeering
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrp18n/providers/Microsoft.Network/expressRouteCir
cuits/expressroute1/peerings/AzurePublicPeering
data:    Type                            : Microsoft.Network/expressRouteCircuits/peerings
data:    etag                            : W/"93469d3a-566b-41de-9b3a-685839d21a96"
data:    Properties:
data:      Provisioning State            : Succeeded
data:      Peering Type                  : AzurePublicPeering
data:      Peer ASN                      : 65000
data:      Primary Peer Address Prefix   : 176.16.3.0/30
data:      Secondary Peer Address Prefix : 176.16.4.0/30
data:      Primary Azure Port            : VZ-SYD-06GMR-CIS-1-PRI-A
data:      Secondary Azure Port          : VZ-SYD-06GMR-CIS-2-SEC-A
data:      State                         : Enabled
data:      Azure ASN                     : 12076
data:      Vlan Id                       : 550
info:    network express-route peering show command OK
</code>
</pre>
