### ISSUE TITLE
ARM : network express-route peering create have duplicate short name options

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#551]
ARM network express-route peering create have duplicate short name -i option.
![image](https://cloud.githubusercontent.com/assets/11171941/11234581/630ea1b0-8def-11e5-8198-e768c92f1e62.png)

**Comment by MikhailTryakhov** [comment]
Thank you @sreekanthbs - it's fixed now

**Comment by sreekanthbs** [comment]
@MikhailTryakhov

**Comment by MikhailTryakhov** [comment]
Thank you! I've reworked all short commands in create and set commands. Should be fixed

**Comment by sreekanthbs** [comment]
@MikhailTryakhov yes now its fixed.Thanks Closing the issue
