### ISSUE TITLE
ARM: network express-route peering create and set with Disabled state not working

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#552]
ARM network express-route peering create and set with disabled state not able to update the state as Disabled. Sometimes set operation ProvisioningState as Failed

![image](https://cloud.githubusercontent.com/assets/11171941/11236530/60652b94-8e00-11e5-9fdf-2657c72566b9.png)

![image](https://cloud.githubusercontent.com/assets/11171941/11236591/bc21cba4-8e00-11e5-92aa-e99f7b3ab62d.png)

![image](https://cloud.githubusercontent.com/assets/11171941/11237104/bd145ce0-8e03-11e5-853f-b42d66e5faa8.png)

Sometime ProvisioningState failed for peer create
![image](https://cloud.githubusercontent.com/assets/11171941/11239696/9521b47a-8e13-11e5-966d-bc916caa89cf.png)

**Comment by sreekanthbs** [comment]
Same issue with  --azure-asn . Create & set are not working ,its taking default value only
![image](https://cloud.githubusercontent.com/assets/11171941/11238021/05c6d2f6-8e09-11e5-8234-cc80d5c8aa8a.png)

**Comment by MikhailTryakhov** [comment]
Duplicates https://github.com/MSOpenTech/azure-xplat-cli/issues/584
