### ISSUE TITLE
ARM : network express-route peering set not working

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#553]
ARM network express-route peering set of MicrosoftPeering type is giving error
![image](https://cloud.githubusercontent.com/assets/11171941/11237437/e5af2a02-8e05-11e5-82f5-f2c643cecd06.png)

**Comment by MikhailTryakhov** [comment]
Hi @sreekanthbs please review it again - I assume THIS issue s fixed (duplicating with Disabled State)

**Comment by sreekanthbs** [comment]
@MikhailTryakhov Still issue exists. This is not Disabled state, Set operation for MicrosoftPeering type is giving error.
![image](https://cloud.githubusercontent.com/assets/11171941/11331952/3ebb5cda-91e7-11e5-8f71-0c3e4d663a8e.png)

**Comment by MikhailTryakhov** [comment]
It doesn't work at all
![show](https://cloud.githubusercontent.com/assets/3079588/11362504/1952dfd6-92a5-11e5-964e-7f9fa29ca35b.png)
throws error setting without any new options
![set error](https://cloud.githubusercontent.com/assets/3079588/11362519/2b6c446e-92a5-11e5-8282-3c61a327297d.png)

**Comment by romangromov** [comment]
@MikhailTryakhov did you investigate -vv ?

**Comment by MikhailTryakhov** [comment]
@romangromov details are empty
[setError.txt](https://github.com/MSOpenTech/azure-xplat-cli/files/42596/setError.txt)

**Comment by MikhailTryakhov** [comment]
Issue still exists
