### ISSUE TITLE
ARM: network express-route peering set help missing ms-advertised-public-prefix-state options

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#556]
network express-route peering set help command missing options available for the  --ms-advertised-public-prefix-state option. It is showing as %s as compared to create help command.
![image](https://cloud.githubusercontent.com/assets/11171941/11332872/30179b5a-91ef-11e5-90df-64d7561d6c02.png)

In create help command showing proper available options
![image](https://cloud.githubusercontent.com/assets/11171941/11332884/5b637bd0-91ef-11e5-9c7f-8d59f9357420.png)

**Comment by MikhailTryakhov** [comment]
Thank you @sreekanthbs, it's fixed now

**Comment by sreekanthbs** [comment]
@MikhailTryakhov yes its fixed.Thanks
![image](https://cloud.githubusercontent.com/assets/11171941/11362023/2abaa198-92b7-11e5-84ae-85fb7af7843b.png)
