### ISSUE TITLE
ARM: network express-route peering create can't work with Disabled state

### ISSUE THREAD

**Issue by MikhailTryakhov** [MSOpenTech/azure-xplat-cli#557]
Problems trying create peering with Disabled state - it is created with Enabled state.

![w9qgilt](https://cloud.githubusercontent.com/assets/3079588/11361950/c27fb3ee-92a1-11e5-9072-883fb24c08b4.png)

**Comment by MikhailTryakhov** [comment]
excluded state option

**Comment by romangromov** [comment]
@MikhailTryakhov why this closed?

From API docs:
`@param {string} [peeringParameters.state] Gets or sets state of Peering`

Do we have confirmation from AppGateways team about excluding `state` parameter from CLI?
