### ISSUE TITLE
ARM : network application-gateway commands are very long running

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#560]
Most of the app-gateway commands run for 20 or more minutes.
Even after one command complete we need to wait for 10-15 mins before running another command otherwise error comes - Another operation on this resource is in progress.

![app-gatewayissue tmp](https://cloud.githubusercontent.com/assets/11171941/10849775/5167651a-7f48-11e5-8c57-8a5ad73a95f8.PNG)

**Comment by bingosummer** [comment]
Hi @romangromov 
Would the next release (0.9.14) support Application Gateway (ARM mode) with health probes?
Thanks.

**Comment by romangromov** [comment]
+ @MikhailTryakhov who owns App Gateways commands in Xplat-CLI to answer this question
