### ISSUE TITLE
Swagger: ARM network nic create is failing

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#561]
In Swagger repo ARM network nic create is giving error
![image](https://cloud.githubusercontent.com/assets/11171941/11972353/175628b8-a971-11e5-9569-ea82f00e7fc1.png)

**Comment by romangromov** [comment]
@sreekanthbs fixed, debug output removed

**Comment by sreekanthbs** [comment]
@romangromov It is working fine now, hence closing the issue.
<pre>
<code>
C:\Dec2015\23Dec\azure-xplat-cli-swagger-networking>node bin/azure network nic create armresgrpswagger tryaNic1 westus -k subnet1 -m vnet1 -p pubIp2 -t tag1=val
1;tag2=val2
info:    Executing command network nic create
+ Looking up the subnet "subnet1"
+ Looking up the public ip "pubIp2"
+ Looking up the network interface "tryaNic1"
+ Creating network interface "tryaNic1"
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrpswagger/providers/Microsoft.Network/netwo
rkInterfaces/tryaNic1
data:    Name                            : tryaNic1
data:    Type                            : Microsoft.Network/networkInterfaces
data:    Location                        : westus
data:    Provisioning state              : Succeeded
data:    Tags                            : tag1=val1;tag2=val2
data:    Enable IP forwarding            : false
data:    IP configurations:
data:      Name                          : Nic-IP-config
data:      Provisioning state            : Succeeded
data:      Private IP address            : 10.0.0.5
data:      Private IP allocation method  : Dynamic
data:      Subnet                        : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrpswagger/providers/Microsoft.Network/virtu
alNetworks/vnet1/subnets/subnet1
data:
info:    network nic create command OK
</code>
</pre>
