### ISSUE TITLE
Swagger: ARM network lb frontend-ip create with -u, --public-ip-id option is failing

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#562]
![image](https://cloud.githubusercontent.com/assets/11171941/11973962/9526ae20-a985-11e5-9a06-f6045288bbb6.png)

**Comment by sreekanthbs** [comment]
Even with  -b, --subnet-id <subnet-id> option also not working
<pre>
<code>
C:\Dec2015\23Dec\azure-xplat-cli-swagger-networking>node bin/azure network lb frontend-ip create armresgrpswagger tryaLb2 tryaFrontendIp2 -b /subscriptions/bfb5
e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrpswagger/providers/Microsoft.Network/virtualNetworks/vnet1/subnets/subnet1
info:    Executing command network lb frontend-ip create
error:   You must specify --public-ip-name or --subnet-name, --subnet-vnet-name
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
error:   network lb frontend-ip create command failed
</code>
</pre>

**Comment by romangromov** [comment]
@sreekanthbs both cases should be good now

**Comment by sreekanthbs** [comment]
@romangromov It is working fine now with both options. 
with -b,  --subnet-id 
<pre>
<code>
C:\Dec2015\23Dec_2\azure-xplat-cli-swagger-networking>node bin/azure network lb frontend-ip create armresgrpswagger tryaLb3 tryaFrontendIp3 -b /subscriptions/bf
b5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrpswagger/providers/Microsoft.Network/virtualNetworks/vnet3/subnets/subnet3
info:    Executing command network lb frontend-ip create
+ Looking up the load balancer "tryaLb3"
{"name":"tryaFrontendIp3","privateIPAllocationMethod":"Dynamic","subnet":{"id":"/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrpswag
ger/providers/Microsoft.Network/virtualNetworks/vnet3/subnets/subnet3"}}
+ Updating load balancer "tryaLb3"
data:    Name                            : tryaFrontendIp3
data:    Provisioning state              : Succeeded
data:    Private IP allocation method    : Dynamic
data:    Private IP address              : 10.0.0.4
data:    Subnet id                       : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrpswagger/providers/Microsoft.Network/virtu
alNetworks/vnet3/subnets/subnet3
info:    network lb frontend-ip create command OK
</code>
</pre>
with option -u, --public-ip-id
<pre>
<code>
C:\Dec2015\23Dec_2\azure-xplat-cli-swagger-networking>node bin/azure network lb frontend-ip set armresgrpswagger tryaLb3 tryaFrontendIp3 -u /subscriptions/bfb5e
0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrpswagger/providers/Microsoft.Network/publicIPAddresses/pubIp3
info:    Executing command network lb frontend-ip set
+ Looking up the load balancer "tryaLb3"
{"id":"/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrpswagger/providers/Microsoft.Network/loadBalancers/tryaLb3/frontendIPConfigura
tions/tryaFrontendIp3","name":"tryaFrontendIp3","etag":"W/\"6ab25449-6899-4980-ae48-8b050e1c6f0f\"","privateIPAddress":"10.0.0.4","privateIPAllocationMethod":"D
ynamic","provisioningState":"Succeeded","publicIPAddress":{"id":"/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrpswagger/providers/M
icrosoft.Network/publicIPAddresses/pubIp3"}}
+ Updating load balancer "tryaLb3"
data:    Name                            : tryaFrontendIp3
data:    Provisioning state              : Succeeded
data:    Private IP allocation method    : Dynamic
data:    Public IP address id            : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrpswagger/providers/Microsoft.Network/publi
cIPAddresses/pubIp3
info:    network lb frontend-ip set command OK
C:\Dec2015\23Dec_2\azure-xplat-cli-swagger-networking>node bin/azure network lb frontend-ip create armresgrpswagger tryaLb3 tryaFrontendIp4 -u  /subscriptions/b
fb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrpswagger/providers/Microsoft.Network/publicIPAddresses/pubIp4
info:    Executing command network lb frontend-ip create
+ Looking up the load balancer "tryaLb3"
{"name":"tryaFrontendIp4","privateIPAllocationMethod":"Dynamic","publicIPAddress":{"id":"/subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armr
esgrpswagger/providers/Microsoft.Network/publicIPAddresses/pubIp4"}}
+ Updating load balancer "tryaLb3"
data:    Name                            : tryaFrontendIp4
data:    Provisioning state              : Succeeded
data:    Private IP allocation method    : Dynamic
data:    Public IP address id            : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrpswagger/providers/Microsoft.Network/publi
cIPAddresses/pubIp4
info:    network lb frontend-ip create command OK
</code>
</pre>
