### ISSUE TITLE
Swagger: ARM network lb inbound-nat-rule create have duplicate short name -i

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#563]
![image](https://cloud.githubusercontent.com/assets/11171941/11975186/2395c0b4-a991-11e5-9d57-d43cc4397dd3.png)

**Comment by romangromov** [comment]
@sreekanthbs fixed

**Comment by sreekanthbs** [comment]
@romangromov It is working fine now.
<pre>
<code>
C:\Dec2015\23Dec_2\azure-xplat-cli-swagger-networking>node bin/azure network lb inbound-nat-rule create armresgrpswagger tryaLb1 tryaNatrule3 -p tcp -f 88 -b 91
 -i 4 -t tryaFrontendIp2
info:    Executing command network lb inbound-nat-rule create
+ Looking up the load balancer "tryaLb1"
warn:    Using default enable floating ip: false
+ Updating load balancer "tryaLb1"
data:    Name                            : tryaNatrule3
data:    Provisioning state              : Succeeded
data:    Protocol                        : Tcp
data:    Frontend port                   : 88
data:    Backend port                    : 91
data:    Enable floating IP              : false
data:    Idle timeout in minutes         : 4
data:    Frontend IP configuration id    : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrpswagger/providers/Microsoft.Network/loadB
alancers/tryaLb1/frontendIPConfigurations/tryaFrontendIp2
info:    network lb inbound-nat-rule create command OK
</code>
</pre>
