### ISSUE TITLE
Swagger : ARM network route-table route create expecting --next-hop-ip-address for every  --next-hop-type

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#564]
The below command creating route-table route of --next-hop-type as 'VirtualNetworkGateway' asking for --next-hop-ip-address parameter, even though --next-hop-ip-address parameter is valid only for next hop type <b>VirtualAppliance</b>
![image](https://cloud.githubusercontent.com/assets/11171941/11977532/a8809c3c-a9a9-11e5-946d-6128906ea9b6.png)

**Comment by romangromov** [comment]
@sreekanthbs should be fixed now

**Comment by sreekanthbs** [comment]
@romangromov It is working fine now.
<pre>
<code>C:\Dec2015\24Dec\azure-xplat-cli-swagger-networking>node bin/azure network route-table route create armresgrpswagger tryaRoute1 -n tryRTRoute1 --next-hop-type V
irtualNetworkGateway -a 10.0.0.0/23
info:    Executing command network route-table route create
+ Looking up Route Table "tryaRoute1"
+ Looking up route "tryRTRoute1" in route table "tryaRoute1"
+ Creating route "tryRTRoute1" in a route table "tryaRoute1"
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrpswagger/providers/Microsoft.Network/route
Tables/tryaRoute1/routes/tryRTRoute1
data:    Name                            : tryRTRoute1
data:    Provisioning state              : Succeeded
data:    Next hop type                   : VirtualNetworkGateway
data:    Address prefix                  : 10.0.0.0/23
info:    network route-table route create command OK
</code>
</pre>
