### ISSUE TITLE
Swagger : ARM network local-gateway list with out optional parameters is giving error

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#565]
![image](https://cloud.githubusercontent.com/assets/11171941/11977898/e7e7dbf8-a9ac-11e5-9c0d-04b31651995e.png)

**Comment by romangromov** [comment]
@sreekanthbs fixed, please note: for `local-gateway` a `resource-group` parameter is required, we can't list local gateways for all of resource groups

**Comment by sreekanthbs** [comment]
@romangromov It is working fine now.
<pre>
<code>
C:\Dec2015\24Dec\azure-xplat-cli-swagger-networking>node bin/azure network local-gateway list -h
help:    Get all local networks gateways
help:
help:    Usage: network local-gateway list [options] <resource-group>
help:
help:    Options:
help:      -h, --help                             output usage information
help:      -v, --verbose                          use verbose output
help:      -vv                                    more verbose with debug output
help:      --json                                 use json output
help:      -g, --resource-group <resource-group>  the name of the resource group
help:      -s, --subscription <subscription>      the subscription identifier
help:
help:    Current Mode: arm (Azure Resource Management)

C:\Dec2015\24Dec\azure-xplat-cli-swagger-networking>node bin/azure network local-gateway list armresgrpswagger
info:    Executing command network local-gateway list
+ Looking up local network gateways
data:    Name              Location  Resource group    Provisioning state  IP Address  Address prefixes
data:    ----------------  --------  ----------------  ------------------  ----------  ----------------
data:    trylocalgateway1  westus    armresgrpswagger  Succeeded           10.0.0.0    10.0.0.0/23
info:    network local-gateway list command OK
</code>
</pre>
