### ISSUE TITLE
Swagger : ARM network express-route circuit set commands is failing

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#566]
![image](https://cloud.githubusercontent.com/assets/11171941/11991063/c787aaca-aa3b-11e5-97fd-0303f2630564.png)

**Comment by romangromov** [comment]
Looks strange, stay tuned, need to consult to Networking team

**Comment by romangromov** [comment]
@sreekanthbs please check `Provisioning state` for this Circuit and let me know

**Comment by romangromov** [comment]
Steps to repro this issue:
1) create new Circuit, ProvisioningState=Succeeded 
2) try to update this Circuit with any simple change, like tags
3) getting InternalError from server, now Circuit have ProvisioningState=Failed forever

**Comment by sreekanthbs** [comment]
ProvisioningState=Failed for the failed one

**Comment by romangromov** [comment]
Ok, I've reported this to Deepak

**Comment by romangromov** [comment]
From Nupur Kothari <nkothar@microsoft.com>

```
I looked into this, and it looks like you tried to downgrade bandwidth, which is not allowed
```

Upgrading bandwidth working fine, closing issue
