### ISSUE TITLE
Swagger : ARM network vpn-connection create is Failing

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#567]
ARM network vpn-connection create is failing and the Provisioning State is 'Failed'
![image](https://cloud.githubusercontent.com/assets/11171941/11994419/fc35f024-aa63-11e5-8f46-7d6a3ceaca64.png)
![image](https://cloud.githubusercontent.com/assets/11171941/11994421/0bbec3ae-aa64-11e5-8bf1-1e4a139e36b0.png)

**Comment by romangromov** [comment]
@sreekanthbs try `WestEurope` location for Gateways and Connection and let me know

**Comment by sreekanthbs** [comment]
@romangromov Even with WestEurope location also giving same error
<pre>
<code>C:\Dec2015\24Dec_1\azure-xplat-cli-swagger-networking>node bin/azure network vpn-connection create armresgrpswagger tryvpnconnection1 WestEurope -i tryVpngatewa
y1 -e tryVpngateway3 -y Vnet2Vnet -k abc123 -t tag1=val1;tag2=val2
info:    Executing command network vpn-connection create
warn:    Using default weight: 0
+ Looking up virtual network gateway "tryVpngateway1"
+ Looking up virtual network gateway "tryVpngateway3"
+ Looking up gateway connection "tryvpnconnection1"
+ Creating gateway connection "tryvpnconnection1" between "tryVpngateway1" and "tryVpngateway3"
error:   Long running operation failed with status: 'Failed'.
info:    Error information has been recorded to C:\Users\sreekanth.bandaru\.azure\azure.err
error:   network vpn-connection create command failed
</code>
</pre>

**Comment by romangromov** [comment]
@sreekanthbs confirm that Gateways creating in WestEurope location

**Comment by romangromov** [comment]
Finally resolved, here is complete list of Vnet Settings:

```
 location for all resources = WestEurope
  vnetAddressPrefix1 = '10.1.0.0/16',
  vnetAddressPrefix2 = '10.2.0.0/16',
  subnetprefix1 = 'GatewaySubnet',
  subnetprefix2 = 'GatewaySubnet',
  subnetAddressPrefix1 = '10.1.0.0/28',
  subnetAddressPrefix2 = '10.2.0.0/28',
  privateIpAddress1 = '10.1.0.11',
  privateIpAddress2 = '10.2.0.11',
```

**Comment by romangromov** [comment]
```
info:    Executing command network vpn-connection create
+ Looking up virtual network gateway "MyGateway1"
+ Looking up virtual network gateway "MyGateway2"
+ Looking up gateway connection "MyVPNConnection"
+ Creating gateway connection "MyVPNConnection" between "MyGateway1" and "MyGateway2"
data:    Id                              : /subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/test-roman-group/providers/Microsoft.Network/connections/MyVPNConnection
data:    Name                            : MyVPNConnection
data:    Type                            : Microsoft.Network/connections
data:    Location                        : westeurope
data:    Provisioning state              : Succeeded
data:    Connection type                 : Vnet2Vnet
data:    Routing weight                  : 11
data:    Shared key                      : abc
data:    Virtual network gateway 1       : /subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/test-roman-group/providers/Microsoft.Network/virtualNetworkGateways/MyGateway1
data:    Virtual network gateway 2       : /subscriptions/2c224e7e-3ef5-431d-a57b-e71f4662e3a6/resourceGroups/test-roman-group/providers/Microsoft.Network/virtualNetworkGateways/MyGateway2
data:    Bytes transferred:
data:      Egress                        : 0
data:      Ingress                       : 0
info:    network vpn-connection create command OK
```

working fine, closing issue
