### ISSUE TITLE
Swagger : ARM network local-gateway set is failing

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#569]
network local-gateway set is giving error : Long running operation failed with status: 'Failed'
![image](https://cloud.githubusercontent.com/assets/11171941/12017493/5c123e50-ad7d-11e5-98cc-a165d0cdbf9c.png)

**Comment by romangromov** [comment]
@sreekanthbs the error message doesn't contain any info, so please try to use another address prefix: 
`10.1.0.0/23`

**Comment by sreekanthbs** [comment]
@romangromov With another address prefix, it is working fine.
<pre>
<code>
C:\Dec2015\28Dec\azure-xplat-cli-swagger-networking>node bin/azure network local-gateway set armresgrpswagger trylocalgateway1 -a 10.1.0.0/23
info:    Executing command network local-gateway set
+ Looking up local network gateway "trylocalgateway1"
+ Updating local network gateway "trylocalgateway1"
data:    Id                              : /subscriptions/bfb5e0bf-124b-4d0c-9352-7c0a9f4d9948/resourceGroups/armresgrpswagger/providers/Microsoft.Network/local
NetworkGateways/trylocalgateway1
data:    Name                            : trylocalgateway1
data:    Type                            : Microsoft.Network/localNetworkGateways
data:    Location                        : westus
data:    Provisioning state              : Succeeded
data:    Tags                            : tag1=val1;tag2=val2
data:    IP Address                      : 10.0.0.0
data:    Address prefixes:
data:      10.0.0.0/23
data:      10.1.0.0/23
info:    network local-gateway set command OK
</code>
</pre>
