### ISSUE TITLE
Swagger : ARM network nic create with  --lb-address-pool-ids and  --lb-inbound-nat-rule-ids options failing

### ISSUE THREAD

**Issue by sreekanthbs** [MSOpenTech/azure-xplat-cli#570]
ARM network nic create with  --network-security-group-id, --subnet-id, --lb-address-pool-ids and  --lb-inbound-nat-rule-ids is failing.
![image](https://cloud.githubusercontent.com/assets/11171941/12018390/e43d6e08-ad87-11e5-9528-aa4487bb041b.png)

**Comment by romangromov** [comment]
@sreekanthbs I've open communication about this, stay tuned

**Comment by romangromov** [comment]
Related issue https://github.com/MSOpenTech/azure-xplat-cli/issues/568

**Comment by romangromov** [comment]
@sreekanthbs  should be fixed now, please verify

**Comment by romangromov** [comment]
@sreekanthbs  should be fixed now, please verify

**Comment by sreekanthbs** [comment]
@romangromov It is working fine now. Hence closing the issue.
