### ISSUE TITLE
ARM application gateway set errors

### ISSUE THREAD

**Issue by MikhailTryakhov** [MSOpenTech/azure-xplat-cli#578]
Every set commands failed because of incorrect requireServerNameIndication parameter checking.
SDK checks for string type, but it's boolean value
![](http://i.imgur.com/nMnsGo9.png)

**Comment by romangromov** [comment]
@MikhailTryakhov you can fix SDK issues and send PR to azure-sdk-for-node, because we are using swagger spec now

**Comment by MikhailTryakhov** [comment]
Duplicates [Azure-sdk-for-node#1603](https://github.com/Azure/azure-sdk-for-node/issues/1603)

**Comment by romangromov** [comment]
@MikhailTryakhov why this closed? Even this is related to SDK itself - anyway `set` command in xplat-cli do not work correctly, that is why we need to keep this open..

**Comment by MikhailTryakhov** [comment]
@romangromov added workaround
